### ISSUE TITLE
Link to manifest-app-info in the README

### ISSUE THREAD

**Issue by xfq** [w3c/manifest#1027]
It always takes some time for me to find the manifest-app-info repo from here. It would be great if there's a link to it in the README.md. I can send a PR if you think it's useful.

**Comment by MdAbulHossain1** [comment]
chrome-extension://ofhbbkphhbklhfoeikjpcbhemlocgigb/_generated_background_page.html

**Comment by MdAbulHossain1** [comment]
> It always takes some time for me to find the manifest-app-info repo from here. It would be great if there's a link to it in the README.md. I can send a PR if you think it's useful.
chrome-extension://ofhbbkphhbklhfoeikjpcbhemlocgigb/_generated_background_page.html

**Comment by aarongustafson** [comment]
@xfq Go for it!
