### ISSUE TITLE
What's the default value of the `id` member if no `start_url` is provided?

### ISSUE THREAD

**Issue by benfrancis** [w3c/manifest#1038]
If no `id` or `start_url` member is provided, what is the value of the processed `id`?

As I understand it, `id` is essentially meant to default to `start_url`, but what does `start_url` default to?

The  [`start_url` algorithm](https://w3c.github.io/manifest/#start_url-member) says:
> If json["start_url"] doesn't exist... return"

The [`id` algorithm](https://w3c.github.io/manifest/#id-member) says:
> If the type of json["id"] is not [string](https://infra.spec.whatwg.org/#string), return.

but then what?

I'm probably just not understanding the way the algorithms are written, does return mean something other than "stop executing the algorithm"?

**Comment by alancutter** [comment]
These algorithms take a manifest out parameter that's passed in in the overall processing a manifest algorithm.
https://w3c.github.io/manifest/#dfn-processing-a-manifest
I'm a bit surprised there doesn't seem to be anywhere that defaults it to the document URL or declares it invalid and unable to be installed or something.
