### ISSUE TITLE
TPAC 2022 status report

### ISSUE THREAD

**Issue by LJWatson** [w3c/manifest#1046]
[TPAC 2022 ](https://www.w3.org/2022/09/TPAC/) is hybrid this year. WebApps will meet in Vancouver on [12 and 13 September](https://www.w3.org/calendar/tpac2022/). Please [register](https://www.w3.org/2022/09/TPAC/registration.html) if you plan to attend in person or remotely.

Editors, we need you to do two things before 30 August 2022:

1. If you want agenda time to discuss your spec(s), please use W3C/webappswg#87 to request it
2. Complete a status report for your spec(s)

#### Status report

Your status report should answer these questions (as a comment on this issue):

1. What progress has your spec made in the last 12 months?
2. Is anything blocking your spec from moving to CR/Rec?
3. If yes, what is your plan to unblock it and do you need any help?

Please post a status report on your spec(s) even if you do not plan to attend TPAC at all.

CC @marcoscaceres and @siusin

**Comment by dmurph** [comment]
Just do document, I would love to chat about
* pending issues that are blocking CR
* updating security sensitive manifest members (@alancutter has been doing a lot of thinking here)
* ...

**Comment by dmurph** [comment]
I'd also like to chat about how we plan on adding new display modes to the spec, especially incubation display modes (e.g. https://wicg.github.io/window-controls-overlay/#addition-of-window-controls-overlay-to-the-manifest).

These display modes used to be in our spec, and now they live here: https://www.w3.org/TR/mediaqueries-5/#display-modes

**Comment by mgiuca** [comment]
We'd also like to discuss [scope extensions](https://github.com/WICG/manifest-incubations/blob/gh-pages/scope_extensions-explainer.md) and [launch handler](https://github.com/WICG/sw-launch/blob/main/launch_handler.md). (Related so they can go together.)

**Comment by mgiuca** [comment]
@luhuangmsft can speak to scope extensions, @dmurph can speak to launch handler.
