### ISSUE TITLE
related_applications needs more settings

### ISSUE THREAD

**Issue by jplevene** [w3c/manifest#1047]
"related_applications" needs more settings like "edge_web_store", "safari_web_store" and "google_workspace"

**Comment by alancutter** [comment]
Strange that Github doesn't link to the page this is commenting on: https://github.com/w3c/manifest/wiki/Platforms

**Comment by tomayac** [comment]
Technically it's simply a Wiki (I seem to have edit rights). What's the process for adding new platforms?

**Comment by duniataymi** [comment]
I need to "apklis" for Cuba

**Comment by dmurph** [comment]
The wiki has been restored, however edit access has been removed as someone deleted all of it. We are happy to add more stores - but likely will need those stores to support this, so we should only add to these if the store reaches out.

Closing this, unless a store representative reaches out / implementer who is implementing the connection to these stores.
