### ISSUE TITLE
About update icon in web app manifest

### ISSUE THREAD

**Issue by nhuttm** [w3c/manifest#1049]
I have a problem about update icon in web app manifest. The user already installed PWA app on their machine and I want to update new icons. As the document said that we need [express permission](https://www.w3.org/TR/permissions/#dfn-express-permission) from the user to automatically apply changes but I don't know which permission I need to ask the user.
As the document said the user agent could present options to the user, but I don't know how to present options accept the update and update icon in user machine.
<img width="889" alt="image" src="https://user-images.githubusercontent.com/51075198/187401970-1d1e39ae-6056-4525-8d0c-311001ee4a4a.png">

**Comment by tomayac** [comment]
There is no developer-facing permission or anything. All you have to do is update your Web App Manifest. The browser then decides how to present potential changes to the user and lets them approve the change. For example, in Chromium, this behavior is still being iterated on. Track https://crbug.com/926083 for updates.

The core threat is:
- The user installs a harmless PWA like, say, a Tetris game.
- The PWA, after a couple of days, replaces its icon and name with, say, "Chase Bank", and the [Chase icon](https://www.chase.com/etc/designs/chase-ux/favicon-152.png).
- The user opens the turned-evil "Tetris" app, thinking it is the Chase Bank" app.

**Comment by dmurph** [comment]
Minutes here: https://www.w3.org/2022/09/13-webapps-minutes.html

Alan & I will meet soon to go over discussion and chat about the proposals.
