### ISSUE TITLE
Manifest: property 'src' ignored, URL is invalid.

### ISSUE THREAD

**Issue by wenanoshe** [w3c/manifest#1059]
```
Manifest: property 'start_url' ignored, URL is invalid.
Manifest: property 'src' ignored, URL is invalid.
```
I got this two warning in console, but it only appears in when I build, and not in localhost

```js
// _manifest.json_
{
  "short_name": "Quick weather",
  "name": "Weather app PWA",
  "description": "Search the weather for any place of the world quickly",
  "icons": [
    {
      "src": "./images/icon-quick-weather.png",
      "type": "image/png",
      "sizes": "460x460"
    },
    {
      "src": "./images/icon-quick-weather(180x180).png",
      "type": "image/png",
      "sizes": "180x180"
    },
    {
      "src": "./images/icon-quick-weather(512x512).png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ],
  "start_url": ".",
  "display": "standalone",
  "theme_color": "#3399ff",
  "background_color": "#fff"
}
```

**Folder structure**
![image](https://user-images.githubusercontent.com/78445203/198746267-583b7a44-ad68-425b-a6a2-affb790b1470.png)

**Comment by marcoscaceres** [comment]
@wenanoshe, I think this might be an implementation issue, not a spec issue. 

What browser did this happen in?

**Comment by wenanoshe** [comment]
> @wenanoshe, I think this might be an implementation issue, not a spec issue.
> 
> What browser did this happen in?

In Brave browser

**Comment by dmurph** [comment]
Looking at the url parsing spec: https://url.spec.whatwg.org/#url-parsing

I believe a single `.` is not a valid url, even if base_url is populated? It looks like that is correctly parsed if you get into "path state" (https://url.spec.whatwg.org/#path-state), but the parser is not initially in path state.

It's better to use absolute URLs in general, they clear up a lot of potential errors.

**Comment by marcoscaceres** [comment]
Yeah, that's strange... "." should be valid though. Checked in the dev console:

```JS
new URL(".", "https://example.com");
```

**Comment by wenanoshe** [comment]
I tried this in **manifest.json**
`  "start_url": "https://quickweather.vercel.app/",
`
Here is the deployment (https://quickweather.vercel.app/)

**Comment by marcoscaceres** [comment]
Closing as answered.

**Comment by wenanoshe** [comment]
I was using relative paths like @dmurph said, I just changed all icon paths to absolute and it solved

**Comment by ahmed-abdat** [comment]
I'm also have the same issue how do you solve it?

**Comment by chrisrob** [comment]
Could this be related to the fact that virtually all browsers now no longer request relative urls along with a 'base' header? They only submit fully resolved absolute urls and http headers do not support 'base'.
