### ISSUE TITLE
About updating the manifest

### ISSUE THREAD

**Issue by NhutTran98** [w3c/manifest#1060]
I have an issue with updating the manifest file. I added new property `file_handlers` in our web app manifest but it doesn't update installed pwa app. I have been waiting over 2 days but it still keeping old PWA app manifest.
https://web.dev/manifest-updates/

**Comment by marcoscaceres** [comment]
hi @NhutTran98... this might be an implementation issue, not a spec issue.. 

What browser did this happen in? I'm assuming Chrome, as it's not supported in WebKit. 

CC @dmurph

**Comment by NhutTran98** [comment]
hi @marcoscaceres, I'm using Chrome with latest version. It still working if I install in a new machine but with PWA app installed before it still not update.

**Comment by alancutter** [comment]
Please file a bug with Chromium at crbug.com with more details for investigation and link to it here.
