### ISSUE TITLE
Ability to override the back button behavior

### ISSUE THREAD

**Issue by christianliebel** [w3c/manifest#1064]
I received a feature request where the developer wants to have more fine-granular control over the behavior of the device's back button when the app is installed. Cordova has a `backbutton` event that allows developers to override the default behavior (i.e., navigating back): https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.backbutton.html

Perhaps this would be worth exploring.

**Comment by kenchris** [comment]
This ties into the Navigation API, please check: https://wicg.github.io/navigation-api/#sp-navigation-monitoring-interception

**Comment by kenchris** [comment]
https://github.com/WICG/navigation-api/issues/32

**Comment by kenchris** [comment]
https://github.com/WICG/navigation-api/issues/32#issuecomment-1290040557 https://chromium-review.googlesource.com/c/chromium/src/+/3868615

**Comment by christianliebel** [comment]
@kenchris Ah, very cool! Didn't know about that. Thank you.

**Comment by dmurph** [comment]
I'm going to close this as it seems like this was solved through navigation API. Feel free to re-open if not
