### ISSUE TITLE
No way to localize icons?

### ISSUE THREAD

**Issue by aphillips** [w3c/manifest#1077]
Declaring multiple icons
https://w3c.github.io/manifest/#declaring-multiple-icons

> In the following example, the developer has made the following choices about the icons associated with the web application (etc.)

There are ways to include multiple icons with different `sizes`, but there is no way to indicate when these should be used with specific locales, such as when the icon contains localizable text or when there are regional variations in the icon.

**Comment by valioDOTch** [comment]
Wouldn't it make more sense to serve a localized manifest based on the clients preferred language, that would also provide the corresponding "lang" attribute in the manifest?

**Comment by aphillips** [comment]
Serving a correctly localized manifest certainly makes sense, but this can be a little complicated. If the manifest files are not generated dynamically but instead use path or file-naming to separate them, an application might choose to bundle a number of related locales together with locally variant icons. For example:

```json
"lang": "fr",
"dir": "ltr",
"name": "une application",
"icons":  [
    {
        "lang": "fr-FR",
        "comment": "a bit of bleu-blanc-rouge",
        "src": "icon-for-france.jpg"
    },
    {
        "lang": "fr-CH",
        "comment": "red with a little white +",
        "src": "icon-for-suisse.jpg"
    },
    {
        "comment": "no special flag-related motif",
        "src": "default-french-icon.jpg"
    }
]
```

**Comment by christianliebel** [comment]
#1101 would introduce a way to localize icons:

```json
{
  "lang": "en-US",
  "icons": [
    { "src": "icon/lowres.png", "sizes": "64x64" },
    { "src": "icon/hires.png", "sizes": "256x256" }
  ],
  "icons_localized": {
    "fr": [
      { "src": "icon/lowres_fr.png", "sizes": "64x64" },
      { "src": "icon/hires_fr.png", "sizes": "256x256" }
    ]
  }
}
```
