### ISSUE TITLE
No language/direction metadata for shortcuts?

### ISSUE THREAD

**Issue by aphillips** [w3c/manifest#1078]
1.1.4 Creating shortcuts 
https://w3c.github.io/manifest/#creating-shortcuts

Multiple examples are provided of creating a "shortcut" in a manifest. Here is one such:

```
  "shortcuts": [
    {
      "name": "Play Later",
      "description": "View the list of podcasts you saved for later",
      "url": "/play-later",
      "icons": [
        {
          "src": "/icons/play-later.svg",
          "type": "image/svg+xml"
        }
      ]
    },
```

The `name` and `description` fields do not have their own `lang` and `dir` values nor does the "shortcut" structure have the ability to provide an override. The whole manifest does have a `lang` and `dir`, but this doesn't allow for separate localizations nor for local overrides of the values. I18N normally recommends the ability to provide a local override when there is file-level metadata.

This design also suggests that some language is more privileged than all others or that large sections of the file must be repeated in order to localize the full experience described by the manifest.

**Comment by tomayac** [comment]
Sorry, @aphillips, realizing that this is part of a bigger [`i18n-needs-resolution`](https://github.com/w3c/manifest/labels/i18n-needs-resolution) effort. Reopening.

**Comment by aphillips** [comment]
@tomayac thanks! Feel free to mark as duplicate any of the items I just filed or to link to on-going work.

**Comment by aarongustafson** [comment]
This is part & parcel of the translations work, no? Once we solve it for the manifest overall, it'll be solved for shortcuts. We don't need a before solution just for shortcuts.

**Comment by christianliebel** [comment]
#1101 would not add language/direction metadata for shortcuts. They would still be inherited from the manifest itself. However, specifying language/direction metadata for their localized versions would be possible.

@aphillips Let me know if this is not sufficient.

**Comment by aphillips** [comment]
@christianliebel Ideally one could override the language or direction of the shortcut separately, but the need to do this should be rare. The localized values have the ability to override their own associated language tag (super rare) and provide their own direction (common for the localized case, but rare for the default value). 

I don't think you need to overcomplicate the format to support this, given that, for most applications, the actual string will come from the localized versions (or the application will be entirely use the default).
