### ISSUE TITLE
"localizable members" should be defined separately?

### ISSUE THREAD

**Issue by aphillips** [w3c/manifest#1080]
`dir` member
https://w3c.github.io/manifest/#dir-member

> The localizable members are:
> 
>    [name](https://w3c.github.io/manifest/#dfn-name) member.
>    [short_name](https://w3c.github.io/manifest/#dfn-short_name) member.
>    [Shortcut item's](https://w3c.github.io/manifest/#dfn-shortcut-item) [name](https://w3c.github.io/manifest/#dfn-name-0) member.
>    [Shortcut item's](https://w3c.github.io/manifest/#dfn-shortcut-item) [short_name](https://w3c.github.io/manifest/#dfn-short_name-0) member.
>    [Shortcut item's](https://w3c.github.io/manifest/#dfn-shortcut-item) [description](https://w3c.github.io/manifest/#dfn-description) member.

This is more of an editorial comment than it is a technical objection.

The section about the `dir` member defines the term "localizable member" and includes the above definition of which fields are localizable. It seems like "localizable" should be defined separately so that it can be referred to by various members and sub-members as appropriate and so that the list of items belonging to it doesn't inadvertently become stale.

Note that "localization" encompasses more than just translation of strings. It can and often does include changing other items found in a manifest, such as icons, colors, and such. The textual items are important, of course, and are related to direction and language metadata more directly than (say) an icon, but this shouldn't be overlooked.

**Comment by christianliebel** [comment]
#1101 would change this and mark the single members as localizable.
