### ISSUE TITLE
Don't re-specify aspects of the UBA

### ISSUE THREAD

**Issue by aphillips** [w3c/manifest#1081]
`dir` member
https://w3c.github.io/manifest/#dir-member

> If the [base direction](https://w3c.github.io/manifest/#dfn-base-direction) is [ltr](https://w3c.github.io/manifest/#dfn-ltr) or [rtl](https://w3c.github.io/manifest/#dfn-rtl), override [Rule P3](https://www.unicode.org/reports/tr9/tr9-46.html#P3) of [[BIDI](https://w3c.github.io/manifest/#bib-bidi)], setting the paragraph embedding level to 0 if the [base direction](https://w3c.github.io/manifest/#dfn-base-direction) is [ltr](https://w3c.github.io/manifest/#dfn-ltr), or 1 if the [base direction](https://w3c.github.io/manifest/#dfn-base-direction) is [rtl](https://w3c.github.io/manifest/#dfn-rtl).

The reference to BIDI should probably use the canned definition for UAX9 instead of defining a separate locally maintained copy.

The I18N WG notes that specifying the aspects of UBA here seems like overkill: you are transmitting metadata. It is up to implementations to use direction metadata appropriately.

**Comment by marcoscaceres** [comment]
Yeah, true... it's overly prescriptive. Let's do this in two parts tho... updating the reference is the easy part.
