### ISSUE TITLE
`name` and `short_name` (and other localizable member's) relationship to localization and accessibility

### ISSUE THREAD

**Issue by aphillips** [w3c/manifest#1085]
`name` member
https://w3c.github.io/manifest/#name-member

> The [manifest's](https://w3c.github.io/manifest/#dfn-manifest) name member is a [string](https://infra.spec.whatwg.org/#string) that represents the [name](https://w3c.github.io/manifest/#dfn-name) of the web application as it is usually displayed to the user (e.g., amongst a list of other applications, or as a label for an icon).
>
> The name member serves as the [accessible name](https://www.w3.org/TR/accname-1.2/#dfn-accessible-name) of an [installed web application](https://w3c.github.io/manifest/#dfn-installed-web-application).

The "accessible name" and the display name (or its `short_name` equivalent) really should be localized to match the expectation of the user. Many apps are localized into many languages, but the design of manifest (with `lang` and `dir` as top level items applying to *all* values inside the manifest and an on-going discussion about localization) suggests that this is not yet fully baked.

**Comment by christianliebel** [comment]
#1101 hopefully addresses this.
