### ISSUE TITLE
"security sensitive" items interaction with localization

### ISSUE THREAD

**Issue by aphillips** [w3c/manifest#1086]
Updating the manifest
https://w3c.github.io/manifest/#updating

> For the purpose of updating, the following member are security-sensitive members, as they are presented during installation and on launch surfaces:
>
> *    [short_name](https://w3c.github.io/manifest/#dfn-short_name),
> *    [icons](https://w3c.github.io/manifest/#dfn-icons)
> *    [name](https://w3c.github.io/manifest/#dfn-name),

These items are all localizable. If an app adds a new locale to the list of supported locales and this locale matches that of the user, should the app be required to report updating the name/short name/icon? Probably the answer is yes, but I18N wants to call out the interaction. The spec text ***assumes*** that there is only one (unlocalized) value for the name and short name. Also, note that users sometimes change their device locale...

**Comment by christianliebel** [comment]
In #1101, I propose to update the app name/icon automatically to match the new locale if the user changes it, but display an update notification the next time the user opens the app.
