### ISSUE TITLE
shortcuts and localizability

### ISSUE THREAD

**Issue by aphillips** [w3c/manifest#1087]
Shortcut items
https://w3c.github.io/manifest/#shortcut-items

Shortcuts are a separate structure inside the manifest that include a `name`, `short_name`, `description`, `icon`, and `url` for some operation that can be invoked on an app or invoke an app with additional arguments. The same concerns about localizability of the shortcuts applies as it does to the `name` and `short_name` at the manifest level, although with the additional note that shortcuts often appear inside the system's user interface (such as context menus) and want to be localized to match the system whenever possible (and that the system locale can be changed by the user after app installation)

**Comment by christianliebel** [comment]
#1101 adds localization support for `name`, `short_name`, `description`, and `icon`.
