### ISSUE TITLE
Way to detect if a web app is installed

### ISSUE THREAD

**Issue by dmurph** [w3c/manifest#1116]
Feedback here: https://issues.chromium.org/issues/331692948#comment15

> For us, with the PWA, we offer more UI options primarily to match the PC native app and provide additional control options, such as a refresh button, because we know users don't have access to browser tools.
> 
> As a small example, we always hide the website's navbar when a user is logged in on the PWA. This provides more screen real estate for the app since we understand that's the main focus. We prefer users not to see the logout and settings options, which are rarely used; instead, they have to click to show the side menu.

This is supportive evidence for an 'installed' attribute that can be media-queried.

**Comment by marcoscaceres** [comment]
I think this is a duplicate of https://github.com/w3c/manifest/issues/1092

**Comment by dmurph** [comment]
Close as duplicate
