### ISSUE TITLE
A means to control the "theme color"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#225]
When an application is launched in standalone mode (or any mode that shows a status bar), it would be nice to be able to have a way of controlling the color of the status bar. 

Proprietary examples:
* IE' [mapplication-navbutton-color](http://msdn.microsoft.com/en-us/library/gg491732%28v=vs.85%29.aspx#msapplication-navbutton-color), 
* iOS's [apple-mobile-web-app-status-bar-style](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html)

See also [Chromium's Intent to Implement and ship: brand-color meta tag](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/nzRY-h_-_ig/KR3XWn73tDoJ)

**Comment by Volker-E** [comment]
@marcosc I'm with you here, in various use cases we're crowding web pages with `meta` tags targeting just a small group of users, on the other hand trying to squeeze out every bit to make pages perform better. 

I'd like to see the possibility to include a "default theme color" in the manifest and if some people wish, they could override it with a maniputable `meta` tag per page.

**Comment by marcoscaceres** [comment]
On February 8, 2015 at 10:47:32 AM, Volker E. (notifications@github.com) wrote:
> > I'd like to see the possibility to include a "default theme color"  
> in the manifest and if some people wish, they could override it  
> with a maniputable meta tag per page.

Yeah, I'd also like to add this. However, I'm want to wait a bit until we get manifest into some products. At the very least, I guess I can draft it up and just leave it sitting in a feature branch.

**Comment by mounirlamouri** [comment]
Why do we need theme color in the Manifest? Is anyone going to use it? It can't be used in Chrome because the theme color needs to be available at first paint and we can't have the Manifest available at first paint.

What makes you think theme-color in the Manifest is better than having it as a <meta> tag?

**Comment by Volker-E** [comment]
@mounirlamouri Thanks for clarification. Reason for color in manifest (if there weren't the first-paint problem): Cacheability & not cluttering HTML output with directives just useful on a minority of applications.

**Comment by marcoscaceres** [comment]
> Why do we need theme color in the Manifest? Is anyone going to use it? 

We would like to be able to use `theme_color` in other contexts, like for making speed-dial cells (together with the icons). 

> It can't be used in Chrome because the theme color needs to be available at first paint and we can't have the Manifest available at first paint.

Yes, you would need to manage the theme color until the manifest is applied. However, once it's applied, then theme color would be available on first paint. It's not really different from, say, default orientation.

**Comment by mounirlamouri** [comment]
It seems that there is enough support for it. Closing.
