### ISSUE TITLE
Hope for external `start_url`s

### ISSUE THREAD

**Issue by cvan** [w3c/manifest#276]
Chrome apps require local paths ([`app.launch.local_path`](https://developer.chrome.com/extensions/apps#manifest)), but they do allow [`webview`s](https://developer.chrome.com/apps/app_external#webview) and cross-origin XHRs via [`permissions`](https://developer.chrome.com/apps/app_external#external) (similar to Firefox's SystemXHR).

Similarly, Firefox apps do not allow external `launch_path`s https://bugzil.la/786710 - but SystemXHR, iframes, and redirects help a little bit to workaround that restriction.

Considering that the spec says `start_url` has the same same-origin restriction, is there a future where we can allow external `start_url`?

It's hacky, but to get around this, I'm just going to set a `start_url` to `https://myserver.org/?https://facebook.com/`, call my app Facebook, and let users install it to their homescreens.

If I can already do that redirect, why enforce the same-origin restriction in the first place for `start_url`.

Forgive my ignorance if any of the above is untrue. Thanks for listening!

<hr>

_Related: https://github.com/w3c/manifest/issues/114#issuecomment-62952898_

**Comment by derlin** [comment]
any news on this opening ?

**Comment by marcoscaceres** [comment]
Don't think so. It would just break too many things :(
