### ISSUE TITLE
Consider making display a space-separated list of tokens

### ISSUE THREAD

**Issue by foolip** [w3c/manifest#304]
http://w3c.github.io/manifest/#display-member

This is a bit speculatory, but on Android there are a lot of flags for different variants of fullscreen:
https://developer.android.com/reference/android/view/View.html#setSystemUiVisibility(int)

*If* there are aspects of display mode that are conceptually orthogonal *and* that can be controlled independently on Android and other platforms, it may make sense to separate these. If not, please ignore me :)

**Comment by kenchris** [comment]
I think that at least we need to look at immersive mode which is supported on newer Android versions. 

Fullscreen on Android doesn't mean that the OS navigation buttons are hidden, but immersive allows both statusbar and navigation buttons to be so, but also making both appear (overlayed) when swiping up or down from outside the screen. Games, in particular are starting to take advantage of this.

On an interesting note, most apps don't use immersive mode when launching (so you can still press back and exit, or go to the menu etc) and first enter immersive mode when it is ready to be used. For instance check out Peggle Blast on Android Lollipop.

**Comment by foolip** [comment]
If the Fullscreen API use immersive mode I guess that could be used to replicate the "default mode first, then immersive", but my colleague @mo speculates that the reason Android apps currently use this model is that immersive mode is so new that you'll want to enable only after launching based on run-time checks.

There's also SYSTEM_UI_FLAG_LOW_PROFILE where the buttons become little dots...

**Comment by marcoscaceres** [comment]
Allowing display to be a space-separated list of tokens could make sense. However, I'm inclined to sit on this for a bit and see how we go with initial implementations. The current set of choices in the spec represents agreement amongst potential implementers on what can be supported across the largest set of OSs. As such, I wouldn't want to expand that list until we start getting more feedback from developers that they want this - and until we figure out who can support the additional modes and what should happen on OSs that don't support those modes.  

@foolip wdyt?

**Comment by foolip** [comment]
That's fine by me, I'm not involved with implementing this and so can't make very concrete suggestions, I just wanted raise this in case it had not been considered. I think that as soon as someone tries to implement the fullscreen or minimal-ui mode on Android the question will become relevant.

**Comment by marcoscaceres** [comment]
Closing for now.
