### ISSUE TITLE
check against security/privacy questions

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#305]
https://mikewest.github.io/spec-questionnaire/security-privacy/

**Comment by marcoscaceres** [comment]
Need to run through this list before we send to webappsec. Need to make sure we have good answers to any questions that apply or they'll eat us alive. 

💀🙈🙉🙊

**Comment by mikewest** [comment]
Yes. We do that. Eating people, I mean. Alive.

**Comment by mikewest** [comment]
(The document is a total strawman; I think the questions are good ones, but the document needs a lot of work. Your feedback would be welcome!)

**Comment by marcoscaceres** [comment]
On Saturday, January 17, 2015, Mike West <notifications@github.com> wrote:

> Yes. We do that. Eating people, I mean. Alive.
>

I've seen it. It's just.. not right :)

**Comment by marcoscaceres** [comment]
(Can other people please check this ... I wrote these out in long form in case we want to integrate this at various points in the spec)

### deal with personally-identifiable information?
No. Not more than for any other resource.  

### deal with high-value data?
This specification does not directly deal with high-value data. However, installed applications and their data could be seen as "high value". 


### introduce new state for an origin that persists across browsing sessions?
This specification introduces new state for an origin that persists across browsing sessions. The scope member can restrict navigation to a set of URLs (in as far as it represents the scope to which the manifest is applied) - forcing URLs outside the scope to be directed elsewhere (maybe even to another user agent). 

Additionally, scope member can be used to capture a set of URLs.  

### expose cross-origin persistent state to the web?

Maybe. Usure if the display-mode: media feature counts. 

### expose any other data to an origin that it doesn’t currently have access to?

No. 

### enable new script execution mechanisms?

No. However, it does allow reuse of existing mechanisms.  

### allow an origin access to a user’s location?

No. 

### allow an origin access to sensors on a user’s device?

No. 

### allow an origin access to aspects of a user’s local computing environment?
This specification allows an origin access to aspects of a user’s local computing environment: Through a CSS media query, a script can know the display mode that a web application is in. An attacker could, in such a case, create a repli of browser chrome

### allow an origin access to other devices?

No. 

### allow an origin some measure of control over a user agent’s native UI?

This specification allows an origin some measure of control over a user agent’s native UI. In particular, the display mode can make the whole browser UI be hidden by putting the application into fullscreen. 

Furthermore, by neglecting to define an scope, it's possible to put an web application into a display mode that persists cros-origin.

For example, user installs example.com - which neglects to include a scope, but puts the app into `fullscreen`. The user navigates from within the app from example.com to foo.com. It is left to the user agent to either stop applying the manifest when a cross-origin navigation occurs or to show some sort of security warning to the user.

For instance, in Chrome Beta, the URL bar is displayed when a user goes from one domain to another.    

### expose origin-controlled data to an origin?

No. Not more than any other resource. 

### expose temporary identifiers to the web?

No. 

### distinguish between behavior in first-party and third-party contexts?

This specification distinguish between behavior in first-party and third-party contexts. In particular, if a `scope` member is declared in the manfiest, it is not possible to navigate the top-level browsing context to somewhere outside the scope while the manifest is being applied. 

### have a "Security Considerations" and "Privacy Considerations" section?

Yes.

**Comment by jmajnert** [comment]
lgtm

**Comment by mikewest** [comment]
Oh, hey! Sorry, I missed the update. This is nice to see!

Did you find the questionnaire helpful at all? Were any pieces simply nonsensical or unhelpful? Were any questions confusing?

**Comment by marcoscaceres** [comment]
> Did you find the questionnaire helpful at all?

Extremely! it prompted me to rethink a bunch of stuff from different angles. As you can see from https://github.com/w3c/manifest/commit/63f8448274a393faf9e0e31874621116d01e1971, this yielded a lot of additional considerations originally missing from the document. 

>  Were any pieces simply nonsensical or unhelpful?

No. It was broad in its approach (in a good way, as it covered both declarative + imperative APIs as well as data formats) and the questions were clear. It was good to have the concrete examples too - as it made it easy to adapt to our spec. 

> Were any questions confusing?

Not particularly. Again, having the detailed text plus examples helped clarify what was being asked. I did read through them a few times, but more because I felt like I was doing a fun university exam than because it was complicated. The only one I think I had trouble answering was "expose cross-origin persistent state to the web?" 

I would encourage you to just quickly read over all the answers and see if you would have answered them  similarly. I know there are no "right" answers, but I think it would be super insightful to see if the reader (i.e., "me") can get into the right frame of mind to answer the questions - as you intended.

If you have time to review the answers, I would really like to hear how you would have answered some things differently. 

Thanks again for putting together the questionnaire!
