### ISSUE TITLE
Clarify display-mode relationship to iframes and legacy content

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#309]
we need to look at how display-mode might be used by legacy content and detail how it should act in iframes etc.

**Comment by marcoscaceres** [comment]
@kenchris can you please give a summary of what's come up on blink-dev? 

Options I can see:

 * legacy content doesn't see `display-mode` media feature. 
 * legacy content does see `display-mode` media feature, and it just defaults to browser. 
 * iframes (including cross-origin) just inherit from the above.

**Comment by kenchris** [comment]
Sorry for being late about this, but been too busy!

* ChromeOS wants to use display-mode for existing chrome apps (and is adding support for minimum-ui) and existing standalone mode

**Comment by marcoscaceres** [comment]
I think we will do the same - and likely to work independently of manifest (i.e., a normal web page will match `display-mode: browser`). We already have support for most of the modes on desktop (fullscreen, standalone, and browser). We don't plan to do a minimal-ui right now.

**Comment by kenchris** [comment]
Yes, so we could add some text saying that it would be fine to support it even without the manifest or with different manifests (like ChromeApps)

**Comment by marcoscaceres** [comment]
Absolutely! Though we might get asked to split it into a new spec.
