### ISSUE TITLE
Add recommended width and height

### ISSUE THREAD

**Issue by yejingfu** [w3c/manifest#310]
Hi,
The spec seems not addressing the main window attributes such as width and height. For packaged apps, it's really nice to define the original window size when launching it. I am wondering if the spec can have window attributes like below:

    "window": {
        "width": 500,
        "height": 600
    }

If it's absent in manifest, the default size should be used.

**Comment by marcoscaceres** [comment]
@yejingfu, unfortunately, packaged apps are currently outside the scope of this spec.

**Comment by yejingfu** [comment]
@marcoscaceres Thank you for the information.
The window attributes are not limited to packaged apps IMO. It's also beneficial to web app.
Throughout the spec, I just find the "Display" modes do the similar thing: fullscreen, standalone, minimal-ui, browser. If the app is running in "standalone" or "minimal-ui" modes, it would be better to define the window original size. What do you think?

**Comment by marcoscaceres** [comment]
Personally, I don't think apps should be able to define their own sizes. This causes a lot of usability ad accessibility problems (e.g., when a pop-up is created, and a user zooms in because text is too small, but there are now no controls to scroll - or everything gets mangled). Apps should be designed to be adaptive to any layout, not expect a fixed size.

**Comment by kenchris** [comment]
I would actually say that this has nothing to do with packaged apps. It could very well be for any app.

On the other hand, many desktop apps (like Windows apps) have a minimum size. You could say that web apps should work at any size, but some apps are just not useful when smaller than a certain size (think about implementing Autocad or similar)

**Comment by kenchris** [comment]
I would be OK with adding

"min-width" and "min-height"

**Comment by marcoscaceres** [comment]
@kenchris, but you can prevent the content from being too small using "min-width" and "min-height" in CSS already. That prevents the content from being squished to an unusable level, while allowing the window to be resized to whatever size the user wants... ok, yes, that is a sad solution :)  

so yeah, "min-width" and "min-height" wouldn't be terrible, but to what display mode would they apply?

**Comment by skddc** [comment]
>  "standalone" or "minimal-ui" modes

... makes sense I think. And it would only apply to installed apps on desktop OSs I guess.

**Comment by marcoscaceres** [comment]
I can't disagree. Next question is, who is planning to support these kinds of floating window apps? We have no plans ATM to support this in Gecko.

**Comment by marcoscaceres** [comment]
Looking at browsers, the `min-width` is 350px on Firefox, and 400px for Chrome, and 505px for Safari. Why not just let the UA decide what the min-width is?

**Comment by kenchris** [comment]
This would apply to ChromeOS apps and it will also apply to Crosswalk on desktop linux systems.

Because the apps know better? :-) We got this requirement from the Deepin linux desktop which uses lots of web apps.

**Comment by marcoscaceres** [comment]
So Deepin linux is going to implement manifest or use cross-walk?

**Comment by kenchris** [comment]
We are looking at the latter

**Comment by marcoscaceres** [comment]
Ok, sorry for all the questions. I want to make sure that if we are going to add something it will be used for sure.

**Comment by kenchris** [comment]
the question that I have is what this should apply to, inner or outer bounds?

Chrome Apps makes this distinction: https://developer.chrome.com/apps/app_window#type-BoundsSpecification

**Comment by skddc** [comment]
> I can't disagree. Next question is, who is planning to support these kinds of floating window apps? We have no plans ATM to support this in Gecko.

So Open Web Apps won't be replaced by this spec at some point? I'm using OWAs on my Linux and OS X desktops.

**Comment by marcoscaceres** [comment]
> So Open Web Apps won't be replaced by this spec at some point?

Maybe. That's and ongoing discussion.

**Comment by skddc** [comment]
In any case, desktop OWAs and FF Marketplace for Desktop were just officially announced as "public beta" with FF 35, so the use case is obviously there.

**Comment by marcoscaceres** [comment]
@kenchris "The minimum width of the content or window" sounds most interoperable. The OSs  are allowed to put whatever chrome around the app as required by their conventions.

**Comment by marcoscaceres** [comment]
> In any case, desktop OWAs and FF Marketplace for Desktop were just officially announced as "public beta" with FF 35, so the use case is obviously there.

Agree about the use case. However, marketplace is currently not aiming to be a consumer of this spec AFAIK. I'm also not sure how they handle window sizes? Any idea? I can't see anything in their [manifest format](https://developer.mozilla.org/en-US/Apps/Build/Manifest).

**Comment by skddc** [comment]
> I can't see anything in their manifest format.

Yes, afaik it's all done automatically with no config option. No idea how it's handled exactly, but it seems like an arbitrary minimum size to me.

**Comment by marcoscaceres** [comment]
I wonder if this is too limited. Do you really want to here what `<meta viewport>` does?

**Comment by marcoscaceres** [comment]
Here is some initial text for review: 
https://github.com/w3c/manifest/commit/64afa4827bd556ed8485f81d63505b1fc56844a7

**Comment by yejingfu** [comment]
Thank you @marcoscaceres and @kenchris . Currently I am implementing it in Crosswalk for desktop Linux. Just for clarification, the `width` and `height` just define the original window size. Does it make sense to add the additional `min-width` and `min-height` to set the minimum window size if we want to prevent window being smaller than certain value?

**Comment by marcoscaceres** [comment]
Personally, I would prefer the width/height describe the minimum, and then let the platform pick the default size (if normally larger). Is that workable, or is it too inflexible?

**Comment by yejingfu** [comment]
It's workable. I am just curious if `width/height` describe the minimum size, user could not resize (by dragging window corner for example) window to be smaller. Per my understanding, the `width/height` define the preferred size which may display the window in comfortable view port. Then it may be better to describe the minimum size with the additional `min-width/min-height`.

**Comment by marcoscaceres** [comment]
@yejingfu @kenchris, sorry: do you think width/height should be the size at which the window opens? The min/width and height still need to be restricted by the UA, given platform conventions (the system/UA can't guaranteed the minimum or even the requested size). 

If the width and height are smaller/larger than allowed by the UA/System, the UA makes width and height the min/max allowed. Fitting the context to size doesn't make much sense anyway, as the content can be zoomed in (with ctrl-+ or having a larger base font-size). Hence, control of the content width/height internally to the window should be controlled with CSS (max/max-width/height and overflow).

**Comment by alxlu** [comment]
Allowing developers to control the size at which the window opens would enable developers to provide a better experience for certain types of apps. If someone is writing an app that is taller than it is wide (e.g. a simple calculator), it may be good to have some control of how the app is initially shown. That being said, I'm not sure how common those scenarios are.

**Comment by kenchris** [comment]
Well on ChromeOS some apps use it. For instance you probably never want a calculator to start up in fullscreen etc as you expect to have to open at the same time as other windows, as it is a complimentary tool

**Comment by kenchris** [comment]
I personally think that there are multiple use cases.

* Some want to enforce a minimum width. Depending on your app, there is only so much you can do to make it still useful at smaller sizes... like a calculator with just room for one button is useless.
* Minimum width doesn't necessarily mean that that is the preferred app size, just that the app still works at that size, so I guess that - especially for first launch - people want to be able to give a preferred width.

width: { min: 100, preferred: 400, max: undefined } ?

**Comment by kenchris** [comment]
ChromeApps basically have

"bounds": { "width": ..., "height":,..."min-width", max-width, ... and even the top and left coordinates

**Comment by marcoscaceres** [comment]
Although the use cases and requirements for this feature are extremely clear, I'm still really worried about adding this. As it stands, we only have one potential consumer of this feature. In Gecko, we are not planning to support anything like this right now  - and it's not clear to me if Chrome or any other UA is going to support this (even if Chrome OS does). 

Can I suggest initially doing a `chromium_` prefixed version of this to work out all the kinks and to define the model? If we find additional interest from other implementers, we can then drop the prefix and take the feature likely wholesale.

**Comment by yejingfu** [comment]
How about adding the bounds spec like below:

    "chromium_bounds": {
        "width": 500,
        "height": 600,
        "min-width": 250,
        "min-height": 300,
        "max-width": 800,
        "max-height": 1000
    }

The `min-width/min-height` and `max-width/max-height` can be optional.

**Comment by marcoscaceres** [comment]
that seems fine - just remember that you will need to treat all of them as optional if this lands in this spec.

**Comment by yejingfu** [comment]
Yes, all fields should be treated as optional. Thank you for pointing out.

**Comment by marcoscaceres** [comment]
Closing feature request for now. Will reopen if other implementers request this feature.
