### ISSUE TITLE
"manifest" link relation type should be registered per RFC 5988

### ISSUE THREAD

**Issue by dret** [w3c/manifest#312]
It would be great to see the new link relation type be registered with IANA. If that helps, I'd be more than happy to add that to the "IANA Considerations" section.

**Comment by marcoscaceres** [comment]
On Friday, February 13, 2015, Erik Wilde <notifications@github.com> wrote:

> It would be great to see the new link relation type be registered with
> IANA. If that helps, I'd be more than happy to add that to the "IANA
> Considerations" section.
>

That would be great! Thanks for your help.

**Comment by dret** [comment]
ok, will do sometime next week, i guess. it'll simply take the standard registration template from RFC 5988 and add a section to the "IANA Considerations". the result will look similar to http://tools.ietf.org/html/rfc6892#section-4

**Comment by marcoscaceres** [comment]
Thanks. If you find you are too busy, I'm happy to give it a go and can ping you to check over the PR.

**Comment by marcoscaceres** [comment]
Sent request to IANA too.

**Comment by marcoscaceres** [comment]
(well, to ietf)
