### ISSUE TITLE
JSON-LD view

### ISSUE THREAD

**Issue by dret** [w3c/manifest#313]
just out of curiosity: it seems that the processing model for the manifest data at least sometimes requires a sequence of items to be represented (as opposed to a set). at least this is how i read how icons must be processed (http://www.w3.org/TR/appmanifest/#icons-member). i am wondering if this can even work for the JSON-LD "view" that's proposed later on. RDF is notoriously bad with sequences, and afaict the example shown would lose the sequence that is necessary to correctly implement the algorithm defined in the spec. am i reading it wrong or missing something?

**Comment by marcoscaceres** [comment]
I'm thinking of dropping the JSON-LD stuff, tbh. It's something that was added for the linked data community, but I haven't heard anyone outside the W3C asking for it. Any issues related to the JSON-LD can then be handled in a separate spec by the linked data folks.

**Comment by dret** [comment]
exactly. layering is good. i wish everybody would see it this way.
