### ISSUE TITLE
Move to using Echidna

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#315]
The w3c is making is possible to automatically have drafts pushed to TR, which partially overcomes the stale spec problem. 

https://github.com/w3c/echidna

**Comment by marcoscaceres** [comment]
I need to get the id numbers from each of the editors. Can each of you go to: https://www.w3.org/users/myprofile and get the ID number in the URL? Please see: https://github.com/w3c/echidna/issues/85#issuecomment-74595519

**Comment by marcoscaceres** [comment]
//cc @anssiko @kenchris  @mounirlamouri

**Comment by kenchris** [comment]
https://www.w3.org/users/57705

**Comment by anssiko** [comment]
@marcoscaceres My ID is 41974.

**Comment by mounirlamouri** [comment]
45389

**Comment by marcoscaceres** [comment]
Feature branch: https://github.com/w3c/manifest/tree/echidna

**Comment by kenchris** [comment]
So this is the branch we should be using now? or is this just an experiemnt? Should this issue be closed?

**Comment by marcoscaceres** [comment]
No, this is a feature branch but I could not get it to work yet. I've asked
the w3c for help. Docs are effing terrible for echidna still.
