### ISSUE TITLE
Desktop web apps should be able to declare their viewport size

### ISSUE THREAD

**Issue by digitarald** [w3c/manifest#317]
**Real life use cases:**
- Cut The Rope is designed for a 3 to 4 viewport ratio and looks best at 640 by 480. If opened in a different ratio, the game will be letterboxed which should be avoided.
- Wunderlist is optimized for using minimal screen estate and looks blown up when resized too far. To look best on first launch, a developer should be able to specify recommended window size.

Display modes that mimic the windowing behavior of native apps, `standalone` `minimal-ui`, should optionally allow declaration of a `viewport` property to set initial app window viewport size.

**Comment by kenchris** [comment]
This is related to #310

**Comment by marcoscaceres** [comment]
Duplicate to #310.
