### ISSUE TITLE
Clarify "scope" in step #3 of Section 3

### ISSUE THREAD

**Issue by AFBarstow** [w3c/manifest#320]
Step #3 in Section 3 says

[[
3. If target is same origin as scope and target's pathname starts with scope's pathname, return true.
]]

The term "scope" is used twice in that sentence and since it is not explicitly qualified, its meaning is unclear to me. Since "scope" is italicized (via <var>), it seems like it could be a variable (but there is no explicit "scope" variable) or perhaps it is "scopeURL", or perhaps "navigation scope" or maybe something else?

(My advanced apologies if I'm simply mis-reading this sentence.)

**Comment by marcoscaceres** [comment]
Good catch. Should indeed be "scopeURL".
