### ISSUE TITLE
Add a lang member

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#322]
[Elsewhere](https://lists.w3.org/Archives/Public/public-i18n-core/2015JanMar/0072.html), Addison Phillips pointed out:

> Language: you still need to provide language information about the manifest's natural 
> language content items. Among other things, correct font selection rides on providing 
> language metadata to the text drawing layer. Inferring the language of the text by sniffing 
> the bits is inaccurate or impractical. The best practice is to provide this as additional 
> data.

I'm inclined to add a `lang` member.

**Comment by mounirlamouri** [comment]
I would suggest to not add 'lang' without a full i18n story. If we were to re-use Mozilla's Manifest way to handle i18n, we might want to have default_locale instead of lang.

**Comment by marcoscaceres** [comment]
@mounirlamouri
> I would suggest to not add 'lang' without a full i18n story.

Please see Addison's comments - this is not related to localization - this is about primary language in which the content of the manifest is written. 

And we do have a full i18n story, it's: "adapt your manifest based on user input to your web app... like you do with every other document on your site":).

**Comment by marcoscaceres** [comment]
@mounirlamouri still want your ok on this: https://github.com/w3c/manifest/commit/cbd8343df1ea4bb1c29abc6a1804954159e0737a

**Comment by benfrancis** [comment]
Note that:
* Having multiple manifest files per app prevents the manifest URL being used as an app identifier.
* Having a dynamically generated manifest prevents the manifest being signed for the purpose of granting permissions.

I know that neither of these requirements are things that everyone agrees on, but I wanted to call out that they may make certain things impossible in the future.

And FWIW I don't actually think having multiple locales in a single manifest is particularly messy.

**Comment by marcoscaceres** [comment]
On March 7, 2015 at 5:21:38 AM, Ben Francis (notifications@github.com) wrote: 
> And FWIW I don't actually think having multiple locales in a single manifest is particularly  
> messy.

There seems to be some confusion about the use case: having `lang` helps with font selection for the purposes of display (please, all, read Addison's email carefully!), which is different to the localization that is used by Mozilla's manifest format or the alternatives proposed in other bugs. 

That is to say, `default_locale`, if it was ever to be added, works independently of `lang`. It's like `<html lang=>` or `<foo xml:lang>`.

**Comment by mounirlamouri** [comment]
But if we end up having some ```locales``` array like the Firefox Manifest, ```lang``` might be a bit pointless? Or would you re-use ```lang``` in there and it would apply for the scope? In which case, the way we would handle override would be a tad different from what Mozilla currently do. If you have no problem with that, I'm fine with adding ```lang```. (Note, I think it would kill ```default_locale``` too.)

**Comment by marcoscaceres** [comment]
> But if we end up having some locales array like the Firefox Manifest, lang might be a bit pointless?

No, because `lang` is still the primary language (i.e., it's the same as `default_locale`). 

> Or would you re-use lang in there and it would apply for the scope? In which case, the way we would handle override would be a tad different from what Mozilla currently do.

That's fine. Mozilla's model leads to very unmanageable nested structures.  

> If you have no problem with that, I'm fine with adding lang. (Note, I think it would kill default_locale too.)

I'm fine. I'll take this as agreement. :+1:
