### ISSUE TITLE
Add note about i18n

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#323]
The note should include: 

 * [x] The spec should details how we expect developers to localize content. Like by: `<link rel=manifest href='manifest?lang=en'>`
 * [x]  An example showing the use of a language other than English. 
 * [x] Add discussion of obtaining a correctly localized reference, particularly for use in cases where the source page itself has used language negotiation.

**Comment by mounirlamouri** [comment]
With the current Manifest 18n support, it seems that HTTP headers could do?

**Comment by marcoscaceres** [comment]
There is a ton of things that could be used, from geo-ip lookup, to HTTP headers (accept-language or whatever), a URL string, and just simply allowing the user to choose their own language (and update the link element's URL, as above)... basically, whatever sites do today. It all works, and it's all good :dancer:

**Comment by kenchris** [comment]
can this be closed?

**Comment by marcoscaceres** [comment]
Not yet, no. I'll send a PR soon.

**Comment by marcoscaceres** [comment]
> An example showing the use of a language other than English.

I used French, because I like to include @mounirlamouri.

**Comment by himorin** [comment]
Note: W3C i18n WG closed our tracker with actions taken satisfactory. (please not remove i18n-needs-resolution label which is used by our bot and tracking system)
