### ISSUE TITLE
Convert "Icon object" into a generic "image object"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#327]
The icon object can really just serve as a generic image object. This could then be reused in the future to, for instance, support splash screens.

**Comment by kenchris** [comment]
ok, any idea?

**Comment by marcoscaceres** [comment]
It's only an editorial change in the spec right now. The `icons` member just takes a list of "image objects" instead of "icon objects".

**Comment by marcoscaceres** [comment]
Splash screens can be done by simply changing the concept of "icon object" to "image object":
https://github.com/w3c/manifest/pull/325 

Roughly:
{
  "icons":  [{"src": "..."}, {"src": "..."} ],
  "splashscreens": [{"src": "..."}, {"src": "..."} ],
  "theme_color": "green"
}

The theme_color can serve as the background for a splash screen. The splash image can just be centered in the middle of the screen. That should cater for most use cases. Fancier cases can be handled on document load (e.g., show a loading indicator as splash, then when first page loads, do some fancy animation).

**Comment by kenchris** [comment]
Well, then you assume that people will supply splash screens that covers the whole viewport and in multiple sizes (there are so many different screen sizes). Current splash system usually adds the image in the middle or makes used of 9-piece images which have stretchable areas.

**Comment by marcoscaceres** [comment]
What I was assuming was they would provide a range of them, but not cover the whole screen (they would be centered, as you said). What is not covered by the image would be filled by the theme_color (in the background).

**Comment by kenchris** [comment]
That could be considered a "splash" but that will not allow creating a fake outline of the app UI, which people can do and are encouraged to do on iOS

**Comment by alxlu** [comment]
>That could be considered a "splash" but that will not allow creating a fake outline of the app UI, which people can do and are encouraged to do on iOS

Do you know of any iOS apps that do this that I can download and try out? I'm interested in seeing how that looks/feels.

That being said, isn't this a much bigger challenge for hosted webapps because of the much larger variations in screen sizes (and other factors)?

**Comment by marcoscaceres** [comment]
> Do you know of any iOS apps that do this that I can download and try out? I'm interested in seeing how that looks/feels.

Closest I found is iCurrency - but I don't actually know if it's using a splash screen. It does show the app layout first, then shows numbers. I don't think it's a great example. The rest of the apps on my phone either don't show a splash or show the centered splash screen.

**Comment by marcoscaceres** [comment]
On March 6, 2015 at 9:40:38 PM, Kenneth Rohde Christiansen (notifications@github.com) wrote:
> That could be considered a "splash" but that will not allow creating a fake outline of  
> the app UI, which people can do and are encouraged to do on iOS

(before you reply: we should probably move this discussion to the splash screen bug #9!) 

OK, but we can't follow iOS here: unlike with iOS, there are a billion different screen sizes/dimensions/density combinations that an app built for the web is supposed to adapt to (and that's just Android! add FxOS, Tizen, or whatever, and the number just keeps on climbing). 

The tradeoff that cross-platform app makes is giving up the ability to target an OS specifically (though you could, of course, do user agent sniffing if you wanted to be pedantic ... alternatively, client-hints might actually help here too - so a developer can send down a auto-generated splash screen that exactly matches the user's device-width/height).

**Comment by kenchris** [comment]
True, and that is why we support using 9-pieces images - or to split your image up into 9 pieces. Cordova supports the exact same. With a bit of work this can emulate most UIs.

Basically all build in apps on the iPhone use a "launch screen", which then fades into the real ui... there is no text on any launch screen done by Apple (and it is not recommended in their guides)

**Comment by marcoscaceres** [comment]
@kenchris I'm trying to understand how Cordova does the 9-piece thing you mentioned, but I don't see it in their docs?: 

* https://cordova.apache.org/docs/en/4.0.0/config_ref_images.md.html
* https://github.com/apache/cordova-plugin-splashscreen/blob/master/doc/index.md

Am I looking at the wrong docs?
