### ISSUE TITLE
add a license field

### ISSUE THREAD

**Issue by bufferoverflow** [w3c/manifest#328]
In many cases a web application and web apps are available under a specific open source license.
It would be beneficial and helpful for collaboration on web applications if a license filed would exist within the manifest.

A very good definition of such a field using SPDX license identifiers can be found here:
https://docs.npmjs.com/files/package.json#license

**Comment by marcoscaceres** [comment]
@bufferoverflow, although that is certainly valuable information, metadata that is not used consumed and used by the user agent is outside the scope of this spec. 

A more appropriate for the display such information might be a a HTML file (or, indeed, in a package.json file).

**Comment by marcoscaceres** [comment]
Closing this for now.

**Comment by bufferoverflow** [comment]
package.json is part of the source code and the web application deployment does usually not contain the source code. What is the recommended way to provide license information in a standard way on a open web app, something like this?
```<link rel="license" href="LICENSE">```

**Comment by marcoscaceres** [comment]
@bufferoverflow, correct. That's [what HTML states](https://html.spec.whatwg.org/#link-type-license): 

"The license keyword indicates that the referenced document provides the copyright license terms under which the main content of the current document is provided."
