### ISSUE TITLE
i18n: No direction metadata for 'name'; [I18N-ISSUE-416]

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest#334]
http://www.w3.org/International/track/issues/416

Raised by: Addison Phillips
http://www.w3.org/TR/2015/WD-appmanifest-20150212/#name-member

The 'name' manifest member does not provide a means of indicating the base direction of the name string. This is equivalent to extracting the 'dir' attribute appropriate for the `<title>` element's scope and may be necessary for correct rendering of bidirectional content.

For example, the author might need to set the base direction explicitly, since the Unicode paragraph detection algorithm can be fooled by a paragraph that starts with a strong LTR character, but is actually a RTL paragraph (or vice versa), eg. "نشاط التدويل is how you say 'i18n Activity' in Arabic."

It would be helpful to the author to be able to set the default base direction for a whole manifest file to rtl.

**Comment by pornel** [comment]
The existing meta `application-name` supports `dir` ([related](https://github.com/w3c/manifest/issues/335#issuecomment-89964179))

**Comment by marcoscaceres** [comment]
Gecko implementation:
https://bugzilla.mozilla.org/show_bug.cgi?id=1258899

@kenchris or @mounirlamouri , is there an implementation on the Chrome side?

**Comment by mounirlamouri** [comment]
No one is assigned to work on this.
