### ISSUE TITLE
typo found

### ISSUE THREAD

**Issue by GrosSacASac** [w3c/manifest#342]
Ctrl+F this

On iOS, when web pages doesn't specify a custom touch icon, the OS takes a screenshot of the webstie and creates an icon from it. This is shown below. 

here
http://w3c-webmob.github.io/installable-webapps/

**Comment by jmajnert** [comment]
Found it in http://w3c-webmob.github.io/installable-webapps/#ios---touch-icons

**Comment by jmajnert** [comment]
This is a different github project: https://github.com/w3c-webmob/installable-webapps

**Comment by jmajnert** [comment]
I moved the issue to the proper project. This issue can be safely closed
