### ISSUE TITLE
difference between lang and default_locale

### ISSUE THREAD

**Issue by GrosSacASac** [w3c/manifest#345]
Can you explain the difference ?

**Comment by marcoscaceres** [comment]
Sure, `default_locale` would be the locale that would be chosen if none of the locales available in a file match the user's locales*. `lang` is the primary language of the document (equiv. to `<html lang>`).

* there is no `default_locale` in the spec because we don't support multiple locales.

**Comment by marcoscaceres** [comment]
closing issue. Please feel free to ask any follow up question tho.

**Comment by marcoscaceres** [comment]
To see more examples of default locale used in a different spec: http://www.w3.org/TR/widgets/#the-defaultlocale-attribute
