### ISSUE TITLE
The use of the `.manifest` file extension may be problematic / confusing ?

### ISSUE THREAD

**Issue by alrra** [w3c/manifest#346]
From: http://w3c.github.io/manifest/#h-media-type-registration

```
File extension(s):
    .json, .manifest
```

`.manifest` was the recommended file extension for the [Application Cache manifest file](https://html.spec.whatwg.org/multipage/browsers.html#manifests), and then, it was changed to  `.appcache` in order to [_"avoid clashing with Microsoft's unregistered `application/manifest` type"_](https://html5.org/r/5812). 

So, taking into consideration also the [legacy](https://www.google.com/search?hl=en&q=%22addtype+text%2Fcache-manifest+manifest%22) aspects, recommending `.manifest` as the file extension creates even more "clashing", and this can complicate things when it comes to server configs (e.g.: especially as in some of the cases, things like the media type [matter](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache#Referencing_a_cache_manifest_file)).

__Note:__ As opposed to `.manifest`, in the case of `.json`, IMHO, things are better. Since for the manifest files for web apps the media type doesn't seem to matter (for now at least), and they are just JSON files, the configurations that most servers out there have should already work great for them (e.g.: serve them compressed, with the media type [`charset` parameter](http://www.w3.org/International/O-HTTP-charset#charset) set to `utf-8`, etc.).

**Comment by marcoscaceres** [comment]
oh, d'oh. Good point.

**Comment by marcoscaceres** [comment]
Should we just call it `.webmanifest`? I think anything we come up with is going to be terrible and 99% of people will just use `.json` (and not send the recommended mime type).

**Comment by alrra** [comment]
> Should we just call it .webmanifest? I think anything we come up with is going to be terrible 

@marcoscaceres Having a unique file extension would make things very easy in terms of server configs, so :+1: for that.

>  (and not send the recommended mime type). 

It's not only about _"sending the recommended mime type"_. Some servers (e.g.: Apache) rely on the media type for different settings (e.g: [ExpiresByType](http://httpd.apache.org/docs/current/mod/mod_expires.html#expiresbytype)), and not having a unique file extension sometimes makes the mapping to a media type [not so straightforward](https://github.com/h5bp/server-configs-apache/blob/9336f201aa1664ac0c9b76442ba354c3a38bcbf6/dist/.htaccess#L186-L217).

>   and 99% of people will just use .json

The HTML5 Boilerplate project is [looking into adding a starter web application manifest file](https://github.com/h5bp/html5-boilerplate/pull/1629), and some of the H5BP server configs had some default configs for this [for quite some time](https://github.com/h5bp/server-configs-apache/issues/29), so if something changes regarding the file extension, we'll try to help even more (e.g.: recently we removed the `.manifest` → `text/cache-manifest` mapping from all our server configs: [1](https://github.com/h5bp/server-configs-apache/commit/c805353c4142c792267945687309259fc15b2106), [2](https://github.com/h5bp/server-configs-nginx/commit/d7e0e1bf46c89e387b201d849711ff8564e9652e), [3](https://github.com/h5bp/server-configs-gae/commit/584759ec0e1fe166cc96b36e6ff00c91769712e0), [4](https://github.com/h5bp/server-configs-lighttpd/commit/27ff0ab0b82aeb63d954294944af956c9ad5d4a6)).

**Comment by marcoscaceres** [comment]
@alrra all excellent points. Let me fix this now.
