### ISSUE TITLE
Triage privacy issues

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#348]
Lots of feedback here... 
https://lists.w3.org/Archives/Public/public-privacy/2015JanMar/0118.html

cc @npdoty, who we need to work with to address the above...

**Comment by npdoty** [comment]
The more formal write-up that I sent to webapps may be better organized and easier to follow for identifying issues:
https://lists.w3.org/Archives/Public/public-privacy/2015JanMar/0117.html

**Comment by marcoscaceres** [comment]
That's great! thank you. That makes things much easier.

**Comment by mounirlamouri** [comment]
_persistent state_: #399
_cross origin persistent state_: #400
_control over native ui_: #401 #402

@npdoty, please, let me know if I missed something.

**Comment by marcoscaceres** [comment]
@mounirlamouri did the triage. We didn't hear back from @npdoty, so assuming it's all good.

**Comment by npdoty** [comment]
Sorry for not following up explicitly. Yes, this separation into GitHub issues seems to cover the privacy/security issues raised in our comments.
