### ISSUE TITLE
About Installations: API vs Signals — ¿case for Desktop-only API?

### ISSUE THREAD

**Issue by berbaquero** [w3c/manifest#359]
I understand there's a current consensus of removing the API for "installing" web-apps to avoid the imminent proliferation of "INSTALL ME" banners and similar things, so on Mobile the focus is now on signals or heuristic for the browser to decide when to offer the "Install" option.

However, could there still be a case for programmatic access, *at least on Desktop*?

Just as a very young example, Facebook released a Web-app for Messenger yesterday. Just a couple of hours later, there were already at least 2 open-source "native wrappers" for it. It makes sense for *some* **desktop** web-apps to live a standalone apps, messaging/chat apps (like FB Messenger, Slack, Telegram) just being some of them. And clearly there's an audience who appreciates having a standalone version of these web-apps on their desktops. For those, an "Install" button would be sweet, and it would eliminate the "need" of these wrappers, or apps like Fluid on Mac.

What do you think?

**Comment by n054** [comment]
I originally wished to make what I called "mega mini mobile desktop", added some html5 and build tools. The need to be able to switch back and forth on some queries and tests and just regular down time stuff like answering conversations or playing some entertainment gets lost in the directory part and the ping adjustments (which could be renamed " address", and "doorbell".) Someone somewhere said something about the doors are you he same basic framework, the trouble comes from acknowledgement of the doorkeeper and the doorbell ringer and whether the door is going to o be shut at the ping or opened. I've been told before that my browser is 'further advanced than the update version am I sure I wish to proceed.' Do any of these comments go inline with your query? no.na

**Comment by n054** [comment]
Change "you he" to "the" on previous comment.

**Comment by benfrancis** [comment]
> I understand there's a current consensus of removing the API for "installing" web-apps

It's not so much removing it, as not adding it to the W3C spec. Although it seems like Microsoft (and at least for now Mozilla) still use proprietary APIs to do this internally for app store type apps.

> clearly there's an audience who appreciates having a standalone version of these web-apps on their desktops. For those, an "Install" button would be sweet

I don't think there's anything special about desktop here, a web app can still be installed from the browser and desktop browsers could take the same approach of prompting the user based on certain heuristics to install the standalone app.

**Comment by berbaquero** [comment]
> desktop browsers could take the same approach of prompting the user based on certain heuristics.

Well, my argument for a "different" approach on desktop is based on my concerns for these heuristic themselves — and I guess that's better for another thread — but in short, I feel these heuristics, at least based on how Chrome just implemented them on Android, seem very limiting.

I think the "Standalone" experience is essential if we want to offer a complete "app experience" from The Web against native and closed-platform apps, and these heuristics are setting a high barrier on entry for devs who want to offer them.

> I don't think there's anything special about desktop here

Maybe I'm "splitting hairs" here, but what about more screen real estate? I feel one of the reasons "install me!" banners are definitely a bad idea on mobile, is because of the bad UX based on the space they'd take if an API is abused. That is not necessarily an issue on desktop, or at least not at the same level.

**Comment by marcoscaceres** [comment]
> I think the "Standalone" experience is essential if we want to offer a complete "app experience" from The Web against native and closed-platform apps, and these heuristics are setting a high barrier on entry for devs who want to offer them.

That's by design. Consider the same high barrier to create an iOS app or an Android app. There should be an expectation that web apps also be of high quality. 

> Maybe I'm "splitting hairs" here, but what about more screen real estate? I feel one of the reasons "install me!" banners are definitely a bad idea on mobile, is because of the bad UX based on the space they'd take if an API is abused. That is not necessarily an issue on desktop, or at least not at the same level.

That's misunderstanding the problem a bit. The banner problem is that, apart from screen real estate, you need to create a unique browser banner per browser (and even sometimes browser version, as happened with changes to iOS's UI). Yes, the install API would get rid of that problem, but would still bring a bunch of "install me" buttons everywhere.

We are wanting to experiment with the installability signals first (say, over the next year), and see if it works out ok. If it all fails spectacularly, we will of course introduce an install API.
