### ISSUE TITLE
image objects should have a background color

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#366]
Use case: non-square container for icons and for splash-screens.

**Comment by benfrancis** [comment]
Is this definitely distinct from theme-color? It seems like theme-color could be used for this use case. Are there examples of where that wouldn't work?

**Comment by marcoscaceres** [comment]
Well, for instance, you want your logo on a white background for the splash screen, but then you want the theme to be some other color when the start page loads. 

Real example: 
 * etsy and eventbrite both have orange backgrounds for splash, but then white theme color when the page loads.
