### ISSUE TITLE
A means to control how long a splash screen should remain on screen. 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#372]
An app might want to show its splash screen for a minimum amount of time.

**Comment by marcoscaceres** [comment]
@kenchris wrote: 
> I would love a DOM API for hiding it. We use that in Crosswalk.

It would be good to investigate when people are calling this API... there has also been talk of adding a "appready" user fireable event in the past, which could be used with something like this.  
```JSON
}
//keyword 
"splash_screens_bikeshedme": "appready",
// or time-based
"splash_screens_bikeshedme": "1000" 
}
 
```

**Comment by marcoscaceres** [comment]
Of course, there could just be an API too.

**Comment by kenchris** [comment]
right. Doesnt web components not already have such an event? or is it only Polymer?

I think the timeout is pretty bad. It might mean that people will always wait even if the app is ready and usable - which makes us look worse than native.

On the other hand if we force people to call an event, people will quickly find out to call it :-)

**Comment by marcoscaceres** [comment]
Well, at the moment, it's specified to hide it after DOMContentLoaded fires. So, question I have for crosswalk is if that's what most developers are using in your ecosystem? Is it possible for you to look at a sample?

**Comment by kenchris** [comment]
We actually support hiding when DOMContentLoaded but my own experience is that that is often a bit too early (especially when using frameworks like Polymer). 

I know that @darktears used it as well, maybe he can comment on his experience. Alexis?

**Comment by darktears** [comment]
I can second what Kenneth said. I tear down the Splash Screen manually when I know in my application code logic that I have stuff to show in terms of content and that the UI has loaded in some way.

**Comment by marcoscaceres** [comment]
@darktears, can you provide some more info? Do you call the tear down after onload or DOMContentLoaded?

**Comment by darktears** [comment]
That's what kenneth said, it was too early for onload or DOMContentLoaded. I felt it would be nice in my case if the UI showed up with partial data already.

**Comment by marcoscaceres** [comment]
Ok, so it seems like an API might be the way to go here.

**Comment by marcoscaceres** [comment]
Spoke to @kenchris about this. He proposes just `navigator.splashscreen.hide()` (similar to Cordova, but exclude the `show()` method, which doesn't have a strong use case?), which returns a promise. Resolves when splash screen is removed. Later, we can add a dictionary with some options for how to remove the splash screen (i.e., fade it out, etc.).

**Comment by allanjuma** [comment]
Yeah. dont think the navigator.splashscreen.show() has a strong use-case either. perhaps when unloading a page before the next page load?

**Comment by marcoscaceres** [comment]
On Saturday, May 9, 2015, allanjuma <notifications@github.com> wrote:

> Yeah. dont think the navigator.splashscreen.show() has a strong use-case
> either. perhaps when unloading a page before the next page load?
>

More interesting question: should this be exposed in a (SW) worker context?

**Comment by allanjuma** [comment]
interesting. Would like to see a use case for the (SW) worker and splash screen.. they don't sound like very good friends :)

**Comment by mounirlamouri** [comment]
I think we don't all have the same vision of what a splashscreen should be used for. IMO, the browser should show a splashscreen up to the point of the first paint so an API to control the splashscreen isn't really needed. After the first paint, the website is able to control what's being rendered.

**Comment by marcoscaceres** [comment]
> I think we don't all have the same vision of what a splashscreen should be used for. IMO, the browser should show a splashscreen up to the point of the first paint so an API to control the splashscreen isn't really needed. After the first paint, the website is able to control what's being rendered.

This seems initially like a good idea (it's actually what's in the spec right now). However, if you look at how splash screens are used, this doesn't really match the requirements developers have (e.g., https://github.com/w3c/manifest/issues/372#issuecomment-97087751). However, there might be room for a compromise position: some may opt for first-paint, while others might want more control. Having the API affords developers control over removing the splashscreen on first paint or when *the developer* deems the application is ready.

**Comment by darktears** [comment]
@mounirlamouri : First paint doesn't mean you can control what's being rendered. Take an example : Polymer. You may get the first paint event, then tear down the splashscreen however the UI may be in a broken state because the bindings are not yet evaluated. One could say that I should implement some complicated logic to make sure that I don't show partial state in my UI but then what's the point of the Polymer bindings {{ }} and the declarative syntax when suddendly I need to add a bunch of JS code to create the bindings afterwards. Again this is convenience.

**Comment by allanjuma** [comment]
@marcoscaceres is right, there should be room for a compromise position.

**Comment by FremyCompany** [comment]
I've built Windows apps in the past using HTML, and I like how it works there. The splashscreen is shown automatically while your app is loading, which usually takes less than a second. 

As soon as your app can paint, it does paint, but there's a built-in fullscreen Splashscreen template/control you can add to your page which has the exact same layout as the splash screen so, if you want, you can use it and hide it while you're actually ready.

In addition, you can display other stuff on top of it like a progress bar and the type of things you're actually waiting for (this is useful for games, for instance).

**Comment by marcoscaceres** [comment]
Maybe what we really need is a generic way for an app to tell the UA that it's "ready" (i.e., on it's own terms).

**Comment by allanjuma** [comment]
@marcoscaceres 'app telling the UI..' might be a better idea.. There may be certain instances where the start URL is different from the app URL? and in such a scenario, should the app request the UA to start the splash then stop when ready?

**Comment by marcoscaceres** [comment]
On June 25, 2015 at 12:32:26 AM, allanjuma (notifications@github.com) wrote:
> @marcoscaceres 'app telling the UI..' might be a better idea..

Sorry, I don't follow? Can you expand the above a bit with an example. 

> There may be certain instances
> where the start URL is different from the app URL? and in such a scenario, should the app
> request the UA to start the splash then stop when ready?

Depends if the application is "resuming", but I think this is unlikely. It seems more likely that if you are starting up the application, you always go to the start URL (and hence show the splash screen). If you are otherwise resuming, then you just return the the currently open web page.

**Comment by allanjuma** [comment]
@marcoscaceres for example, the very first time you visit a website/webservice homepage, you may not go directly to the app, however upon navigating from the homepage to the app, the splashscreen should be activated. (of course this only applies if you are visiting the webapp from the homepage). eg, the home page at https://bitsoko.co.ke should be able to call the splash screen when navigating to the web app at https://bitsoko.co.ke/app.. (on chrome mobile)

**Comment by alxlu** [comment]
If the start page isn't where the splash screen is activated, wouldn't it be better to just have the developer implement their own splash screen at that point?

**Comment by marcoscaceres** [comment]
Resolved to leave this to the user agent.
