### ISSUE TITLE
Should a manifest unambigiously and authoritively be the app's metadata?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#376]
Basically, if a manifest is present, should the page's metadata be ignored?

**Comment by jmajnert** [comment]
Question that I think didn't get enough attention: 1 manifest_url <-> one app ?

**Comment by marcoscaceres** [comment]
> Question that I think didn't get enough attention: 1 manifest_url <-> one app ?
Can you elaborate what you mean here?

**Comment by jmajnert** [comment]
Should the spec restrict or mandate how UAs handle:
* the case of multiple web apps using the same manifest_url?
* the case where a page in the `scope` of one manifest links to a different manifest_url?

@slightlyoff said something along the lines: "all pages linking to a single manifest_url (or being in `scope`) are to be treated as one web app". Does this hold when we don't have the same origin restriction on the manifest_url? And more importantly - do we need to include this in normative text in the spec?

**Comment by slightlyoff** [comment]
If we consider the tuple of `(manifest_url && sw_scope)` as the identifier, I'm not sure that it matters where the manifest lives. The SW scope is rooted at the origin (as is the SW script itself).

But it all comes back to my root question: what problems are we solving with same-origin manifests? Happy to support them if we can identify an issue that requires it.
