### ISSUE TITLE
.json in MIME registration is causing problems.

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#381]
See: 
https://github.com/jshttp/mime-db/commit/078ed4e8e6695ce934e766069f35f97cf8dedf99

Should probably only register `.webmanifest` as the "standard" file extension.

**Comment by alrra** [comment]
> Should probably only register .webmanifest as the "standard" file extension. 

Having just a single unique file extension [makes things simple](https://github.com/w3c/manifest/issues/346), so big :+1: from me!
