### ISSUE TITLE
Add background color for splash screen. 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#390]
Conditional on: https://github.com/w3c/manifest/pull/387

If we remove image object's `background_color`, we need a way of coloring the  backgrounds of splash screens.

**Comment by mounirlamouri** [comment]
I think I would prefer if the website could tell us the background colour of its content in the Manifest so we can construct a splashscreen that it smooth. The difference is mostly semantic though.

**Comment by marcoscaceres** [comment]
@mounirlamouri, you still need the background color for the splash screen image, no? Working assumption is that there will be a transparent png being painted on some given color.

**Comment by marcoscaceres** [comment]
This is handled by https://w3c.github.io/manifest/#background_color-member
