### ISSUE TITLE
Additional context for the Abstract

### ISSUE THREAD

**Issue by AFBarstow** [w3c/manifest#392]
In the following discussion thread, Ben Francis makes some good points to consider including to the abstract, especially the following discoverability/crawler use case in posting 17 (although the later is mentioned in section 12):

[[
<https://groups.google.com/forum/#!topic/mozilla.dev.platform/RAHBNdesiXs> 

W3C manifests allow web apps to be crawled by search engines and discovered 
by users through their user agent without needing them to be submitted to a 
central app store by the developer. They provide the metadata needed to 
describe a web app, and provide a built-in discovery mechanism. 
]]

**Comment by marcoscaceres** [comment]
I do really like that text, but I don't want to make unsubstantiated claims that search engines are actually using web manifests. Apart from that bit, it's mostly ok - tho I need to check if it's much different from what is already there.

**Comment by marcoscaceres** [comment]
As I don't have any indication that search engines are doing this, I've decided to close this.
