### ISSUE TITLE
Add background_color to represent the content's background color

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/manifest#394]
I would like the Manifest to have a ```background_color``` field so a website could specify its background colour. The expected value is similar to ```theme_color```.

The use case for this is to be able to create a view for a web app with the right color before the app is loaded. For example, on a mobile device, if you add to your homescreen a website, it might take some time before it renders, in which case, a plain white screen wouldn't be ideal. This is different from a splashscreen because if a website is working offline, there might still be a delay between the user clicking and the website being rendered because of starting new processes and loading the data from the disk. In such situation, a splashscreen would be too heavy but showing the backrgound color early would be a smooth transition.

**Comment by benfrancis** [comment]
Just to note that in Firefox OS we're using theme_color as a background colour in several places. The WHATWG description of theme-color mentions using it as a background colour as an example https://github.com/whatwg/meta-theme-color

As discussed before we need to think about whether theme_color is really different than background_color, and if so that needs to be specified more clearly.

**Comment by marcoscaceres** [comment]
for me, theme_color was always about the the surrounding chrome and OS integration (e.g., the way it works on Android). `background_color` as described by Mounir makes sense, as color to show or transition from nothing or from a splash screen.

**Comment by kenchris** [comment]
I think it is fine adding it, but we should use it for splash screen background as well then, as splash screen might in some cases fade into the app just showing background color

**Comment by marcoscaceres** [comment]
I don't agree with using it for the splash background. Background colors for apps are usually different from the application background. I've tested quite a few apps on iOS. I would encourage you to take a look on Android.

**Comment by marcoscaceres** [comment]
(fixed comment above... need kwaffee)

**Comment by kenchris** [comment]
So if my app has blue background, but I use a darker blue for theme color, then my splash screen would get darker, or I would have to use the same color for background and theme color.

I don't really know what is preferred here.

**Comment by marcoscaceres** [comment]
To me, it's pretty clear. Look at Eventbrite - splash (orange):
![2015-08-12 11 46 19](https://cloud.githubusercontent.com/assets/870154/9228818/2c173608-40e8-11e5-97c5-a8060d1f3b13.png)

App bg color (white):
![2015-08-12 11 46 25](https://cloud.githubusercontent.com/assets/870154/9228831/408cd548-40e8-11e5-9324-1324264d9f1d.png)

**Comment by kenchris** [comment]
OK convinced :-) Will you add this then?

**Comment by marcoscaceres** [comment]
Yep, can add it.
