### ISSUE TITLE
Add support for disabling pull-to-refresh

### ISSUE THREAD

**Issue by jdduke** [w3c/manifest#398]
Android has a default overscroll action of refreshing the page. Many appy sites either provide their own pull-to-refresh implementation, or want to explicitly disable it. While developers can use programmatic and declarative means to disable the effect, it's not always convenient (see http://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature). Having a manifest key for disabling the feature (or perhaps other content targeting gestures like gesture nav on desktop) would be nice.

@slightlyoff what do you think?

**Comment by kenchris** [comment]
Maybe these things should just be disabled by default when in standalone mode?

**Comment by mounirlamouri** [comment]
@jdduke most implementations of the Manifest only use it when the web app is "installed". Would that match your requirements?

**Comment by benfrancis** [comment]
This seems very specific to a particular UI design in the user agent, that property would not be meaningful for all implementations.

**Comment by marcoscaceres** [comment]
Agree. This is very UA specific. If this was ever to be a thing, it would be to prevent unloading of a page by preventing a default action (e.g., `.onbeforerefresh` event).

**Comment by jdduke** [comment]
OK, what if it were generalized to be something like "overscroll-action: none"? Disallowing other potentially disruptive behaviors like gesture swipe navigation?

@mounirlamouri we'd also like to use the attribute as a hint in the non-installed case.

**Comment by alxlu** [comment]
> OK, what if it were generalized to be something like "overscroll-action: none"? Disallowing other potentially disruptive behaviors like gesture swipe navigation?

Something like `overscroll-action:none` could be useful. Some mobile browsers have a 'bounce' effect, and it would be nice to have the option of disabling it when running as an app.

**Comment by marcoscaceres** [comment]
@alxlu, absolutely - something like that would really help (or even the opposite: to enable the bounce on elements). @jdduke, this might be good to raise with the WICG on their [discourse instance](http://discourse.wicg.io/). It's outside the scope of this spec, unfortunately :(

**Comment by mounirlamouri** [comment]
CSS sounds like a natural way to go here.

**Comment by majido** [comment]
I am [proposing](https://discourse.wicg.io/t/proposal-api-to-control-user-gesture-navigation/1536) an CSS based API for this on WICG. I have also listed a few alternative and appreciate any feedback you may have.

@alxlu: This is essentially what you proposed [earlier](https://github.com/w3c/manifest/issues/398#issuecomment-133478796) with some more details around it. It will be great if you or someone from Edge team could collaborate on this.
