### ISSUE TITLE
Privacy Review: how to handle navigation to a fullscreen'd application?

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/manifest#402]
It is actually more of a security issue than a privacy issue. If a user has an application installed and the UA wants them to use it instead of the regular browser experience when clicking on a link, it might be very easy for that application to spoof the user and make them believe they are on another website.

The specification should at least mention that issue and provide some guidance. Maybe show the origin in that case? Always allow the user to find the URL bar?

**Comment by marcoscaceres** [comment]
@mounirlamouri, how are you handling this in Chrome?

**Comment by mounirlamouri** [comment]
At the moment, we do not open homescreen'd app unless the user clicks on the icon. When the user adds the website to their homescreen, we ask them to confirm while showing the icon and the name so we assume the user knows what they are doing.

Though, we have plans to start opening homescreen'd app from other entry points and I'm not sure if we have any plan around this.

/CC @owencm

**Comment by marcoscaceres** [comment]
Talking to @pauljt, it seems all we can really add here are recommendations: 

- user should able to access the URL somehow (e.g., it may be shown in the task manager).
- the OS/UA should make it clear that the user is leaving the standard browsing context. For example, in iOS, there is a pretty significant transition that signal that the user is leaving a browsing context and entering an application context.

**Comment by jakearchibald** [comment]
Being able to access the URL is nice for sharing too. Showing the icon will also help. When the fullscreen experience launches I can see the icon for not-a-banking-website, so hopefully I'll know something is up if something pretending to be a banking website appears.

**Comment by boyofgreen** [comment]
I would agree with @marcoscaceres.  It sounds like a UA implementation decision to me and should actually be a spec point
