### ISSUE TITLE
Maintain list of sites that have a manifest

### ISSUE THREAD

**Issue by alxlu** [w3c/manifest#404]
Is there a list of sites that have a linked JSON manifest? It would be nice to get an idea of how this is being used in the wild&mdash;if at all (at least by early adopters). So far I've only been able to find about six sites with a linked JSON manifest.

**Comment by marcoscaceres** [comment]
@alxlu not that I know of. I would also love to get such a list also.

**Comment by wizzwizz4** [comment]
Issue 404! :laughing:
Seriously though, it would be a simple matter to use a web spider over an Internet Directory and parse the XML of each page, make an array of link tags and check their attributes to determine whether they reference a manifest, then add them to a list. You'd need a lot of bandwidth though.

**Comment by kenchris** [comment]
@paulkinlan maybe you can share what you have?

**Comment by PaulKinlan** [comment]
Let me sort something. I have a list of most things discoverable.

**Comment by marcoscaceres** [comment]
We didn't succeed in getting a list, unfortunately. One would still be nice.

**Comment by PaulKinlan** [comment]
I thought I sent you the list?

**Comment by marcoscaceres** [comment]
I can't seem to find it :( did anyone else get it?

**Comment by kenchris** [comment]
I never received anything :)

**Comment by marco-c** [comment]
https://github.com/mozilla/prowac could be interesting.

**Comment by RobDolinMS** [comment]
@PaulKinlan Just checking on the availability of this list.  Being able to look at a sample of sites to see how they're implementing Web App Manifest would be informative for potential features like splash screens (#9)
