### ISSUE TITLE
Manifest "sizes" fallback logic

### ISSUE THREAD

**Issue by laukstein** [w3c/manifest#409]
Reference: https://lists.w3.org/Archives/Public/public-webapps/2015OctDec/0064.html

Does "[sizes](https://w3c.github.io/manifest/#sizes-member)" has any fallback for device required different icon sizes?

    {
        "icons": [
            {
                "src": "32x32.png",
                "sizes": "32x32"
            }, {
                "src": "48x48.png",
                "sizes": "48x48"
            }, {
                "src": "128x128.png",
                "sizes": "128x128"
            }
        ]
    }

1. For example, would device request for 16x16 return scaled down image 32x32.png?
2. What about request 40x40 - would it scale up 32x32.png or scale down 48x48.png (40x40 is in middle of both those sizes (+8 = 48, -8 = 32))?
3. Would request 96x96 use 128x128.png?
4. Would request 192x192 and 512x512 use 128x128.png?

**Comment by marcoscaceres** [comment]
In Gecko, I'm just going to try to use `HTMLPictureElement` to do the selection (not sure if it will work, but going to try). That is, I just convert the JSON into a bunch of `<source>` elements and let the `<picture>` element tell me what the right thing is. 

So, it might be nice to generalize the image selection algorithm to take a display context, and a bunch of sources, and let the algorithm pick one.

**Comment by laukstein** [comment]
Related issue https://github.com/w3c/manifest/pull/407 **sizes="any"**.

**Comment by kenchris** [comment]
I think it is up to the platform (user agent) to decide how to best choose the icon, ie choosing a bigger one and scaling it down, which scaling algorithm to use etc.

**Comment by marcoscaceres** [comment]
I agree with @kenchris. We should do nothing here unless it becomes an issue.
