### ISSUE TITLE
Add integrity to image objects

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#411]
As manifest often rely on CDNs, it might be useful to add an `integrity` member to images.

**Comment by alertme-edwin** [comment]
Something like SRI would be useful more generally, so that manifests could point to fonts, stylesheets and scripts.  That way a single offline signature could be used to secure an entire web application.

**Comment by marcoscaceres** [comment]
> Something like SRI would be useful more generally, so that manifests could point to fonts, stylesheets and scripts. That way a single offline signature could be used to secure an entire web application.

Although it could be good, I'd prefer we don't overreach (i.e., let's stick to the things the manifest handles, instead of the things that belong to HTML). In any case, we would need to discuss any such addition with the Web App Sec group.

**Comment by marcoscaceres** [comment]
@mounirlamouri @kenchris, WDYT? Do we want to add support for this?

**Comment by mounirlamouri** [comment]
If an implementation is going to implement it, sure. Otherwise, I don't think that should be a priority.

**Comment by marcoscaceres** [comment]
SRI is only useful for link and script resources, so it doesn't apply to resources inside the manifest itself - as those are just images. The manifest itself could benefit from this tho, but that would be up to the SRI spec.
