### ISSUE TITLE
Icon schema considerations

### ISSUE THREAD

**Issue by kevinSuttle** [w3c/manifest#422]
Hello. I opened an issue with Schema.org about standardizing the icon schema. It has come up across many other software packaging environments, so I thought I'd bring it up here, after @marcellodesales pointed me to the latest working draft. 
https://www.w3.org/TR/appmanifest/#example-manifest

See: https://github.com/schemaorg/schemaorg/issues/939 for the research and proposal. 
Thank you.

**Comment by marcoscaceres** [comment]
@kevinSuttle thanks! Will comment in the schema.org issue.

**Comment by marcoscaceres** [comment]
@kevinSuttle the scope of our specification only deals with describing the aspects of image objects that are of immediate value to, and can be used explicitly by, Web browsers (i.e., arbitrary/linking/descriptive metadata - or metadata that can be inferred from the file itself upon retrieval). Hence, most of the stuff in the schema.org proposal does not apply to web browsers (e.g., codeRepository, dateCreated, etc.) - hence, it would be outside the scope of this specification to use the schema.org proposal.
