### ISSUE TITLE
Is RFC5988 supported by implementers?

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#424]
The last sentence of the spec's Abstract section mentions a document can be associated with a manifest "either directly in an HTML document or over the wire using RFC5988"  (https://tools.ietf.org/html/rfc5988) 

If I understand correctly, the directly in a HTML document would by via:
<link rel="manifest" href="..." >

And via RFC5988 would be a HTTP header:
Link: http://...; rel="manifest"

If referencing a manifest via RFC5988 is somewhat common and/or supported by implementers, I recommend we elaborate on this as a new section 5.2

If referencing a manifest via RFC5988 is very rare and/or not supported by implementers, I recommend considering removing the reference to this method in the Abstract section.

**Comment by RobDolinMS** [comment]
Thanks @mounirlamouri.  Should RFC5988 also be removed from the informative references?  
(I did a quick search and it looks like the place you're removing it in the Abstract is the only place it is referenced in the main spec)

**Comment by mounirlamouri** [comment]
I believe removing its usage will remove it from the reference.

**Comment by marcoscaceres** [comment]
I'm 50/50 on this... I actually implemented support for it in the past, but removed it as no one else was willing to implement it. It's not a terrible idea.

**Comment by marcoscaceres** [comment]
FWIW, Gecko does support RFC5988 for stylesheets... of course, no one uses it because you would still need to add style tags to get your styles to show up in other browsers.
