### ISSUE TITLE
Add description member

### ISSUE THREAD

**Issue by owencm** [w3c/manifest#435]
Lots of sites provide a description in metatags. We should support a `description` field in the manifest to capture this need.

In particular, I hear the Physical Web project wants to move to pulling metadata from the manifest, but make use of descriptions so this would be nice to be able to resolve.

**Comment by kenchris** [comment]
We already have this in Crosswalk (prefixed with xwalk_) and I heard that others like @RobDolinMS might also be interested in this.

**Comment by kenchris** [comment]
@boyofgreen I assume you have something similar in Manifold.js already?

**Comment by boyofgreen** [comment]
Yes, we actually map name to description if there is also a short name, but we have a few other fields that we prefix.   Prefixing in this scenario is no evil, but web developers will probably assume it is until we explain why.

**Comment by marcoscaceres** [comment]
I'd be in favor of this if people are willing to implement it and it serves some purpose in the context of a user agent (i.e., it's shown as part of an install dialog). Do we have a screenshot showing how physical web exposes the description to the user?

**Comment by kenchris** [comment]
One example here: https://developers.google.com/web/updates/images/2016/03/web-enabled-internet-of-things/physicalweb.png

**Comment by kenchris** [comment]
Also keep in mind that Crosswalk already uses something like this (xwalk_description)

**Comment by marcoscaceres** [comment]
@kenchris, thanks for providing the physical web screenshot. How does Crosswalk expose it?

**Comment by kenchris** [comment]
We use it when apps are submitted to the store (Play Store, Linux Deepin store, etc etc). In our meeting last time, I believe that @RobDolinMS wanted something similar.

I see little risk in adding this. It is already use somehow by Crosswalk, ManifoldJS and I believe others (@boyofgreen ?) wanted it for store submission as well, and it is definitely useful for other things as well (like web crawlers)

**Comment by marcoscaceres** [comment]
> On 5 Apr 2016, at 7:06 PM, Kenneth Rohde Christiansen <notifications@github.com> wrote:
> 
> We use it when apps are submitted to the store (Play Store, Linux Deepin store, etc etc). In our meeting last time, I believe that @RobDolinMS wanted something similar.
> 
> I see little risk in adding this. It is already use somehow by Crosswalk, ManifoldJS and I believe others (@boyofgreen ?) wanted it for store submission as well, and it is definitely useful for other things as well (like web crawlers)
> 

It's not really a question of risk; it's always been a question of browsers or OSs doing something meaningful with the metadata (I.e., in the past we've resisted and ejected any/all store related metadata - compare the first drafts of this spec, which had author, description, etc.). The aim of this spec should be, and has been, to enable installable web apps in precisely the way Chrome has implement the spec (using installability signals + add to homescreen)... Or, even Safari's add-to-homescreen stands as a good example of the goal  of this spec (despite the propriety aspects and shortcomings of their current offering).

This is to say that interested vendors SHOULD standardize store metadata: But we should do it as a separate effort. It's not, for instance, something Mozilla would support (given we tried that and it didn't go as we imagined).

Now, "description" MAY be of value to both browsers and stores (as the physical web example shows). That's what we need to ascertain. Hope that makes sense. 

The fundamental question is always: how will the browser/OS use this?

**Comment by kenchris** [comment]
Currently PWAs on Chrome doesn't use description, but there is no reason they couldn't offer a ^ arrow to review more info or an info button.

The Physical Web use-case should be quite obvious from the screenshot. You don't have the site open, so you want to know a bit about it.

From a Search Engine point of view, it would be the same. The user hasn't loaded the site yet (which could be shown as a PWA) but would like a bit of info about that it is and what it does. 

In the case for non-content pages (ie. single app pages) just deriving this info from the source is quite hard (look at the screenshot again so see what info it got from my app).

**Comment by boyofgreen** [comment]
every store has some sort of description requirements, most are appended outside of the manifest right now, but we would like to have a way to have all the necessary data for a listing right inside the manifest.  I am guessing if some day google.com or bing.com start listing apps within search results, it would be quite useful there too.

**Comment by marcoscaceres** [comment]
@boyofgreen, agree that that this would be useful for search engines, and possibly lots of other context. However, the bar for inclusion for things into the spec is driven by implementation: that is, if Google's or Bing's search teams (or browser teams) were to either implement support for it, or explicitly ask for it, then we should debate adding it (as we are doing). See, for example, "beforeinstallprompt" and "install" events in #417 - where @owencm asked for the inclusion of both events, being driven by their implementation experience in Chrome for Android. 

The same applies to this bug (also filed by @owencm), but with the Physical Web project as the backing implementation that needs this... however, IIUC, the Physical Web project is still fairly experimental, thus I'm soliciting further input from people about backing support in browsers - and particularly, how a browser might use this information and commitment to implementation.

**Comment by marcoscaceres** [comment]
@scottjenson, would really like your input here. If I add this to the spec, will you support it in Physical Web?

**Comment by scottjenson** [comment]
We're having a discussion about this very issue over on our github:

https://github.com/google/physical-web/issues/620#issuecomment-208353093

We clearly want to support this, we're just working out a few kinks.

**Comment by marcoscaceres** [comment]
@scottjenson, ok will wait to see the outcome from https://github.com/google/physical-web/issues/620.
