### ISSUE TITLE
Poorly coded example on w3c

### ISSUE THREAD

**Issue by ayumihamsaki** [w3c/manifest#437]
hi don't know who done the example in 1.1 but its terrible and very misleading. I am talking about: https://www.w3.org/TR/appmanifest/#example-manifest

The density on the icons and splash screens are totally wrong with the maths. For example in the splash screens part 320 x 3 does not equal 1920. I would remove a large section of that example code and write a correct code like this:

{
  "lang": "en",
  "dir": "ltr",
  "name": "Super Racer 2000",
  "short_name": "Racer2K",
  "icons": [{
        "src": "icon/lowres",
        "sizes": "64x64",
        "type": "image/webp"
        "density": 1
      }, {
        "src": "icon/hd_hi",
        "sizes": "128x128",
        "density": 2
      }],
  "splash_screens": [{
        "src": "splash/lowres",
        "sizes": "320x240",
        "density": 1
      }, {
        "src": "splash/hd_small",
        "sizes": "1280x960"
        "density": 4
      }, {
        "src": "splash/hd_hi",
        "sizes": "1920x1440",
        "density": 6
      }],
  "scope": "/racer/",
  "start_url": "/racer/start.html",
  "display": "fullscreen",
  "orientation": "landscape",
  "theme_color": "aliceblue",
  "background_color": "red"
}

See above correct maths on density and less confusing to people.

**Comment by marcoscaceres** [comment]
> hi don't know who done the example in 1.1 but its terrible and very misleading.

That would be me... Sorry it's terrible :cry:. 

Thanks for providing the improved version. I'll use it.

**Comment by marcoscaceres** [comment]
@ayumihamsaki, just a couple of things... your density descriptors are incorrect and will never match. The density descriptor is supposed to mean "ONLY use this when the device has this density" and not "this is the density of this icon". Hence, having a density of 6 means no device will match... at least probably not for about 20 years (if ever... as I doubt we will get 6x density displays). Also, density 1 is implied, so it's redundant to include it.

**Comment by marcoscaceres** [comment]
@ayumihamsaki, also, please note that having the two "sizes": "64x64", was deliberate - because they discriminate by `"type":`. As Gecko and Edge, for instance, don't not support webp, they would skip over that icon.
