### ISSUE TITLE
Clarify how image objects should be fetched

### ISSUE THREAD

**Issue by jakearchibald** [w3c/manifest#443]
Chrome stable has this bug - https://sw-cors-demo.herokuapp.com/

1. Image would be requested
1. SW would cache the request & response
1. "Add to homescreen" pressed
1. Icon fails to load

This is because the icon was fetched with mode "cors", and the service worker responded with an opaque response.

Chrome has since fixed this issue, but this spec should detail how images should be fetched to avoid other UAs making the same mistake.

Fetching should be similar to https://html.spec.whatwg.org/multipage/embedded-content.html#update-the-image-data - as in mode "no-cors".

**Comment by marcoscaceres** [comment]
@jakearchibald, the fetch spec says:

> "Even though the default request mode is "no-cors", standards are highly discouraged from using it for new features. It is rather unsafe. "navigate" and "websocket" are special values for the HTML Standard. [HTML]"

Maybe need an Ok from @annevk to use no-cors here? 

I'll assume @jakearchibald is right, and spec it up tho. But just want to make sure it's all ok.

**Comment by marcoscaceres** [comment]
Created a PR: https://github.com/w3c/manifest/pull/459

**Comment by annevk** [comment]
Ideally this would reuse the HTML pipeline for image loading, but that's still not nicely refactored...

I don't mind using no-cors here, but it's not clear why this particular issue isn't an issue with the service worker though. Would it just fail to load other CORS requests properly as well?

**Comment by marcoscaceres** [comment]
> Ideally this would reuse the HTML pipeline for image loading, but that's still not nicely refactored...

Yeah, it's hard to use without 🐵patch. It is heavily dependent on both ImageElement and Document, etc. Fetch has all the right bits.
