### ISSUE TITLE
Possible Registry for Extension Properties

### ISSUE THREAD

**Issue by dret** [w3c/manifest#452]
The current draft has a very useful extension point that is supposed to catch properties that are not specified in the draft itself. One possible way to make this a bit more managed would be to establish a registry where new properties can be registered and then become well-known. This way other specs extending what can be represented in a webapp manifest could do that in a more managed way.
https://tools.ietf.org/html/draft-wilde-registries talks about the general pattern of having a registry, and if there were such a registry, then the nect question would be how to establish one. There are several design options for this, but this issue is simply about the question of whether having a registry would be a useful thing to do.

**Comment by adrianhopebailie** [comment]
I need to think a little more about this but would like to highlight our use case as evidence for this issue.
We've leveraged the "actions" format from the Ballista project but this may change.

Our core requirement is for an app to advertise a set of payment methods it supports (using their string identifiers).

The proposed spec that extends Manifest is here: https://w3c.github.io/webpayments/proposals/paymentapps/payment-apps.html

You'll note that we have defined an interface for `manifest` which we'd be happy to move to the manifest core spec. Perhaps this object could be returned as part of the install events?

**Comment by dret** [comment]
thanks for the note @adrianhopebailie and good to see that there's another use case popping up pretty much immediately. could you see yourself using manifest by specifying a bunch of extension properties and registering them in whichever way prescribed by the webapp spec? i think opening it up this way would be more robust than hardcoding the extensions in the webapp spec itself.

**Comment by marcoscaceres** [comment]
> On 15 Apr 2016, at 6:29 AM, Adrian Hope-Bailie <notifications@github.com> wrote:
> 
> I need to think a little more about this but would like to highlight our use case as evidence for this issue.
> We've leveraged the "actions" format from the Ballista project but this may change.
> 
The ballista folks are still experimenting. It seems premature for web payments to be adding that.
> Our core requirement is for an app to advertise a set of payment methods it supports (using their string identifiers).
> 
> The proposed spec that extends Manifest is here: https://w3c.github.io/webpayments/proposals/paymentapps/payment-apps.html
> 

Whoa! Please don't do that!!! I kindly ask that you bring extensions to this forum for discussion and standardization. 

> You'll note that we have defined an interface for manifest which we'd be happy to move to the manifest core spec. Perhaps this object could be returned as part of the install events?
> 

Yes. Please immediately remove that from the web payments spec and file a bug on this spec.

**Comment by adrianhopebailie** [comment]
> The ballista folks are still experimenting. It seems premature for web payments to be adding that.

Yep, that's why it will likely change.

> Whoa! Please don't do that!!! I kindly ask that you bring extensions to this forum for discussion and standardization.

Doesn't that defeat the purpose of extension points? Extension points are included in algorithms to avoid monkey patching. The extension point is defined so that custom processing can be defined and executed at that point in a way that doesn't require changes to the base algorithm (the definition of a monkey patch).

Why would you ever want to include custom behavior for payment apps directly in the web app spec?

> Yes. Please immediately remove that from the web payments spec and file a bug on this spec.

I had been planning to submit a PR with this WebIDL included but was waiting to see what the install events changes looked like.

Bare in mind that this is not the web payments spec. It's just a proposal at this time. Your feedback is appreciated :smile:

**Comment by marcoscaceres** [comment]
> Doesn't that defeat the purpose of extension points? Extension points are included in algorithms to avoid monkey patching. The extension point is defined so that custom processing can be defined and executed at that point in a way that doesn't require changes to the base algorithm (the definition of a monkey patch).

No, I was referring to the API that spec adds. New members are ok, but you seem to be doing other things there.

> Bare in mind that this is not the web payments spec. It's just a proposal at this time. Your feedback is appreciated 

Oh, phew. Ok, I thought it was the real spec. That document should not be using the W3C Editor's draft status: please change it to "unofficial".

**Comment by dret** [comment]
> Doesn't that defeat the purpose of extension points? Extension points
> are included in algorithms to avoid monkey patching. The extension point
> is defined so that custom processing can be defined and executed at that
> point in a way that doesn't require changes to the base algorithm (the
> definition of a monkey patch).

i think that's a good starting point. one of the important things of a 
spec is always the processing model, though. so what you should never do 
(and the underlying spec should outrule this in the strongest terms) is 
to change the processing of the core vocabulary. in other words, 
somebody not knowing your extension, but only knowing the core set, 
should be able to process the manifest and get meaningful and correct 
behavior out of it. if that's not the case, something is wrong.

**Comment by dret** [comment]
On 2016-04-14 21:00, Marcos Cáceres wrote:
> No, I was referring to the API that spec adds. New members are ok, but
> you seem to be doing other things there.

@marcoscaceres: if, hypothetically, the manifest spec had a registry 
associated for those extension values to be registered and discovered, 
would you be ok with that draft simply adding its own processing model 
for them (without changing any behavior for the core ones, which of 
course would need to be disallowed), registering them, and that would be 
how the webapp spec could be used as a foundation?

**Comment by marcoscaceres** [comment]
> @marcoscaceres: if, hypothetically, the manifest spec had a registry
associated for those extension values to be registered and discovered,
would you be ok with that draft simply adding its own processing model
for them (without changing any behavior for the core ones, which of
course would need to be disallowed), registering them, and that would be
how the webapp spec could be used as a foundation?

I'm not sure I fully understand the question above, but I'm in favor or adding a registry. However, I want it to be super light weight.

I've created https://github.com/w3c/manifest/wiki/Extensions-Registry

I'm sending a PR now that points to the registry from the spec.
