### ISSUE TITLE
Case sensitivity of enumerated values

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#460]
The spec treats enumerated values as case **sensitive**, but Chrome implements them as case **insensitive** 😱 + 🙀. 

@mounirlamouri, you broke the Web! Should I update the spec (and Gecko) to reflect Chrome's implementation? To be fair, `sizes` is explicitly treated as case insensitive, so there is precedence to make the values of  members case insensitive.

**Comment by mounirlamouri** [comment]
Usually the Web isn't very picky with case. Enumerated attributes in HTML being an example. Sorry for the oversight here.

**Comment by marcoscaceres** [comment]
@mounirlamouri, no need to apologize and you are right about the Webs - I looked over the spec and I was not very clear - so I blame the guy writing the text! I'm going to update the spec and my imp. It's a trivial fix for both the spec and Gecko implementation.

**Comment by marcoscaceres** [comment]
The most webby solution is to just normalize enumerated members to lower-case, and canonicalize others (e.g., `lang`). This works like case insensitive comparisons. I've sent a PR.
