### ISSUE TITLE
Need to specify client of image objects when fetching  

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#465]
@annevk wrote, re: obtaining image objects: 

> Referrer policy also needs to come from somewhere. I guess if you don't have a client you'll need some integration with the referrer policy specification then...

**Comment by marcoscaceres** [comment]
Moving @annevk's comments from #443 here... 

> Yeah, maybe that's better. Although it's a little weird since you can be associated with multiple documents, right?

Not necessarily. The perhaps short-sighted view is that "installation" and downloading of the icons is based on a single active Document... 

> And that document might disappear and then another one might appear?

If the Document vanishes, then the installation process would stop (this is not currently captured in the spec). 

> Would that mean you get a new policy?
> How does CSP work today for manifest resources?

It uses the Document's security principle, respecting `img-src`.  See:
https://w3c.github.io/manifest/#content-security-policy-of-image-objects

**Comment by annevk** [comment]
A manifest is only useful when you install? We wouldn't use it for favicons and such?

**Comment by marcoscaceres** [comment]
> A manifest is only useful when you install? We wouldn't use it for favicons and such?

Probably not, no. They are only really useful for representing a larger grouping of URLs ("an app" or "a site"). On a page-by-page basis, it seems fine to keep using favicons and link rel=icon.

**Comment by annevk** [comment]
It just sounds so... pointless. And a bit of a pain from a security perspective if it's anchored neither here nor there. Though maybe document-that-linked-to-it-first is good enough.

**Comment by benfrancis** [comment]
> Probably not, no. They are only really useful for representing a larger grouping of URLs ("an app" or "a site"). On a page-by-page basis, it seems fine to keep using favicons and link rel=icon.

FWIW in Firefox OS 2.5 we use icons from a manifest in the URL bar without installation. We assume the manifest icon applies to the whole site whereas a link rel=icon applies to a single page. We fall back to a page icon if a site icon isn't provided.

**Comment by marcoscaceres** [comment]
> On 27 Apr 2016, at 7:16 PM, Anne van Kesteren <notifications@github.com> wrote:
> 
> It just sounds so... pointless. And a bit of a pain from a security perspective if it's anchored neither here nor there. Though maybe document-that-linked-to-it-first is good enough.
> 
I'd rather it not be pointless. I'm happy the manifest's icons to be used as you suggested. We haven't added that because no products have asked for it. Can't hurt if implementors get it for free.

Will that make it a useful part of the platform?

**Comment by annevk** [comment]
Maybe, I think a big problem is that the delivery is late and cannot be relied upon when interpreting a document. If we had something that was guaranteed to be available we could put CORS information in there, CSP, and other things. But the late-binding approach kills it I think.

**Comment by annevk** [comment]
(To be clear, I'm pretty sure I mentioned that to you before, though maybe not in specific enough terms.)

**Comment by jakearchibald** [comment]
@annevk 

> It just sounds so... pointless.

The benefit of the manifest is it's fetched when it's needed, which may be "never" in most visits. Previously we had a big ol' dump of meta-crap sitting in the `<head>` of every page, delaying first render.

**Comment by annevk** [comment]
@jakearchibald except you need icons and such each visit.

**Comment by jakearchibald** [comment]
Yeah, so that stuff is still needed in the head. So theme color & an icon (if it isn't `/favicon.ico`) in the head, then the rest, including bigger icons, in the manifest.

**Comment by annevk** [comment]
Still seems rather pointless to have a whole new resource for just that including all the complexity it brings. Might as well insert some additional icons later in the main document. Especially given that we need something manifest-like for origins that is available straight away.

**Comment by annevk** [comment]
Also, you're assuming an awful lot about the particular UI of a user agent. What if browsers with more room for the favicon return? What if the user agent supports higher resolution there? All those would require the icon to be available together with the main resource.

**Comment by jakearchibald** [comment]
Fair, it would need to be downloaded earlier in that case, but at least it's cachable and doesn't need to block content render.

**Comment by annevk** [comment]
Can you really say that a couple of extra elements in `<head>` cause a measurable delay? It seems that would be tiny compared to the several megabytes of a page.

**Comment by jakearchibald** [comment]
https://github.com/h5bp/mobile-boilerplate/blob/master/index.html it was starting to get pretty bad.

**Comment by annevk** [comment]
So once you hit 11 icons it's time for a new format that lists 10 of them?

**Comment by marcoscaceres** [comment]
Talked to @annevk. Reopened so we have a correct reference to an environment settings object (one that maps to a concrete thing in the implementation). Gecko does not currently implement actual acquisition of image objects from the manifest - so I don't have a concrete example of what we do... (I had a WIP patch that used a `<picture>` element to figure out the icon selection... will try to dig it up).

**Comment by aarongustafson** [comment]
@marcoscaceres Should this move over with `ImageResource`?

**Comment by marcoscaceres** [comment]
Yes, it should be specified as part of the fetching model.

**Comment by marcoscaceres** [comment]
Closing as [fetching an image resource](https://www.w3.org/TR/appmanifest/#fetching-image-resources) is specified in terms of fetch. If there are specific bugs or clarifications needed (e.g., #851), then can deal with them separately.
