### ISSUE TITLE
short_name to fall back to name & vice versa

### ISSUE THREAD

**Issue by jakearchibald** [w3c/manifest#466]
I'm seeing developers with manifests where `name` and `short_name` are duplicates, which is ok, but shouldn't be required.

It'd be nice if the `name` and `short_name` members explicitly fell back to each other. This will hopefully avoid an implementation giving up on displaying a name because `short_name` was empty, yet `name` was defined & already as short as it could be, eg "Facebook".

**Comment by slightlyoff** [comment]
I'd prefer to see a single field which is clearly the default. Given how `name` and `short_name` are used today by implementations, that might require a new field (strawman: `default_name`). The bi-directional fallback seems like a recipe for developer confusion and a lack of control.

**Comment by jakearchibald** [comment]
Don't have strong feelings about `name` falling back to `short_name`, but I think the naming already makes sense. `short_name` is more specific than `name`, as it has the `short_` requirement. If `name` is already short, it should be fine.

If in future we have `emoji_name`, it similarly shouldn't be required if `name` is already emoji.

**Comment by benfrancis** [comment]
FWIW, so far in the Firefox OS implementation we always do:

> name = short_name || name;

when displaying the app name because we basically always want the shortest version available.

**Comment by jakearchibald** [comment]
Interesting. So in the case of:

```json
{
  "name": "Words With Friends",
  "short_name": "Words"
}
```

…you'd never display "Words With Friends"? We use the longer name in the add-to-homescreen prompt and the splash-screen, but favour the short name for the homescreen icon label.

**Comment by marcoscaceres** [comment]
Bingo. It's about context of use. The UA is supposed to chose when and where to show the appropriate version. The motivation was iOS's app search, which let's you search for both long and short name (even if short name is displayed).

**Comment by jakearchibald** [comment]
Cool. Well given that both Chrome & Firefox treat "name" as a fallback to "short_name", I think that should go into the spec. The failure case here is requiring devs to duplicate "name" and "short_name" because some UA doesn't do the fallback.

**Comment by mounirlamouri** [comment]
I agree that we might want to add to the spec that UA should use `name` as a fallback for `short_name` and `short_name` as a fallback for `name`. Developers who just want to use one name could just set either of those (like `name`) and be done with it.

Chrome already has code paths where `name` is favoured over `short_name` (splash screen) and some where `short_name` is favoured over `name` (homescreen).

**Comment by marcoscaceres** [comment]
Sounds like a plan.
