### ISSUE TITLE
Allow unique start_url for subdomains

### ISSUE THREAD

**Issue by gui-poa** [w3c/manifest#470]
Even with the access-control-allow-origin header in the manifest.json, it's not possible to use the same start_url for subdomains.

_Manifest: property 'start_url' ignored, should be same origin as document._

It would be great to set the homepage in start_url for article pages in different subdomains.

https://twitter.com/jaffathecake/status/742415227015303168

**Comment by marcoscaceres** [comment]
I think this depends on https://storage.spec.whatwg.org/#site

**Comment by RobDolinMS** [comment]
@gui-poa You might want to take a look at #449 to see a solution to that could address your case.

**Comment by thomaspessato** [comment]
@marcoscaceres have you heard any news about this? I'm really looking forward to to use this 👊

**Comment by marcoscaceres** [comment]
@thomaspessato, not yet, sorry :(

**Comment by gui-poa** [comment]
Just to let it clear:

We have articles published inside subdomains, like: sports.example.com, politics.example.com. So the best start_url when the user get prompted while reading an article should be the home: www.example.com

**Comment by RobDolinMS** [comment]
@gui-poa Would you please elaborate on your example?  Would there be a single PWA for example.com or would there potentially be multiple PWAs for sports.example.com and politics.example.com?

**Comment by gui-poa** [comment]
Both...

Like this:
news.example.com -> example.com (start url) SAME PWA
sports.example.com -> example.com (start_url) SAME PWA
politics.example.com -> example.com (start_url) SAME PWA


games.example.com -> games.example.com (start_url) ANOTHER PWA

**Comment by RobDolinMS** [comment]
Trying to make sure I understand the set-up ...

There is one PWA with Manifest hosted at `example.com/manifest.json`:
``` json
{
   "name": "Example PWA",
   "start_url": "example.com"
}
```

There is another PWA with Manifest hosted at `games.example.com/manifest.json`:
``` json
{
  "name": "Another PWA",
  "start_url": "games.example.com"
}
```

These Manifests are referenced on the respective HTML pages:
HTML page: `news.example.com` includes:
`<link rel="manifest" href="example.com/manifest.json" />`

HTML page `sports.example.com` includes:
`<link rel="manifest" href="example.com/manifest.json" />`

HTML page `politics.example.com` includes:
`<link rel="manifest" href="example.com/manifest.json" />`

HTML page `games.example.com` includes:
`<link rel="manifest" href="games.example.com/manifest.json" />`

@gui-poa Is this an accurate description of the set-up ?  
 * If there's more that I'm missing, would you please explain?
 * If this is an accurate description, would you please elaborate on what is not working?

**Comment by gui-poa** [comment]
Yes, you are right.

So talking about the first PWA (example.com and its subdomains[articles])

Today the user is never getting prompted while reading an article because of this:

manifest-br.json:1 Manifest: property 'start_url' ignored, should be same origin as document.
manifest-br.json:1 Manifest: property 'scope' ignored, should be same origin as document.

Thanks for your attention, Rob.

**Comment by gui-poa** [comment]
I guess a real case would be better to explain.

It's not allowed to add to homescreen (www.terra.com.br) from here
https://esportes.terra.com.br/lance/representante-da-kanxa-critica-conduta-do-boa-sobre-bruno-em-momento-algum-nos-avisaram,066137a911874031b9564f246036b363ovyt9n8g.html

![pwa_github](https://cloud.githubusercontent.com/assets/1610365/23928153/021fb15c-08fd-11e7-87fe-80e9cfd40015.jpg)

**Comment by gui-poa** [comment]
Rob, do you think this request is reasonable?

I'm planning a project to start killing the subdomains around here in the near future.

**Comment by RobDolinMS** [comment]
Thanks @gui-poa.  Sorry for my delayed response.  I had family visiting and was away from GitHub.

I think the request is reasonable.  I'm wondering if the idea of supporting multiple scopes as described in #449 would address this scenario.

**Comment by gui-poa** [comment]
No problem. :)
Yep, reading #449 I can't know if this would solve it.

**Comment by gui-poa** [comment]
Just to inform, Rob.

This week we removed the subdomains. And, as we expected, the number of PWA installations has increased. (as well as cancels too. lol)
![a2hs](https://cloud.githubusercontent.com/assets/1610365/25066005/8fc6171a-21f0-11e7-9f02-b4a1da4b09b4.jpg)

**Comment by davido242** [comment]
Answers are not straightforward honestly!
