### ISSUE TITLE
Define core web manifest to enable extensions

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/manifest#471]
From the Digital Publishing IG:
Would it be a more extensible architecture to define a "core" web manifest, with common terms, procedures, etc, with an extension model that could be used to define a Web App manifest and others, depending on the usage patterns? 
Here are some examples of what this might mean for the publishing world:

- Section 7.2 [1] allows for extension points, but this is listed in processing instructions and not explicit. Would it be possible to add a section clarifying the extension process? Digital Publishing will likely be interested in expanding the definition of “manifest” [https://www.w3.org/TR/appmanifest/#dfn-manifest] and possibly scope and navigation so that it is clear that a specific set of objects are contained a publication.
- Publishing might not require all manifest members. In this case, it would be helpful if specific members (e.g. “theme_color”) could be optional. 

[1] https://www.w3.org/TR/appmanifest/#dfn-extension-point

**Comment by marcoscaceres** [comment]
> On 21 Jun 2016, at 12:22 AM, Tzviya <notifications@github.com> wrote:
> 
> From the Digital Publishing IG:
> Would it be a more extensible architecture to define a "core" web manifest, with common terms, procedures, etc, with an extension model that could be used to define a Web App manifest and others, depending on the usage patterns? 
> Here are some examples of what this might mean for the publishing world:
> 
> Section 7.2 [1] allows for extension points, but this is listed in processing instructions and not explicit. Would it be possible to add a section clarifying the extension process? Digital Publishing will likely be interested in expanding the definition of “manifest” [https://www.w3.org/TR/appmanifest/#dfn-manifest] and possibly scope and navigation so that it is clear that a specific set of objects are contained a publication.

Sure, but we would need to understand the use cases better and any current limitations. What exactly is not clear about the extension point and where to hook into the algorithm? 

> Publishing might not require all manifest members. In this case, it would be helpful if specific members (e.g. “theme_color”) could be optional.

All members are optional in the spec. Apologies if that was not clear.

**Comment by TzviyaSiegman** [comment]
From an algorithmic point, the extension mechanism is clear. It’s From an editorial perspective, how do I write an extension to this spec? DPUB is preparing a draft that identifies manifest for publications. How would we hook this in?

Three of us read through the spec in detail, and it was not clear to any of us that members are optional.

**Comment by iherman** [comment]
@marcoscaceres to extend what @TzviyaSiegman said: I wonder whether it is a possible approach, editorially, to re-engineer the document in such a way that a 'core' would be defined as normative requirement (we would have to look at it closely, things like security considerations or locating a manifest come to my mind; the processing structure as well) and then a separate section that defines the terms for Web Applications. Other communities, like publishing, could hook their manifests on the same level.

Just an idea...

Thanks

**Comment by marcoscaceres** [comment]
@TzviyaSiegman, @iherman, we would still like to hear what you are going to propose as extensions. If it's something that the whole web will benefit from, then we should work together. Having said that...  

>  how do I write an extension to this spec?
 
@TzviyaSiegman, see, for example:
http://w3c.github.io/manifest-csp/

And in particular how the hook is used: 
http://w3c.github.io/manifest-csp/#processing-the-manifest

**Comment by marcoscaceres** [comment]
@iherman, to your proposal: I would like to generalize some of the algorithms at some point... like "run the steps to process a string", "run the steps to process a space separated list" , etc. and you would get a lot of the security properties for free. It's what implementations do already, and would make the spec a lot smaller. Just haven't found time to do that. 

As a further step, at least in Gecko, we are thinking that once processing of a manifest has occurred, we send it into our WebIDL machinery to further sanitize the manifest. That might happen if we end up exposing the manifest's values to the Web via an JS API - which we currently don't do, but some people are requesting we should.

**Comment by iherman** [comment]
@marcoscaceres 

>@iherman, to your proposal: I would like to generalize some of the algorithms at some point... like "run the steps to process a string", "run the steps to process a space separated list" , etc. and you would get a lot of the security properties for free. It's what implementations do already, and would make the spec a lot smaller. Just haven't found time to do that. 

Thanks! That sounds great, and it goes in the direction I was wondering about. I believe there may be some terms in the current document that may be generic (eg, `scope`?) as well as obtaining the manifest (although, in our own discussions where we also looked at how to obtain manifests for Web Publications we went a bit further in the possibilities than what you considered, see [current PWP draft](http://w3c.github.io/dpub-pwp/#manifest_algorithm).

Exposing the manifest values through a JS API... I must admit I did not think about that before; because the manifest is in JSON, it is "just" a big object with keys and values from a JS point of view, I am not sure what it would bring. But I do not claim to be a JS programmer, so I may miss something.

**Comment by marcoscaceres** [comment]
Will take a look! thanks for the pointer. Please be warned that you shouldn't mess with how to obtain a manifest, as it's carefully designed to work with the security model of the Web (i.e., it's not just JSON you can just grab.... CORS and CSP play a role, and there are a bunch of security restrictions, etc. that it took a long time to work through). That's why the manifest spec only allows you to add and process simple values, but doesn't let you interface with how to obtain a manifest or other moving parts. 

Regarding the API, it's all to do with the lifecycle of the web application - you could generate the icons on the fly, for instance. I've done that before using a Service Worker. We don't have much of an idea of what an API might look like yet... I've opened #472 to discuss.

**Comment by iherman** [comment]
> On 23 Jun 2016, at 11:33, Marcos Cáceres <notifications@github.com> wrote:
> 
> Will take a look! thanks for the pointer. Please be warned that you shouldn't mess with how to obtain a manifest, as it's carefully designed to work with the security model of the Web (i.e., it's not just JSON you can just grab.... CORS and CSP play a role, and there are a bunch of security restrictions, etc. that it took a long time to work through). That's why the manifest spec only allows you to add and process simple values, but doesn't let you interface with how to obtain a manifest or other moving parts.
> 
I think there are to major differences. One is that we also consider manifests (ie, JSON content) embedded in the HTML content using a <script> element, and we also have to consider (but that may be special to the publishing world) when the manifest is included in a packaged content entirely (ie, a packaged book). The latter is probably specific to publishing; I hope that none of these two lead to special security issues. But I am sure you have more experience with that than we have. The other difference is that we consider situations when manifests are combined, ie, it is not that the content is always in one place; that may again be the consequence of the publishing world, where some metadata may be published via a different workflow than the main content.

**Comment by marcoscaceres** [comment]
@TzviyaSiegman @iherman, I think you have most of what you need, right? Let me know if you have any further questions - happy to try to help.

**Comment by iherman** [comment]
@marcoscaceres 

>@TzviyaSiegman @iherman, I think you have most of what you need, right? Let me know if you have any further questions - happy to try to help. 

turning this around: if you find the time and look into what you described in [your comment](https://github.com/w3c/manifest/issues/471#issuecomment-227996134), I think we would be happy to contribute and feed back.

**Comment by marcoscaceres** [comment]
Yeah, absolutely... just need to find more cycles :(  Where is all those AI bots we were promised? can we teach them to write specs for us?
