### ISSUE TITLE
Install event definition is missing some details

### ISSUE THREAD

**Issue by RByers** [w3c/manifest#475]
The [section on the install event](https://w3c.github.io/manifest/#installation-events) seems incomplete.  For example, what is the type of the event (I assume just `Event`?), what are its `cancelable` and `bubbles` properties set to?  Is there a default action? 

The spec doesn't even seem to say explicitly that there is a DOM event called "install" outside the example (technically the `oninstall` attribute is separate).  But the intent is clear.

See, for example, the [load event](https://w3c.github.io/uievents/#event-type-load) for a more completely defined DOM event.

**Comment by mgiuca** [comment]
I filed almost the same bug yesterday ([#473](https://github.com/w3c/manifest/issues/473)). A fix is in flight. But we didn't discuss `cancelable` and `bubbles`.

**Comment by RByers** [comment]
Ah sorry I missed that bug, lets continue there.
