### ISSUE TITLE
Define how the manifest is fetched

### ISSUE THREAD

**Issue by jakearchibald** [w3c/manifest#481]
Similar to how icon fetching has been defined, define how the manifest itself is fetched.

**Comment by marcoscaceres** [comment]
@jakearchibald, can you clarify a bit more what you want to see changed from this algorithm: 
https://w3c.github.io/manifest/#obtaining

That's literally how I implemented it in Gecko.

**Comment by jakearchibald** [comment]
Hmm, I somehow completely missed that. My cmd+f skills failed.

**Comment by marcoscaceres** [comment]
@annevk, in the fetch spec, did Request's "context" get renamed to "destination"?

**Comment by marcoscaceres** [comment]
reopening, because I think this also has the "environment settings object" issue.... I'm still really struggling to understand what/where/how "environment settings object" is... and what to put in the spec. 

I'm desperate for some help. @jakearchibald, maybe you understand it or can point me to an example of usage?

**Comment by jakearchibald** [comment]
Hah, was coming back to do the same. The client of the request needs to be set.

The loading steps for img use "Set request's client to the element's node document's Window object's environment settings object"

**Comment by marcoscaceres** [comment]
> "Set request's client to the element's node document's Window object's environment settings object"

@annevk says that is wrong tho so I'm kinda stuck because I don't, despite reading now at least 50 times, understand what [HTML says](https://html.spec.whatwg.org/multipage/webappapis.html#environment-settings-object) 😢 

@domenic, maybe you can help us? The Editors of this spec don't understand what a client settings object is. We've tried to make heads or tails of the HTML spec, but we don't get it. The examples currently there don't help us. Can you provide us with some guidance?

**Comment by domenic** [comment]
There are three entities that are 1:1:1 that you should know about: realm, global object, and environment settings object. Roughly, the global object is the thing JS developers see; the realm is the stuff the JavaScript spec uses to track extra data about the global environment; and the environment settings object is the stuff web platform specs use to track extra data about the global environment.

When doing a request, it's important to know what realm/global/settings object it came from. This is embodied in the concept of a request client, which is an environment settings object.

I think you should probably just set the client to the element's [relevant settings object](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-settings-object). However, I just checked https://html.spec.whatwg.org/multipage/semantics.html#concept-link-obtain, and it uses the more complicated formalism of "the link element's node document's Window object's environment settings object." That seems weird to me... @annevk, any thoughts on why it does that?

Also it seems like this spec is duplicating https://html.spec.whatwg.org/multipage/semantics.html#concept-link-obtain (just with different CORS semantics), which is a bit sad?

**Comment by annevk** [comment]
@domenic if you move an element across documents, it's currently unclear whether the relevant settings object changes for that element (a disputed topic). Therefore it makes more sense to talk about the element's node document's relevant settings object. We could simplify it to that probably. I suspect this is leftover from before the cleanup rounds.

**Comment by marcoscaceres** [comment]
> relevant settings object.

Ah! Now it's all slotting into place! THANK YOU! 

> Also it seems like this spec is duplicating https://html.spec.whatwg.org/multipage/semantics.html#concept-link-obtain (just with different CORS semantics), which is a bit sad?

Agree. That is sad... I believe it was @mounirlamouri that wanted to change the samantics. I'm in favor of doing what HTML says to do.

**Comment by marcoscaceres** [comment]
@domenic, iirc, the reason @mounirlamouri didn't want to use "obtain a resource" was because he didn't want to fire the load/error events at the link element. I don't have a strong opinion about firing the events.

**Comment by annevk** [comment]
Why would we not fire them? But also, that should be defined through some hook. Otherwise it's not clear from reading the HTML Standard you might not get those events.

**Comment by marcoscaceres** [comment]
> But also, that should be defined through some hook. 

In HTML or the manifest spec? 

>Otherwise it's not clear from reading the HTML Standard you might not get those events.

It's been a while, but it was fairly clear from HTML that the events would fire. Can you clarify a bit?

**Comment by annevk** [comment]
I meant that you should then add some hook to HTML to disable dispatching those events. Presumably implementations reuse most of the codepath too?

**Comment by mounirlamouri** [comment]
Chromium implementation doesn't use the same path as `<link>`, instead we use the `<link>` to get the cross origin and the src then we start a regular fetch when needed. The manifest is loaded on demand and even though I do not exactly remember why I did not want to fire the events, it would make sense to not fire them if they could happen at any point between page load and page close (they become worthless and a great footgun).

**Comment by marcoscaceres** [comment]
> Chromium implementation doesn't use the same path as <link>, instead we use the <link> to get the cross origin and the src then we start a regular fetch when needed. 

We do the same in Gecko. 

> The manifest is loaded on demand and even though I do not exactly remember why I did not want to fire the events, it would make sense to not fire them if they could happen at any point between page load and page close (they become worthless and a great footgun).

Agree. We don't want developers to confuse the load or error events with meaning that it's being installed or cancelled. The UA is free to load the manifest resource as needed, when needed.

**Comment by isonmad** [comment]
> in the fetch spec, did Request's "context" get renamed to "destination"?

Not sure if this should be a separate bug, but I noticed that too. It got split into initiator+destination in August 2015, so that step in the manifest spec makes no sense anymore. https://github.com/whatwg/fetch/commit/d2208faa939998cf56bb08a724cd8d4590afea47 https://github.com/whatwg/fetch/issues/93

**Comment by kenchris** [comment]
@marcoscaceres could you list what still needs to be done here?

**Comment by marcoscaceres** [comment]
Someone who understands fetching better than me needs to read over the spec and make sure it's done right (tm).

**Comment by kenchris** [comment]
Do you know who we can get to do that?

**Comment by marcoscaceres** [comment]
I do, but it's one of those "trial by fire" things where we need to make an effort research and understand what we are doing first (we won't get any help unless it affects implementers). 

Basically, we need to set aside a month or two to do some in-depth reading.

**Comment by marcoscaceres** [comment]
[Obtaining](https://www.w3.org/TR/appmanifest/#obtaining) is defined in terms of fetch, so unless there is a specific bug (e.g., #821), then I think we are good here.
