### ISSUE TITLE
Discoverability of metadata in web application manifest

### ISSUE THREAD

**Issue by dauwhe** [w3c/manifest#486]
A web app manifest contains metadata that search engines might be interested in. It also provides a way for metadata to describe a collection of web resources as a unit. Has there been any discussion of aligning some of the members with schema.org? 

Just for fun, here's the first example in the spec, modified so that Google can understand a fair amount of the metadata.

```json
{
	"@context": "http://schema.org/",
	"@type": "MobileApplication",
	"applicationCategory": "Game",
	"inLanguage": "en",
	"name": "Super Racer 2000",
	"description": "The ultimate futuristic racing game from the future!",
	"alternateName": "Racer2K",
	"image": [{
		"@type": "imageObject",
		"contentUrl": "icon/lowres.webp",
		"height": "64",
		"width": "64",
		"encodingFormat": "image/webp"
	}, {
		"@type": "imageObject",
		"contentUrl": "icon/lowres.png",
		"height": "64",
		"width": "64",
		"encodingFormat": "image/png"
	}, {
		"@type": "imageObject",
		"contentUrl": "icon/hd_hi",
		"height": "128",
		"width": "128"
	}],
	"scope": "/racer/",
	"start_url": "/racer/start.html",
	"display": "fullscreen",
	"orientation": "landscape",
	"theme_color": "aliceblue",
	"background_color": "red"
}

```

**Comment by patrickkettner** [comment]
Microsoft has already spoke in public about using Bing to index the manifest files. Since it is structured data (albeit it not in the traditional schema), it would be cake for any engine to understand it in its current form.

**Comment by marcoscaceres** [comment]
mmm... cake.

**Comment by marcoscaceres** [comment]
So, we once had that in the spec, but we took it out:
https://github.com/w3c/manifest/pull/316

As @patrickkettner mentioned: it's trivial for an engine to decipher the semantics of each element based on the fact that it's a standardized web manifest (without schema.org's stuff). It can do that by the link type or the mime type.
