### ISSUE TITLE
Redundant reference to ISO 3166?

### ISSUE THREAD

**Issue by chaals** [w3c/manifest#488]
From Addison Philipps by email: 

I was looking at https://www.w3.org/TR/appmanifest/#lang-member today. I noticed this text in section 8.2:

> A language tag is a string that matches the production of a Language-Tag defined in the [BCP47] specifications (see the IANA Language Subtag Registry for an authoritative list of possible values, see also the Maintenance Agency for ISO 3166 country codes)

I'm wondering why the reference to ISO 3166 country codes is maintained in addition to the IANA Language Subtag Registry. The IANA registry contains all of the 3166 values in a stabilized fashion and tracks changes to 3166. Is there a purpose to maintaining the additional reference (especially since other standards referenced by BCP 47 are not mentioned (e.g. ISO 639-1/-2/-3, UN M.49, ISO15927)?

**Comment by marcoscaceres** [comment]
Removed the offending text
