### ISSUE TITLE
Status section has misleading info on filing bugs

### ISSUE THREAD

**Issue by chaals** [w3c/manifest#489]
The Status of the Document section suggests that comments should be sent to the mailing list.

This might actually be caused by a respec issue.

**Comment by marcoscaceres** [comment]
Indeed, need to fix this in ReSpec: https://github.com/w3c/respec/issues/919

**Comment by kenchris** [comment]
Something was merged there, so can we close?

**Comment by RobDolinMS** [comment]
Both the information at the top of the document and the "Status of This Document" section link to the GitHub issues: https://github.com/w3c/manifest/issues.  

I believe this is now resolved.  /cc @chaals
