### ISSUE TITLE
Drop gh-pages branch

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#492]
As we are using echidna, we don't need to be publishing gh-pages.

**Comment by patrickkettner** [comment]
is there anything to be done other than delete the branch?

**Comment by marcoscaceres** [comment]
The branch will have to live on, but with a HTML document that has an ol' school `<meta refresh>` for redirect (to avoid a 404).  There are lots of articles, etc. pointing to the current gh-pages' served page.

**Comment by patrickkettner** [comment]
ah - gotcha

**Comment by marcoscaceres** [comment]
We just need to copy/pasta/adapt this:
https://github.com/w3c/reporting/blob/gh-pages/index.html

**Comment by patrickkettner** [comment]
happy to PR a change, but I am not sure what the Echidna powered url would be

**Comment by marcoscaceres** [comment]
That would be great. The URL is:
https://www.w3.org/TR/appmanifest/

I've given you write access on this repo, so if you can create a feature branch that would be great; then we can rebase/merge on gh-pages once the 2 existing PRs land.
