### ISSUE TITLE
Standalone description not accurate

### ISSUE THREAD

**Issue by owencm** [w3c/manifest#495]
Currently our description of display:standalone says:
"In this mode, the user agent will exclude UI elements for controlling navigation, but can include other UI elements such as a status bar."

In fact, on all browsers I'm aware of on Android the UI for controlling navigation is just system UI that isn't obscured. Hence it may be clearer to say:

"In this mode, the user agent will exclude standard browser UI elements such as an URL bar, but can include other system UI elements such as a status bar or system back button."

**Comment by marcoscaceres** [comment]
@owencm, the original description was designed to match what Safari did in iOS. However, I'm happy to change it.
