### ISSUE TITLE
Describe how developers can block web crawlers

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#498]
There may be a case where a web app developer does not want their web app to be crawled.  I was thinking proposing an additional element to support this, but realized the web already has a way to block crawlers.  

Below is some draft language, if this seems reasonable, please 👍 and I'll submit a PR.

> Like other web resources, a web app manifest should be accessible to any web browser or web crawler.
>  
> If a web app developer wants to block traffic from web crawlers, the developer MAY do so by including the web app manifest in a robots.txt file.  This is further described in the [robots.txt](http://www.robotstxt.org/) protocol.

**Comment by marcoscaceres** [comment]
I'm respectfully not in favor of adding this to the spec, primarily because robots.txt is well-known and doesn't add normative text the spec. 

I'm wondering, however, if we should actually start an explainer.md for web manifest, where this kind of information can go. That would give us freedom to provide guidance to developers, while keeping the spec lean of non-normative text.

**Comment by patrickkettner** [comment]
Personally, I would be in favor of adding this to the Manifest. My use case
would be as a former web hosting Company employee comma people had access
to upload files, but not necessarily modify their robots.txt. this happened
with resellers and subdomains. You could easily imagine code sites like
CodePen, jsbin, or even just old fashioned college websites offering folks
the ability to add files on an HTTPS domain, without giving them access to
robots.txt. while I agree that the robots is the way to go for a vast
majority of the internet, I would really like to have this escape hatch in
the Manifest

**Comment by RobDolinMS** [comment]
(Discussing @marcoscaceres's proposal of including this concept in some separate appendix/explainer with @patrickkettner offline)

**Comment by alrra** [comment]
> If a web app developer wants to block traffic from web crawlers, the developer MAY do so by including the web app manifest in a robots.txt file. 

Note: One can also use the [`X-Robots-Tag`](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag#using-the-x-robots-tag-http-header) HTTP header.

**Comment by marcoscaceres** [comment]
/me removes Editor hat, puts on Mozilla hat...

From Gecko implementation standpoint, I wouldn't be in favor of adding anything like this to the spec. At least, I don't feel it would be something we would want to implementation. 

/me puts on Editor hat. However, if another implementer wanted this, then happy to add it.

**Comment by patrickkettner** [comment]
@marcoscaceres - for clarity, what is the anything that you are referring to?

**Comment by marcoscaceres** [comment]
@patrickkettner, any new member that would serve as a robots.txt equivalent.

**Comment by patrickkettner** [comment]
ah, ok. wasnt sure if that was in response to catalin or something that happened in the other part of the thread. thanks! :]

**Comment by nolanlawson** [comment]
So the consensus is not to add the robots.txt fix to the spec, but instead to an explainer?

BTW I sympathize with @patrickkettner's POV but I imagine most web authors will work around this by just not hosting their PWAs on Geocities. :wink: Also may not be so bad that admins of JSBin/Codepen/etc. can unilaterally disallow PWAs on their sites by robots.txt-blocking all manifest files.

**Comment by patrickkettner** [comment]
>  Also may not be so bad that admins of JSBin/Codepen/etc. can unilaterally disallow PWAs on their sites by robots.txt-blocking all manifest files.

What? Why would that be a good thing?

**Comment by nolanlawson** [comment]
Dunno, thinking back to [Remy Sharp's security issues with JSBin](https://remysharp.com/2015/09/14/jsbin-toxic-part-1) seems not so bad to give more power to the admin...

**Comment by patrickkettner** [comment]
I don't think anyone is suggesting _not_ supporting robots.txt. site owners should, and always will, have the ability to blanket blacklist PWAs. But they also have the power to choose to offer the service. If Remy, Chris, or any other hosting team wants to offer PWAs as a possibility, they shouldn't be hamstrung by the w3c making decisions for them.

By not offering a way for users to opt out of this, you are not giving power to these sites - you are taking it away.

**Comment by nolanlawson** [comment]
My bad, thanks for the explanation. :+1:

**Comment by RobDolinMS** [comment]
This is addressed by #505
