### ISSUE TITLE
Combine Origin Policy mechanism with the Web App Manifest?

### ISSUE THREAD

**Issue by anssiko** [w3c/manifest#500]
As discussed at [Origin Isolation/Browsing Context Isolation breakout](https://www.w3.org/2016/09/21-isolation-minutes.html) F2F today with @mikewest et al., it _might_ make sense to combine Origin Policy mechanism with the Web App Manifest.

See also [Relation to Web App Manifests](https://mikewest.github.io/origin-policy/#app-manifest).

**Comment by christianliebel** [comment]
@anssiko @mikewest Origin Policy doesn’t seem to have made any progress in the past 2.5 years—is this still relevant?

**Comment by aarongustafson** [comment]
A site’s manifest, though declared early, is not downloaded or parsed early enough in the page rendering process to make such instructions available in the same way that a header would. There’s bound to be a better solution that would not involve the manifest.
