### ISSUE TITLE
(Re-)Add Optional Splash Screens

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#501]
This issue proposes resurrecting the `splash_screens` object that was removed with PR #440 

While UAs can fall-back to using one of the smaller images and a background color, offering the optional `splash screens` object gives web app developers an option to have the UA display a larger, more detailed image while their app loads.  

(Example from [prior spec version](http://www.w3.org/TR/2015/WD-appmanifest-20151124/))
```
  "splash_screens": [{
        "src": "splash/lowres",
        "sizes": "320x240"
      }, {
        "src": "splash/hd_small",
        "sizes": "1334x750"
      }, {
        "src": "splash/hd_hi",
        "sizes": "1920x1080",
        "density": 3
      }],

```

**Comment by RobDolinMS** [comment]
Discussing with @boyofgreen and may want to get this from `icons` object.  Closing for now.

**Comment by benfredwells** [comment]
Interesting that this just came up. We (Chrome) have been discussing this. We currently get something from `icons`, but would like to do something better.

We are tossing up two options - having some way of specifying splash screen images like this proposal, or having a splash screen url declared. With the url method the site could generate a page and the browser would probably grab a snapshot of it.

Any comments on either approach?

**Comment by benfrancis** [comment]
Only that this has been discussed at great length before. See #9  and also #361, #372, #373 and #390.

I would personally recommend sticking with the icon and background colour.

**Comment by marcoscaceres** [comment]
If need be, please reopen #9 to discuss further.
