### ISSUE TITLE
Rename "install" event to "appinstalled" to avoid SW event name clash

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#502]
The Web App Manifest spec defines an event type [`"install"`](https://www.w3.org/TR/appmanifest/#oninstall-attribute) which is fired at the *window* object. The Service Workers spec defines an event type [`"install"`](https://www.w3.org/TR/service-workers/#service-worker-global-scope-install-event) which is fired at the `ServiceWorkerGlobalScope` object.

While these do not directly conflict (as they are fired at different objects), there is potential for confusion (for both web developers and browser developers). As one anecdote, in Chromium, the event objects for these two types of event are indistinguishable, so we have to take context into account (e.g., when logging the relative usage of these two features) to avoid conflating the two event types.

Since the concept of "installing" a service worker and "installing" a web app are totally unrelated, perhaps it is worth renaming this event to something different. Suggestions: `"register"`, `"installapp"`.

**Comment by marcoscaceres** [comment]
Good point. I'd be happy with "installapp" or "appinstalled" - "ed" because it's fired **after** the application has installed.

**Comment by mgiuca** [comment]
If we decide to change it, what would be the process? (This is already implemented on Firefox isn't it?)

Having the "ed" suffix seems reasonable; in that case could we just have `"installed"`, or is that too confusing with SW? In that case, `"appinstalled"` seems like the best.

**Comment by marcoscaceres** [comment]
> If we decide to change it, what would be the process? 

We just prepare a PR. Basically just do a find/replace for the event name :)

> (This is already implemented on Firefox isn't it?)

It's pref'ed off right now, so no big deal... will take me a few minutes to update the Firefox implementation and associated tests.

> Having the "ed" suffix seems reasonable; in that case could we just have "installed", or is that too confusing with SW? In that case, "appinstalled" seems like the best.

It's still too close to SW, I think. Let's got with "appinstalled". I'll do that now.

**Comment by marcoscaceres** [comment]
Sent rename patch for review: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1309099 

Expect it to land in a week or so.
