### ISSUE TITLE
Add Optional Opt-In for UA Default Transition

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#504]
This issue proposes adding an optional opt-in for a web app to request a UA show a default transition.  Something like:
`"transition_fallback": "auto";`

And the default (if no object is specified) would be equivalent to: 
`"transition_fallback": "none";`

Many web apps will either not need transitions or will write their own code to handle transitions.

However, some web apps (which may start from progressively enhancing existing web pages) may not have code to handle transitions and may want some native-like fallback transition UX.  

FAQ
**Q: Who is this for?**
A: Web app authors who may want to do minimal initial work to convert a legacy website into a web app but still get as much of a native-like experience as possible.

**Q: What might an "auto" transition look like?**
A: If a page render had not completed after a user-perceptible amount of time, (ex: 1 second), the UA might show a transparent overlay and some UX widget like a spinner, loading bar, hourglass, watch, etc.

**Q: Do all UAs need to support having a default transition?**
A: No, many UAs may not do anything (and web app authors should expect this.)

**Q: Will this break any existing web apps (and web app manifests)?**
A: No, this is an optional, opt-in feature.

**Q: Will this require any additional work from web app (and web app manifest) authors?**
A: No, this is an optional, opt-in feature.

**Q: Does link rel="prerender" solve this?**
A: Prerender works great if the navigation is linear, but in a number of cases, navigation is non-linear:
- A game in which a user can visit one of multiple "neighbors"
- A game in which a user can choose to play one of multiple unlocked levels
- A social experience in which a user can navigate to one of multiple "friends"
- A financial app in which a user can check the performance of one of multiple stocks/funds/etc.

**Q: Would any additional values beside "auto" (and "none") be allowed?**
A: No, not for now, this could be expanded in the future, but the intent is that this gives web app authors a way to request a platform default transition until they have time / resources to write their own transition code.

**Comment by marcoscaceres** [comment]
@RobDolinMS, maybe just "auto" and "none" as the options ("none" being the default) - and "auto" being "let the UA choose based on what the platform provides".  

I'd still like @mounirlamouri or @jakearchibald or someone from Google to chime in here as it requires OS integration... and I'm not sure Android currently supports this? (maybe it does, dunno?). Also, in #478 we discussed  using CSS for this - as a more general solution that could benefit all web apps, without relying on Web Manifest.  

Ideally, I'd like to see two implementers willing to support this before we add it.

**Comment by benfredwells** [comment]
I assume 'platform' in this case is the browser itself not the OS. I.e. Chrome on windows would have to code up the transition, there wouldn't be anything we could get from windows to do it for us. Similarly Chrome on Android would also need to have code for the transition as the OS wouldn't provide anything.

Maybe others at Google will disagree but this isn't something I'm interesting in adding to Chrome.

**Comment by marcoscaceres** [comment]
I have to concur with @benfredwells; this is also not something we would add to Firefox at this point (though I think we all strongly support the problem of page transitions this is trying to solve). 

@RobDolinMS, I'd suggest "ms_" prefixing this initially in a Microsoft implementation while we work towards addressing this more generally in CSS.

**Comment by RobDolinMS** [comment]
Updated proposal at top to match @marcoscaceres's suggestion of "auto" and "none" (with "none" being the default)

**Comment by marcoscaceres** [comment]
@RobDolinMS see @jakearchibald's proposal:
https://github.com/jakearchibald/navigation-transitions/blob/master/README.md

Looks like it could address this use case really nicely!

**Comment by RobDolinMS** [comment]
Thanks @marcoscaceres.  @jakearchibald's [Navigation Transitions proposal](https://github.com/jakearchibald/navigation-transitions/blob/master/README.md) looks really cool, but I'm not sure it solves the problem that me and colleagues are trying to address.  

Situation: Developer wants to have a minimum viable product (MVP) PWA by adding a web app manifest to an existing website that scales with screen size.  

User Experience: When an end-user of this MVP PWA on a slow Internet connection clicks/taps a link to navigate, it can take some time for the next page to load.  Waiting multiple seconds with no visible indication of progress in the UX may cause the end-user to think the app has hung and exit the app.  :(

Solution for MVP PWA Developer: Enable the developer who just wants a MVP PWA to indicate with one line in the Manifest that they want the web browser to provide some default "transition" like chaser dots, an hourglass, etc. (if it is available.)

MVP PWA -> Better PWA: Once the developer of MVP PWA starts getting users of their PWA app, they will hopefully invest in improved "transitions" and/or improved offline / slow Internet experiences.

**Comment by kenchris** [comment]
This sounds a bit like a temporary features and something that will go away with time. Maybe it should be a vendor specific extension for the time being? Chaser dots, hour glass already sounds very platform specific

**Comment by RobDolinMS** [comment]
After discussing with multiple stakeholders, we can do this via an extension.
