### ISSUE TITLE
Bikeshedding: should 'purpose' be named 'kind'?

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/manifest#509]
I understand that `type` is already used for images but `purpose` is a very odd name. `kind` is used in some places in the HTML specification. Would that make more sense?

**Comment by kenchris** [comment]
kind if more like explaining what it is instead of what it is intended for. At least that is how I feel.

**Comment by marcoscaceres** [comment]
I wanted to use "role", but a11y already own that... "purpose" was the closest synonym I could think of.

**Comment by marcoscaceres** [comment]
Influence by: https://www.youtube.com/watch?v=wqzLoXjFT34

**Comment by mounirlamouri** [comment]
@marcoscaceres feel free to close this if you think it's not worth discussing more.

**Comment by RobDolinMS** [comment]
I'm (personally) OK with "purpose."  

If it's worth debating more, I have a weekly sync with other folks working on Edge and could ask for additional opinions.

**Comment by RobDolinMS** [comment]
@marcoscaceres Would you want to close this issue?
