### ISSUE TITLE
Should the spec include a link to the Explainer?

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#512]
Could be as simple as a link near the end of the spec to: http://w3c.github.io/manifest/explainer.md

If others think this is a good idea, I'm glad to draft a PR.

**Comment by mgiuca** [comment]
I don't see the point, especially since it's a very minimal explainer. I think the explainer serves as a starting off point for making a spec; it shouldn't be part of the final product. If there is non-normative explanation of why things are done like this, those comments should be transferred into the intro section of the spec (but I think there is enough motivation there already).

**Comment by alrra** [comment]
> Could be as simple as a link near the end of the spec to: http://w3c.github.io/manifest/explainer.md

Directly linking to the [`explainer.md`](http://w3c.github.io/manifest/explainer.md) file is not a good idea ([Edge](https://cloud.githubusercontent.com/assets/1223565/19718186/e839cbb8-9b6c-11e6-9bc9-477429988a85.png) / [Firefox](https://cloud.githubusercontent.com/assets/1223565/19717283/80cc6ffc-9b68-11e6-80d6-a7a7c27c5804.png) will prompt to download it, while Chrome / Opera / Safari will just display its raw content). 

If a decision is made to link to the explainer, I think it should be to either [its associated GitHub page](https://github.com/w3c/manifest/blob/12691c228e8547d5796411524d2d8a320e6faade/explainer.md), or better yet, it should be converted to an HTML page, and linked to that.

**Comment by marcoscaceres** [comment]
I tend to agree with @mgiuca that we should not link to it from the spec. The spec will likely hang around for a decade or more, and by then we will probably have long moved onto some new collaboration platform (sorry Github, still ❤️you.. but reality).

**Comment by kenchris** [comment]
Can we close?

**Comment by RobDolinMS** [comment]
Thanks all.  I understand not linking from the Spec to the Explainer.

There is at least one thing in the explainer that I might want to move into spec.  I'll open a new issue and/or PR for this.
