### ISSUE TITLE
Processing the purpose member should return the same value in both error conditions

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/manifest#513]
Maybe that was on purpose (no pun intended) but it sounds fairly odd that `purpose` parsing will return `undefined` when the value isn't a string but a set with `"any"` if the value is a string but doesn't contain a known value.

I would suggest to do something similar to `icons` where the same value (empty array) is returned regardless of the type of errors. Here, we could return an empty set.

(As a side note, is space separated keywords more common in JSON than comma separated? HTML uses comma separated most of the time, doesn't it?)

CC @marcoscaceres

**Comment by marcoscaceres** [comment]
Yeah, looks like I made a copy/pasta error there. Will fix.

**Comment by mounirlamouri** [comment]
I'm happy to fix this. Do you have a preference on what the fix should look like?

**Comment by marcoscaceres** [comment]
Should default to "any" when error or missing.
