### ISSUE TITLE
Should appinstalled / beforeinstallprompt fire on native app installation?

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#514]
Bit of a thorny issue that came up while implementing `appinstalled` in Chrome.

Background:

* Chrome's implementation of the `beforeinstallprompt` event (currently being specced in #506) fires the event whenever the web app *or* related app install banner is to be shown.
* The `BeforeInstallPromptEvent` object includes a `platforms` field, which lists the platform that the app is being installed for (I'm not sure why, but it is an array that always contains exactly one element). This could be "web" for the web app, "play" for Google Play (Android) app, etc.
* We decided to punt on including this in the spec, since it is a somewhat Chrome-specific detail.
* The manifest spec includes `related_applications` which lists, for example, Android or iOS equivalents to a web app. But the spec treats these as incidental metadata, and doesn't mention any specific interaction between `related_applications` and app installation events.
* Specifically, the `appinstalled` event, which is already in the spec, is supposed to be fired by **steps to install the web application** (and not when a native application is installed).

So the issue for us is that we already have `beforeinstallprompt` firing when a native app banner is shown (despite the current draft language not permitting this), and when I implement `appinstalled`, I have to choose between firing the event on native app installation (despite the spec not permitting this) or not (which would be inconsistent with our implementation `beforeinstallprompt`). I'd prefer to keep consistency, so maybe we should add a provision that installing a related application may fire `beforeinstallprompt` (when the banner is shown), and that it may fire `appinstalled` when it becomes installed. The proposed changes would be (assuming the current `beforeinstallprompt` draft):

1. Explicitly note steps to notify before installing, and steps to install, a related application, the process of which is triggered at the user-agent's discretion.
2. State that `beforeinstallprompt` is to be fired before notifying the installation of a related application.
3. State that `appinstalled` is to be fired after installation of a related application.
4. Add a `platforms` member to `BeforeInstallPromptEvent`.
5. Add `AppInstalledEvent` interface and change `appinstalled` to be that instead of `Event`.
6. Add a `platforms` member to `AppInstalledEvent`.

(Note: 2 and 3 imply 4, 5 and 6, because if we fire it on related app install, we need to tell the site that it isn't a web app install.)

If we can't change the spec, we would probably honour that in Chrome for `appinstalled`, but I doubt we can remove this from `beforeinstallprompt` (since I think this was the main use case for which we added `beforeinstallprompt` in the first place). So we'd likely just remain diverged, as well as `appinstalled` behaving inconsistently with `beforeinstallprompt`. So I'd like to discuss and hopefully change the spec. @marcoscaceres ?

**Comment by mgiuca** [comment]
@dominickng @mounirlamouri

**Comment by marcoscaceres** [comment]
> So the issue for us is that we already have beforeinstallprompt firing when a native app banner is shown (despite the current draft language not permitting this), and when I implement appinstalled, I have to choose between firing the event on native app installation (despite the spec not permitting this) or not (which would be inconsistent with our implementation beforeinstallprompt). 

So, the spec doesn't consider the scenario you mention above ... it's undefined behavior. What you are describing makes sense tho. 

>  I'd prefer to keep consistency, so maybe we should add a provision that installing a related application may fire beforeinstallprompt (when the banner is shown), and that it may fire appinstalled when it becomes installed.

This worries me, because it might mean that Firefox, as a regular app, won't ever be able to support this (I would imagine this would require special privileges - but maybe not?). 

> Add a platforms member to BeforeInstallPromptEvent.

We can add it to the UserResponseObject. It would be null when userChoice is "dismissed". 

So:

```  
ev.prompt().then(obj => obj.platform);
``

Also, as you mentioned, be good to get a valid reason for it being an array. 

> 5. Add AppInstalledEvent interface and change appinstalled to be that instead of Event.
> 6. Add a platforms member to AppInstalledEvent.

I'll be honest... this is gonna be really controversial for the reasons I mentioned above :( Let me run this by a few people internally...

**Comment by mgiuca** [comment]
Yeah I thought it might be controversial.

Don't know why it's an array. I'll ask Dom tomorrow.

> We can add it to the UserResponseObject. It would be null when userChoice is "dismissed".

That's not ideal because it means you can't make a policy decision on whether to preventDefault based on the platform (since you only find out the platform after you prompt).

**Comment by marcoscaceres** [comment]
> That's not ideal because it means you can't make a policy decision on whether to preventDefault based on the platform (since you only find out the platform after you prompt).

Ah, I was imagining a drop-down where you would be able to choose either "Web" or "Play Store". 

What this is basically enabling is:

```JS
addEventListener("beforeinstallprompt", async (ev) => {
    ev.preventDefault();
   if (!ev.platform.includes("Play")) {
       return; // Never install for the Web or other platform! <evil laugh>.
   }
   await stuff;
   ev.prompt();
});
```

Is this really where we want to go? 😢 

Basically, if `related_applications` doesn't include "web" and `prefer_related_applications` is true, then would it not disqualify it as a "progressive web app"?

**Comment by mgiuca** [comment]
@dominickng and I just had a chat about this. I think that behaviour would be bad but it's not something we can, or should, be specifically trying to stop. You can already prevent web app installation in favour of an Android app in Chrome (by e.g., not having a service worker but having a Play app in `related_applications`). So your example of the "evil" behaviour is already possible, and we aren't enabling further evil behaviour.

As I put it to Dom, "we aren't the PWA police, just the ticket inspectors." The PWA install banner is a carrot to encourage people to make a PWA. I don't think we should be worried about PWA authors not showing the web app install banner. The web app install banner is the reward for being a PWA, not the other way around.

> Basically, if related_applications doesn't include "web" and prefer_related_applications is true, then would it not disqualify it as a "progressive web app"?

Yes, that would disqualify it as a PWA.

**Comment by marcoscaceres** [comment]
> So your example of the "evil" behaviour is already possible, and we aren't enabling further evil behaviour.

True.

> As I put it to Dom, "we aren't the PWA police, just the ticket inspectors." The PWA install banner is a carrot to encourage people to make a PWA. I don't think we should be worried about PWA authors not showing the web app install banner. The web app install banner is the reward for being a PWA, not the other way around.

Ok, so two question still remain: 

1. Implementability: if a browser like Firefox wanted to support this, does Android expose such APIs whereby we can get the callback after referring the installation of a native app from the Play Store? 
1. Support from other browser vendors: @RobDolinMS or @boyofgreen, would this be something Microsoft would be interested in?

**Comment by dominickng** [comment]
> Ok, so two question still remain:
> 
> Implementability: if a browser like Firefox wanted to support this, does Android expose such APIs whereby we can get the callback after referring the installation of a native app from the Play Store?

I believe this is a first-party API on Android at the moment, and I'm not sure how likely it would be open it further. That's definitely a challenge here.

**Comment by mgiuca** [comment]
If that's the case then that's unfortunate. But it shouldn't change the intent behind this. I'd be concerned if we were discussing a feature that _can't be_ implemented without magic powers on Android (e.g. an "installPlayApp" API), but this is mostly informational -- we're delivering a message to the app to tell it: we're going to install the Android app, would you like to proceed with this? If a User Agent can't implement Android app installation, it simply will always set `platform` to `["web"]`.

And this is not an Android-specific API. It can be used to inform the site about installation of a related application on any platform.

**Comment by RobDolinMS** [comment]
Responding to: 
>Support from other browser vendors: @RobDolinMS or @boyofgreen, would this be something Microsoft would be interested in? 
I'll send an email thread with other Microsoft/Edge folks on this question including (@BoyOfGreen, @Seksenov, et. al.) and comment back on this issue soon.

**Comment by boyofgreen** [comment]
I don't see this being a problem for Microsoft/Edge as we  control both the store and the browser (much like the situation on chrome / android).  We always want to encourage apps so we would likely take advantage of this.  However I would agree with @marcoscaceres that this may disadvantage other browsers on our platforms.

**Comment by marcoscaceres** [comment]
I'm told that we (Mozilla) have, in the past, put in place contracts to access privileged APIs with OS vendors. Given that, it might be possible for us to put this in the spec and let the business folks sort out API access down the line.

**Comment by delapuente** [comment]
>  We always want to encourage apps so we would likely take advantage of this.

Folks, I truly understand your motivations regarding your specific platforms but this does not make the Web platform more competitive. On the contrary, you are including it to benefit native apps and you know it:

> I believe this is a first-party API on Android at the moment, and I'm not sure how likely it would be open it further. That's definitely a challenge here.



> However I would agree with @marcoscaceres that this may disadvantage other browsers on our platforms.

I think delegating in the _business folks_ is an error. That prevents emerging / future browsers to access the same capabilities in the Web platform.

**Comment by mgiuca** [comment]
This is certainly a concern, thanks for raising it.

However, really we're not talking about adding any new capabilities to the web to enhance native apps. We're just talking about notifying websites when their corresponding native app is installed, so that they can understand how users are using their different apps and also control the experience to avoid duplicating UI work (e.g., not showing an app install banner if the user has already installed their native app).

We don't like it when sites show native app install banners, so even though this may seem contrary to that mission, helping sites manage their native app integration from their website is the best way we have of reducing that spam. There are real websites asking for these capabilities and if we don't provide them, they are just going to go off and do their own thing anyway.

I wonder if we can make some progress on this as I am landing the `appinstalled` event in Chrome and it would be good to come to a decision about this (we need to add a `platform` attribute to the `appinstalled` event).

**Comment by delapuente** [comment]
What about providing an API to ask if one of the `related_applications` is already installed?

**Comment by mgiuca** [comment]
We are working on that too ([`getInstalledRelatedApps`](https://github.com/WICG/get-installed-related-apps)), but I think it also makes sense to have these come up as events when they are installed.

**Comment by seanlinsley** [comment]
did this ever get resolved?

**Comment by seanlinsley** [comment]
this doesn't seem to work currently (Chrome Canary on Android)

```js
    window.addEventListener('beforeinstallprompt', function(e) {
      e.preventDefault();
      return false;
    });
```

**Comment by dominickng** [comment]
@seanlinsley that isn't what this issue is talking about.

`beforeinstallprompt` is used to access the modal A2HS UI. We currently show a mini-infobar on Android that isn't controlled by `beforeinstallprompt`, and have plans for removing the mini-infobar with a UI refresh in the near future.

**Comment by seanlinsley** [comment]
I don't know what the difference is between add-to-homescreen, and the mini-infobar you describe.

I posted here b/c I couldn't find a better place. FWIW this issue appeared to be similar b/c of the reference to `beforeinstallprompt`, and our common need to keep people from being prompted to install from within a native app.

This all seems to be awfully under-documented, at least from an official source. Maybe y'all could update [this document](https://github.com/deanhume/pwa-tips-tricks/blob/master/README.md#the-add-to-homescreen-banner-doesnt-make-sense-for-my-website-how-do-i-disable-this-functionality-i-want-to-hide-it) as things change?

**Comment by tomayac** [comment]
Some more background on the interim solution named [mini-infobar](https://developers.google.com/web/fundamentals/app-install-banners/#the_mini-info_bar). There is currently no way to suppress it, as it’s just a temporary way to facilitate the behavior change described in the linked article.

**Comment by marcoscaceres** [comment]
Closing because of #836. Also seems ok to close given @dominickng's comment in https://github.com/w3c/manifest/issues/514#issuecomment-440925911
