### ISSUE TITLE
Proposal: Add Optional Member for IARC Rating

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#523]
It may be useful for web apps to be able to optionally indicate their [IARC](https://www.globalratings.com/) rating.  I'm thinking this may be as simple as: 

`"iarc_rating": "opaque_string",`

App stores participating in IARC include the Google Play Store, Windows Store, and Nintendo Store.

Locales covered by IARC include: Australia, Brazil, Germany, Europe (PEGI), and North America (ESRB)

For more on IARC:
* https://www.globalratings.com/intro-to-iarc-en.aspx
* https://www.globalratings.com/for-developers.aspx

**Comment by marcoscaceres** [comment]
This is a good suggestion, specially if stores are going to use it. @RobDolinMS, do you know if there is some way to verify the claim that the "iarc_rating" makes? Does IARC provide some means for the store to verify it (e.g., a token or something)?

**Comment by mounirlamouri** [comment]
Why should the string be opaque?

**Comment by marcoscaceres** [comment]
@RobDolinMS, I'm having trouble with the Global Ratings site... I can't seem to find the information about what their process is going to spit out. Is there a way of actually getting a listing of the ratings that can be produced? That would allow us to better understand the requirements for this member.

**Comment by RobDolinMS** [comment]
@marcoscaceres I have accounts with the Apple, Google, and Microsoft app stores.  I'll try to work through the flows and dig into this soon.  This should also enable me to answer @mounirlamouri's question about why the string might be opaque.

**Comment by RobDolinMS** [comment]
Responding to @mounirlamouri's question:
>Why should the string be opaque?

My understanding is that there are a number of different ratings systems (see: "Rating authorities & descriptions" in https://support.google.com/googleplay/android-developer/answer/188189.)  I THINK that IARC provides an opaque identifier for the app in the IARC system rather than a specific rating value (or array of rating values)

Such a model would also address Marcos's question:
>Does IARC provide some means for the store to verify it (e.g., a token or something)?

I'm waiting for an app submission to go through so I can confirm the above.

**Comment by delapuente** [comment]
> My understanding is that there are a number of different ratings systems 

If there are more than one, it would be better to include a `rating` key as an array of objects specifying rating system and string and make it extensible.

**Comment by kenchris** [comment]
Some info here: https://support.google.com/googleplay/android-developer/answer/188189?hl=en

IARC currently seems to go through the store system, ie when you submit your app, you request a rating and fill out a questionnaire. Then the store can show it as unrated (or use the rating you suggested as Google Play will do), then later replacing with the proper localized rating. 

It seems to be hard to have something in the manifest as it seems that IARC can reclassify at any point and even the store can refuse an update if it seems to require reclassification.

There are lots of different rating systems:

* Pan	European	Game	Information	(PEGI)	– Europe
• Unterhaltungssoftware	Selbstkontrolle	(USK)	– Germany
• Entertainment	Software	Rating	Board	(ESRB)	– North	America
• Classificação	Indicativa	(ClassInd)	– Brazil
• Classification	Board	- Australia
* IARC Generic ratings: https://www.globalratings.com/ratings-guide.aspx

**Comment by RobDolinMS** [comment]
Resurfacing the original proposal:

`"iarc_rating": "opaque_string",`

When a developer submits their app to one of the stores, they fill-out a questionnaire as @kenchris  mentions.  The developer gets an opaque string that references the rating results calculated from their answers to the questions in the questionnaire.  If a developer wants to submit their app to another store, the developer can just share the opaque string that they received from the first store and not have to fill-out the questionnaire again.

My intent in proposing an `iarc_rating` member is for the developer to be able to communicate that they have completed the questionnaire and the opaque string is a reference to the results of the developer completing the questionnaire.  

You can imagine a scenario where a tool like [PWA Builder](http://www.pwabuilder.com/generator) could help a developer complete the IARC questionnaire and then the `iarc_rating` member would be a place in the Manifest to store the results of the developer completing that questionnaire so the developer could submit their PWA to [various stores](https://www.globalratings.com/about.aspx#participants) without having to complete the IARC questionnaire for each store.

**Comment by kenchris** [comment]
OK, sounds great! I am fine with us adding this and will review any PR doing that :-) 

Maybe use iarc_rating_id ?

**Comment by marcoscaceres** [comment]
Given the different kinds, wouldn't we then want:

"ratings": [{kind, value},...]

**Comment by kenchris** [comment]
No :-) because then no one can trust that anyway, I can write that my app is rated for age 3 and it is not.

The id links to the IARC database (or similar) and can be updated and adjusted by the IARC member groups from time to time, plus verified that it actually applies to that URL/app

**Comment by marcoscaceres** [comment]
ah, got it.

**Comment by delapuente** [comment]
Is IARC rating aggregating somehow the information from other rating systems?

**Comment by kenchris** [comment]
The other way around basically. Different eating systems joined together to create IARC, and their ratings can be derived from IARC rating

**Comment by kenchris** [comment]
Rating not eating
