### ISSUE TITLE
Update references to W3C if available

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#526]
When reviewing #520, I noticed it includes a reference on line 3030 / 3148 to:
`https://dom.spec.whatwg.org/#concept-event-fire`

I suggest we update this to the equivalent in the W3C spec: 
`http://www.w3.org/TR/domcore/#firing-events`

**Comment by marcoscaceres** [comment]
Unfortunately, we can't reference W3C DOM because it's obsolete :( There is new behavior and security assurances (related to things being in the correct JS realm, etc.) in the WHATWG DOM spec that we rely on.

**Comment by chaals** [comment]
Please make sure that issues are filed on those at https://github.com/w3c/dom

**Comment by RobDolinMS** [comment]
Thanks @chaals.  Issue is now opened: https://github.com/w3c/dom/issues/10
