### ISSUE TITLE
Add info push notifications to extensions registry

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#529]
BACKGROUND
Looking for manifest files of popular websites, I noticed [quora.com's manifest](https://qsf.ec.quoracdn.net/-jsons.desktop_push_manifest.jsoncc40e313a4597c57.json) includes the following:
``` json
{
  "name": "Desktop Push Notifications",
  "gcm_sender_id": "602221294976"
}
```

I suspect gcm_sender_id may be a vendor-specific extension possibly documented at: https://developers.google.com/cloud-messaging/chrome/client

If that is the case, I recommend we document it in the Web App Manifest spec's Extensions Registry at: https://github.com/w3c/manifest/wiki/Extensions-Registry

/cc @mounirlamouri who may know more here

**Comment by patrickkettner** [comment]
That is the old chrome specific field for push notifications that is deprecated for standards based push (https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web)

**Comment by marcoscaceres** [comment]
@dret, do you want to document this one as deprecated/historical in the wiki?

**Comment by RobDolinMS** [comment]
@marcoscaceres It looks like @dret works for CA Technologies.  Did you possibly mean to assign this to someone from Google or has @dret been taking point on documenting extensions?

**Comment by dret** [comment]
i am indeed the one who should be doing this. still in my overflowing inbox. stay tuned!

**Comment by dret** [comment]
seems like i cannot assign this issue to myself. is that a lack of repo access rights or is the repo set up so that it does not support assignments? if the former, could somebody with sufficient powers please assign this issue to me? thanks!

**Comment by marcoscaceres** [comment]
Sorry, my bad! Will send you an invite to the repo.

**Comment by marcoscaceres** [comment]
Sent. Rob, also sent you an invite so we can assign you to things.

**Comment by dret** [comment]
On 2016-11-30 17:45, Marcos Cáceres wrote:
> Sorry, my bad! Will send you an invite to the repo.

thanks, now assigning the issue worked.

**Comment by RobDolinMS** [comment]
@dret Anything I can do to help here?

**Comment by RobDolinMS** [comment]
I've added `gcm_sender_id` to the [Extensions Registry](https://github.com/w3c/manifest/wiki/Extensions-Registry) wiki page
