### ISSUE TITLE
Minor typo in explainer.md

### ISSUE THREAD

**Issue by newschapmj1** [w3c/manifest#531]
Interaction with Web _Cralwers_

**Comment by RobDolinMS** [comment]
Thanks @newschapmj1.  PR #532 should fix this.  

If you agree, please close.

**Comment by RobDolinMS** [comment]
Since PR #532 has now been merged, I'm closing this issue.  

Thanks for raising this @newschapmj1.  If the PR does not resolve, please re-open the issue.
