### ISSUE TITLE
The list of known Web Manifest platform values is confusing

### ISSUE THREAD

**Issue by pkotwicz** [w3c/manifest#538]
The list of known Web Manifest platform values is confusing. https://github.com/w3c/manifest/wiki/Platforms list only "play"

https://www.w3.org/TR/appmanifest/#purpose-member uses an example with platform="android"
https://www.w3.org/TR/appmanifest/#dfn-application-object uses an example with platform="play"

I suggest having two separate lists of platform values one for the "Image Object" and one for the "Application Object"

There is some discussion on this topic in https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/purpose%7Csort:relevance/blink-dev/1ebMBNhqRew/_6hAQKAfBwAJ

Thanks to Rick Byers for noticing the spec inconsistency!

**Comment by RByers** [comment]
Note that this is intentionally NOT part of the spec - it's implementation defined with the WG maintaining a wiki that implementors can just update to reflect the status of their implementation.  I suggest you just edit the wiki to say whatever you think best reflects your implementation in Chrome Android :-)

**Comment by RByers** [comment]
Oh but yeah the spec examples should probably be consistent with real implementations too :-)

**Comment by pkotwicz** [comment]
I suggest clarifying the green Note in https://www.w3.org/TR/appmanifest/#platform-member or the https://github.com/w3c/manifest/wiki/Platforms page to clearly state that the supported platforms for the "Image Object" and the "Application Object" are different

Current state of Chrome for Android:
Application Object -> Only "play" platform is supported
Image Object -> platform attribute ignored (no platforms are supported)

I believe that the platform member for the application object was added by the Mozilla folks so I suspect that Firefox supports "android" as a platform for the Image object https://github.com/w3c/manifest/commit/29f1690a8371990fc8dae254445232d252aef7cc

**Comment by marcoscaceres** [comment]
We (Mozilla) don't currently do anything with" platform". Tho it would be great if Google would be consistent with names, as we might also need to rely on them 😉

**Comment by kenchris** [comment]
Something like

```
The values supported by the image and application object may differ as an operation system can have multiple app stores. As an example, Firefox and Chrome may both use the value "android" for image objects on Android, and "windows" on Windows, but use "play" to refer to native applications in the Play Store, or "samsung" to those in the Samsung store.

This specification does not define the particular values (like the above) for a the platform member. However, the working group maintains a list of known platform values in our wiki.
```

**Comment by kenchris** [comment]
@RobDolinMS feel like handling this one? and make sure it fits with what Microsoft wants

**Comment by marcoscaceres** [comment]
Closing, as we now only have "play" in the examples.
