### ISSUE TITLE
Tools for Web App Manifests

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#541]
Has anyone worked on any tooling for web app manifests?

For example, do we have anything that could take a URL to a web app manifest and return which members are present?

Or, do we have anything that could take a list of URLs (CSV file?) and output the URLs of web app manifests for each URL in the CSV?

**Comment by marcoscaceres** [comment]
> Or, do we have anything that could take a list of URLs (CSV file?) and output the URLs of web app manifests for each URL in the CSV?

I've got code that does that.

**Comment by marcoscaceres** [comment]
> For example, do we have anything that could take a URL to a web app manifest and return which members are present?

And for this... :)

**Comment by marcoscaceres** [comment]
@RobDolinMS, if you email me, we can set something up. The repo I have for that code is private, ATM... but happy to share the tooling and you are free to use it however you want.
