### ISSUE TITLE
Make start_url relative to scope and not manifest location

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest#552]
When no scope is declared, start_url would be relative to manifest location as that then would serve as default scope (ie. default scope would be ".").

This seems to follow more or less what the Chrome WebAPK implementation is doing. @PaulKinlan

**Comment by mgiuca** [comment]
I don't think this is how Chrome WebAPKs work. @pkotwicz can you confirm?

It sounds a bit cyclic to me to have a rule that essentially says:

- If `scope` is declared, `start_url` is relative to `scope`.
- If `scope` is not declared, `start_url` is relative to manifest URL, and `scope` default is based on `start_url`.

Although it seems reasonable to make the start URL based on scope, the above rule is a bit too complex and I think it's nice and simple to have everything be relative to the manifest URL.

**Comment by kenchris** [comment]
I'm fine with closing this
