### ISSUE TITLE
Simple Example and Complex Example

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#553]
I've noticed some manifest members are not included in our current example.

I'm thinking we should have two examples:
* A simple example with a small set of the most common fields (ex: name, icons, etc.)
* A complex example with a complete (or near complete) set of all fields (ex: prefer_related_applications, etc.)

If folks agree, please comment and I'm glad to draft a PR.  /cc @marcoscaceres @kenchris @mounirlamouri @anssiko 

--- Update below from 14 March ---
Incorporating suggestions from below, here's what I'm thinking for examples:
[X] Simple example near front (#557)
[X] Complex example with stable objects near front (#558)
[ ] Complex examples with less-stable objects either with those objects or in appendix

**Comment by marcoscaceres** [comment]
So, what's key to remember is that people are coming to the spec and copy/pasting whatever we put at the top there - so we need be really careful. This burnt us already with `density`. What we should maybe do is have an Appendix with more examples.  

Some things are quite complex (e.g., `scope`)  so we need to add more detailed examples for those. Same with `prefer_related_applications` and friends, because of how they integrate with app stores.

**Comment by anssiko** [comment]
+1 to what @marcoscaceres said. Make sure the first example people come up with in the spec includes only members that are considered stable (=are shipping widely). Put more complete example(s) in appendix with a big bold warning that developers should not copy directly given the examples contain features that might change out from under them in incompatible ways (e.g. adapting the beautiful warning from the status section: https://w3c.github.io/manifest/#sotd).

That said, PRs welcome.

**Comment by RobDolinMS** [comment]
Thanks guys.  @marcoscaceres makes an especially important point about people copying the example:
>people are coming to the spec and copy/pasting whatever we put at the top there - so we need be really careful
I'm traveling for work for most of the next two weeks and will try to take a cut at a PR.

**Comment by RobDolinMS** [comment]
Thanks all.  I've submitted PR #557 to add a very simple example and updated the original description of this Issue with a proposal to address @marcoscaceres's and @anssiko's suggestions about more complex examples and stable vs. unstable objects.

**Comment by marcoscaceres** [comment]
Current examples are ok, so closing
