### ISSUE TITLE
Extending the manifest with 'vendor-specific' properties

### ISSUE THREAD

**Issue by arcadiogarcia** [w3c/manifest#560]
I am currently developing a platform for developing HTML5 games, and one of the things devs using it are required to do is to create a manifest.json that specifies some information about the game. At first I thought of just using the Web App Manifest, since many properties (name, scope, icons...) are similar, but others are very specific to my use case (fps, screen resolution...).

I still think it would be really nice to let my users just have a W3C compliant manifest.json for their web game, and let them extend it with additional properties to provide the additional info my platform would need.

That is why I was wondering if there are any plans for allowing 'vendor-specific', additional properties to the added to the manifest while still following the standard. IMO that would help to make the web manifest more powerful, allowing it to specify information that is only relevant in certain web apps.

**Comment by kenchris** [comment]
That should already be mentioned in the spec with examples. Does this not cover your use-cases?

I still do think it makes sense discussing your extension points as we might be able to generalize ideas

**Comment by arcadiogarcia** [comment]
I'm sorry, I can't find any relevant example in the spec, do you mean [this one](http://www.w3.org/TR/appmanifest/#example-manifests)? (I only see the standard members defined in point 8).

My extension points would be:

- Frames per second (two different fields, one for the rendering and one for the game loop)
- The screen resolution at which the game is rendered
- Some string arrays indicating files that deserve special treatment (level files, game code files, spritesheet files).
- A capabilities member to specify which features of the engine does the game use
- A dependencies member to specify which external modules does the game use

so ideally the manifest would end up looking something like this: 

```
{
    "name": "Pong",
    "scope": "gameFiles",
    "components": [
        "components.js"
    ],
    "levels": [
        "levels.xml"
    ],
    "spritesheets": [
        "spritesheets.xml"
    ],
    "screenResolution": {
        "w": 320,
        "h": 200
    },
    "dependencies": {
        "keyboard": "1.0",
        "gamepad": "1.0",
        "pointBoxCollision2D": "1.0"
    },
    "capabilities": [
        "ClockworkRuntime"
    ],
    "themeColor": "#4B5",
    "backgroundColor": "#000",
    "tileIcon": "tileIcon.png",
    "enginefps": 60,
    "animationfps": 60
}
```

**Comment by kenchris** [comment]
I am thinking about section 15.1 and example in 15.1.1

**Comment by kenchris** [comment]
Generally what you add feels very specific to your engine, like configuration data. Maybe you could still use the manifest but have this additional configuration data in another file, potentially linked to from the manifest, or the other way around

**Comment by kenchris** [comment]
We have discussed (without conclusion) the ability to set window size for windowed apps, like max or min width, but generally web apps scale quite well.

**Comment by arcadiogarcia** [comment]
I saw point 15 but I somehow missed point 15.1😅 That indeed covers my use case, thanks for your help!

Instead of adding a configuration file, I was thinking about adding a single proprietary manifest member which has an object with all the configuration at its value (that way I would still keep the number of additional members at one), something like this:

```
 {
    "name": "Pong",
    "scope": "gameFiles",
    "theme_color": "#4B5",
    "background_color": "#000",
    "icons": ... ,
    "clockwork":{
        "components": [
            "components.js"
        ],
        "levels": [
            "levels.xml"
        ],
        "spritesheets": [
            "spritesheets.xml"
        ],
        "screenResolution": {
            "w": 320,
            "h": 200
        },
        "dependencies": {
            "keyboard": "1.0",
            "gamepad": "1.0",
            "pointBoxCollision2D": "1.0"
        },
        "capabilities": [
            "ClockworkRuntime"
        ],
        "enginefps": 60,
        "animationfps": 60
    }
}
```

**Comment by RobDolinMS** [comment]
@arcadiogarcia With the spec text in section [15.1 Extensibility](http://www.w3.org/TR/appmanifest/#extensibility) would it be OK to close this issue?

**Comment by arcadiogarcia** [comment]
@RobDolinMS Sure :)
