### ISSUE TITLE
It is not stated how to decode the bytes obtained

### ISSUE THREAD

**Issue by domenic** [w3c/manifest#565]
https://www.w3.org/TR/appmanifest/#obtaining assumes the body is a string, but it is not. It is a stream of bytes. You need to decode it, preferably using UTF-8 decode.

This is important as people might be assuming that you e.g. respect the Content-Type header or do some sort of sniffing.

For an example of how to do this see https://domenic.github.io/payment-method-manifest/#processing-model

**Comment by marcoscaceres** [comment]
Now at: https://w3c.github.io/payment-method-manifest/#processing-model

**Comment by marcoscaceres** [comment]
@kenchris, can you take this one? I don't have cycles to do it.

**Comment by anssiko** [comment]
@kenchris @domenic PTAL #570

And please educate me if we need something more than this.
