### ISSUE TITLE
Publishing icons for various UI sizes (DIPs)

### ISSUE THREAD

**Issue by mastiz** [w3c/manifest#568]
I was wondering if the following feature request has been discussed.

Some sites like cnn.com or reddit.com publish icons not only of different resolution, but also of different content: presumably intended to be used in UIs of different DIP size. In a high density screen, say mobile, fitting a high-resolution image into a small UI (in DIPs) leads to a too detailed, hard-to-see image.

This spec could be extended with some additional field per icon.

**Comment by marcoscaceres** [comment]
We attempted this previously, (via the `density` member), but we had to remove it. Authors got confused and it ended up doing more harm than good 😭

**Comment by mastiz** [comment]
Thanks! Can you please provide some links to the past discussions, assuming they're accessible? Within Chrome, the use of manifest icons for certain UIs has been considered a regression for the examples I listed earlier, so we might need to combine manifest and non-manifest icons depending on the UI, which doesn't seem easier to get right by authors.

**Comment by mastiz** [comment]
Friendly ping, thanks.

**Comment by marcoscaceres** [comment]
Apologies, I missed this. Here is all the issues that mention "density":
https://github.com/w3c/manifest/issues?utf8=✓&q=is%3Aissue%20is%3Aclosed%20%20density

The one that pertains to this in particular:
https://github.com/w3c/manifest/issues/450

**Comment by mastiz** [comment]
Thanks Marcos, that's very useful.
