### ISSUE TITLE
Small markup issues

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#572]
See comments in https://github.com/w3c/manifest/pull/570/files

**Comment by anssiko** [comment]
There's no comments, did you forgot to submit your review?

**Comment by marcoscaceres** [comment]
Yep, I sure did 👍

**Comment by anssiko** [comment]
Fixed with https://github.com/w3c/manifest/commit/7a0c1fc95370204324c9e754e5acb411f87ca211
