### ISSUE TITLE
Which "platform" should I use for Windows 10 UWP apps?

### ISSUE THREAD

**Issue by ndbroadbent** [w3c/manifest#580]
I saw this note on https://w3c.github.io/manifest/

> This specification does not define the particular values for a the platform member. However, the working group maintains a list of known platform values in our wiki.

However, the [wiki page](https://github.com/w3c/manifest/wiki/Platforms) only included "play", while [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/Manifest#related_applications) also include "itunes". (I'll update the wiki.)

Is it worth adding a link for my app on the Windows Store? Even if Windows 10 doesn't currently support these links, they may do so in the future, so I want to make sure that I choose the correct "platform" string.

**Comment by ndbroadbent** [comment]
And I guess if no-one has thought about this, then I'm happy to make the decision. It should be "windows" for the Windows Store.

**Comment by marcoscaceres** [comment]
Im sure our friends at Microsoft have give it some thought. Please give them time to answer.

**Comment by nolanlawson** [comment]
`"windows"` has been added to the wiki, and it appears [pwa-builder expects `"windows"`](https://github.com/pwa-builder/manifoldjs-lib/blob/168a4c666ca6029a418684a3e3a54ee5f4eab86b/test/manifestTools/manifestCreator/manifestCreator.js#L168) as well.

**Comment by marcoscaceres** [comment]
Closing, as per https://github.com/w3c/manifest/issues/580#issuecomment-343234260
