### ISSUE TITLE
Provide VR display mode

### ISSUE THREAD

**Issue by delapuente** [w3c/manifest#583]
WebVR is getting traction and it introduces a new display mode to be considered: VR.

I'm thinking of a new `vr` value for the `display` property. Thoughts?

**Comment by cvan** [comment]
what would be the behaviour of `vr`? besides signalling to the browser intent to use the WebVR API? would this be an alias of `fullscreen`, `standalone`, etc.?

**Comment by marcoscaceres** [comment]
It just degrades gracefully to fullscreen.

**Comment by marcoscaceres** [comment]
> what would be the behaviour of vr? 

This is an interesting question: currently, the VR context is a canvas that requests fullscreen, no? What would entering into a VR context mean for a regular web page?

**Comment by cvan** [comment]
> This is an interesting question: currently, the VR context is a canvas that requests fullscreen, no? 

Actually, most sites upon entering VR do not request Fullscreen mode (nor Pointer Lock). They could, but it's not common practice in three.js or A-Frame WebVR sites.

> What would entering into a VR context mean for a regular web page?

In my opinion, I'd say the best parallel it playing a `<video>`. Entering/exiting VR mode is more based on sessions (à la the Presentation API and Chromecast).

Does that help? Let me know if there are other points I can help clarify. Thanks, @marcoscaceres and @delapuente!

**Comment by delapuente** [comment]
@marcoscaceres confirm this: the fullscreen display mode is not related to the fullscreen API. Is that correct? If so, perhaps the display mode is not suitable for something like VR. But, in the same way [link traversal](https://w3c.github.io/webvr/spec/1.1/#dom-vrdisplayeventreason-navigation) triggers the [`vrdisplay` event](https://w3c.github.io/webvr/spec/1.1/#interface-vrdisplayevent). It would be convenient to hint the OS about the nature of the app so the browser can trigger this same event at the beginning.

Does it make sense, @cvan @marcoscaceres ?

**Comment by cvan** [comment]
We've discussed using a `<meta http-equiv>` tag with an equivalent HTTP Response header to indicate to the User Agent/client hints of what kind of, if any, VR content it is (and whether we should auto-enter VR, world-coordinate systems, projection matrices, etc.).

**Comment by marcoscaceres** [comment]
>  the fullscreen display mode is not related to the fullscreen API.

Correct. It's to do with browser chrome. 

>  It would be convenient to hint the OS about the nature of the app so the browser can trigger this same event at the beginning.

Depends on what "convenient" means: It would have to do something significant in the browser during the application's launch (like the other view modes to - where they set up the display, take away browser chrome, and potentially lock the orientation). 

So the above sets the bar, and that's what would need to be clarified before we would include this display mode. 

(also, just realized the VR spec you pointed to is deprecated and no longer has a "navigation" event - new spec: https://w3c.github.io/webvr/spec/latest/ ... I've not read the spec, but if we want to move forward with it, we would probably want to set up a call with the editors of that spec to see if they see much value in adding this)

**Comment by marcoscaceres** [comment]
@cvan 
> We've discussed using a `<meta http-equiv>` tag with an optional (but recommended) equivalent HTTP Response header to indicate to the User Agent/client hints of what kind of, if any, VR content it is (and whether we should auto-enter VR, world-coordinate systems, projection matrices, etc.).

Interesting... did anything come from those discussions? Anything that you think would be appropriate here?

**Comment by marcoscaceres** [comment]
Closing as I think web-vr is fine spinning up it’s own 3d context.
