### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/manifest#585]
Would you like time at [TPAC](https://www.w3.org/2017/11/TPAC/) to update the WG on progress and/or bring issues up for discussion?

Please let me know by Friday 16th June. If yes, please also let me know how much time you think you'll need.

**Comment by anssiko** [comment]
Personally I'll have a schedule conflict on Thu-Fri with WebVR WG.

Other editors @marcoscaceres @kenchris @mounirlamouri may be able to lead the discussion.

**Comment by LJWatson** [comment]
Thanks @anssiko. We're still figuring out the logistics, but WebPlat will likely meet Mon, Tue, and Thu (with Thu being set aside for the Editing TF).

**Comment by marcoscaceres** [comment]
I can give a 10 minute update during the general Web Platform WG meeting.

**Comment by kenchris** [comment]
If I get travel approval, I can help

**Comment by anssiko** [comment]
@LJWatson, per https://www.w3.org/2017/11/TPAC/#Schedule Thu-Fri is allocated to Web Platform WG. Should probably fix that?

(I have a conflict on Mon-Tue too with Second Screen WG, so I'll happily defer this update to my fellow editors regardless of the choice of days.)

**Comment by LJWatson** [comment]
Thanks @marcoscaceres and @kenchris, an update on progress would be welcome.

anssiko that was true at the time of my first message, but we had to shuffle things around in the TPAC schedule yesterday - so now WebPlat will meet on Thu/Fri, sorry.
