### ISSUE TITLE
ServiceWorker type-member ( "type" : "module" )

### ISSUE THREAD

**Issue by nuxodin** [w3c/manifest#594]
Maybe we should add a "type" member for "service_workers"?

```
...
"serviceworker": { 
    "src": "sw.js", 
    "scope": "/racer/", 
    "use_cache": false 
    "type": "module" 
},
...
```

Will be needed once Browsers support serviceWorkers as js-modules.
https://html.spec.whatwg.org/#module-worker-example

**Comment by marcoscaceres** [comment]
Sorry for my ignorance, but can you provide more background as to why it will be needed? I don't know all the details of `module`. 

What benefit does it provide and what benefit will it provide for users or developers if we include this.

**Comment by patrickkettner** [comment]
@marcoscaceres (from the whatwg spec)

> Workers can instead be instantiated using module scripts, which have the usual benefits: the ability to use the JavaScript import statement to import other modules; strict mode by default; and top-level declarations not polluting the worker's global scope.

The SW spec was actually [updated](https://github.com/w3c/ServiceWorker/commit/6d9500e99e764c12b117c63d10107e094d243662) to include the concept of modules back in february of last year

**Comment by marcoscaceres** [comment]
@patrickkettner oh, ok! got it, thank you. Yeah, I agree, this seems really nice.

**Comment by kenchris** [comment]
What is the reason this was closed?

**Comment by kenchris** [comment]
:)
