### ISSUE TITLE
we refer to ASCII lowercase from WHATWG infra spec but Trim from ES spec

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest#600]
We should be more consistent

ie we could refer to ToLowerCase from ECMA as well

```When instructed to ToLowerCase(x), a user agent must behave as if [ECMASCRIPT]'s String.prototype.toLowerCase() function had been called on the string x.```
      
Or we could refer to infra instead of Trim()
https://infra.spec.whatwg.org/#strip-leading-and-trailing-ascii-whitespace

**Comment by kenchris** [comment]
We could argue as this is JSON based, following ECMA makes the most sense.

**Comment by marcoscaceres** [comment]
Yeah, it's tempting... but prefer infra: https://infra.spec.whatwg.org/#strip-leading-and-trailing-ascii-whitespace

**Comment by aarongustafson** [comment]
Trim no longer appears in the spec, so I’m closing this.
