### ISSUE TITLE
Fix references to lower case in spec

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#602]
Opening per [discussion](https://github.com/w3c/manifest/pull/598#issuecomment-321781841) with @kenchris in #598 

The Manifest spec includes three instances of "to lower-case" and two instances of "to ASCII lowercase"

Should all of these be made consistent and updated to reference: https://www.ecma-international.org/ecma-262/8.0/index.html#sec-string.prototype.tolowercase

**Comment by kenchris** [comment]
This is related to #600

**Comment by marcoscaceres** [comment]
This should actually refer to the [[infra]] spec. https://infra.spec.whatwg.org/#ascii-lowercase

**Comment by marcoscaceres** [comment]
(in case all instances where we lowercase are ascii - which, if I remember correctly, they are)
