### ISSUE TITLE
Consider adding a `theming` manifest member or a separate spec for browser customisation

### ISSUE THREAD

**Issue by delapuente** [w3c/manifest#618]
The manifest provides several members to control the aspect of the browser where branding is important. This proposal suggests gathering these members under a new member `theming` or considering the creation of a new specification for browser customisation.

`theme_color`, `icons`, `purpose` values #617, a possible `spash_screen` definition #589 and other discussions related to design could live separately from the manifest spec and get input from design audiences.

**Comment by christianliebel** [comment]
Actually, the manifest’s purpose is to define the appearance of the installed app, so I think it’s perfectly valid to have `theme_color` etc. as a “root member” of the web app manifest. Apart from that, I think it’s too late for radically changing the structure of the manifest now, as many sites are already actively using it. That’s why I would vote for closing this issue.

@marcoscaceres What do you think about this?

**Comment by mgiuca** [comment]
I would close this. Those things are one of the primary use cases for Manifest.
