### ISSUE TITLE
Remove Trim() logic on string members

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#620]
Most of the manifest fields (see below) are specified as trimming their string values during processing. The question has come up as to whether to remove this logic (spun off from #611 --- it makes it much easier to specify the manifest in WebIDL without the trimming logic). However it's really a separate issue.

Removing this logic would be a breaking change to the Web, so we need an analysis of existing manifests to see if this is going to break. It's also open to debate whether this change is desirable.

The fields that currently trim are:

- dir
- lang
- name
- short_name
- description
- display
- orientation
- categories
- iarc_rating_id
- Image.src
- Image.type
- Image.platform
- ServiceWorker.src
- ServiceWorker.scope
- ServiceWorker.type
- Application.platform
- Application.url
- Application.id
- Application.min_version

There are numerous other fields (mostly URLs) that aren't trimmed, so the set of fields that are trimmed seems quite arbitrary (e.g., why is ServiceWorker.scope trimmed, but not scope?).

I would say we should divide the strings into user-facing and non-user-facing. The user-facing ones (name, short_name, description, categories) probably should still be trimmed, since it doesn't make sense for an application name to have leading or trailing spaces. The spec doesn't necessarily have to explicitly trim them; this could just be left up to the platform.

The other fields really have no business being trimmed. URLs, enum values, and so on, should just be an error if they contain spaces at all.

**Comment by mgiuca** [comment]
@marcoscaceres @kenchris 

I am going to run a quick analysis of public manifests to see if this would break any of them.

**Comment by marcoscaceres** [comment]
> I would say we should divide the strings into user-facing and non-user-facing. The user-facing ones (name, short_name, description, categories) probably should still be trimmed, since it doesn't make sense for an application name to have leading or trailing spaces. The spec doesn't necessarily have to explicitly trim them; this could just be left up to the platform.

I agree. Representation of the string should be left up to the platform (i.e., it should guard against such unrestrained inputs). I'd be in favor of not trimming.

**Comment by mgiuca** [comment]
I've done an analysis of a large corpus of about 50,000 manifests (from January 2017, so somewhat out of date).

The results are that there are only 6 manifests that have leading/trailing whitespace in a field other than name, short_name, description; all of them are the "src" field of an icon. 4 of them are completely non-sensical (the whitespace is a backslash before a word starting with 't' or 'f', like `"\the"` (i.e., "&lt;tab&gt;he"), so obviously that's not correct). So we're going to break ~2 sites' icons.

I also found 9 manifests with a trimmable description, 15 with a trimmable short_name, and 100 with a trimmable name. Though as discussed, I think if we drop the "Trim" behaviour from these fields, it will have no observable effect, because user agents will still be allowed to to trim those fields at their discretion (and they should continue to do so).

I'll try to get a newer corpus to re-run the analysis, but at this stage, it looks like we can just remove Trim now.

Maybe we do it in a separate PR to @kenchris's major refactor, so we have a small change that explicitly breaks backwards compatibility, and Ken's change should have no real observable effect.

**Comment by marcoscaceres** [comment]
@mgiuca, can you confirm that those trimmable ones are actually served over "https://"? It might be that they don't even qualify as an installable "progressive web app" (thus further ruling them out).

**Comment by marcoscaceres** [comment]
> Maybe we do it in a separate PR to @kenchris's major refactor, so we have a small change that explicitly breaks backwards compatibility, and Ken's change should have no real observable effect.

I agree. Let's do this as a different PR.

**Comment by marcoscaceres** [comment]
(also, thanks for doing the data analysis! this is great news!)

**Comment by mgiuca** [comment]
> can you confirm that those trimmable ones are actually served over "https://"? It might be that they don't even qualify as an installable "progressive web app" (thus further ruling them out).

I was looking at all of them (as @dominickng argued that they still count as manifests even if they aren't installable). If we just look at the HTTPS ones, the icon "src" ones are reduced to just 2, and one of them is invalid.

**Comment by marcoscaceres** [comment]
@dominickng is technically correct - but no user agent currently supports manifests without HTTPS (because I think we are all adhering somewhat to the [installability signals](https://www.w3.org/TR/appmanifest/#installability-signals))... we should probably also make this a HTTPS only feature in the spec.

**Comment by mgiuca** [comment]
We could make Trimming an HTTPS-only feature :)

j/k

**Comment by kenchris** [comment]
> Maybe we do it in a separate PR to @kenchris's major refactor, so we have a small change that explicitly breaks backwards compatibility, and Ken's change should have no real observable effect.

I will rather do it as part of that PR, or I will have to re-add lots of sections etc for the sake of removing them soon after. I know it is not perfect, but the IDL PR was a bit hard to get right

**Comment by kenchris** [comment]
I will remove the trim for categories

**Comment by marcoscaceres** [comment]
Whatever works best for you. We just want to make sure you don’t get overworked/overwhelmed with changes 🛠

**Comment by mgiuca** [comment]
I was suggesting we land a change removing all the Trims before you land yours (then you would not need to add lots of Trim logic to the new version; you would have a merge conflict but you could resolve it in favour of your existing version).

It would make it clear that we intentionally removed Trim, rather than it just accidentally disappearing during a refactor.

**Comment by marcoscaceres** [comment]
> It would make it clear that we intentionally removed Trim, rather than it just accidentally disappearing during a refactor.

Well, this is kinda no longer a refactor... it's already a "2.0" with lots of breaking changes. Might as well keep breaking stuff now that we are on a roll.

**Comment by kenchris** [comment]
I don't see any trims in the spec now, can we close?

**Comment by mgiuca** [comment]
Yep!
