### ISSUE TITLE
Create a test suite for the specification

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest#623]
@Honry has volunteered to look into this. @marcoscaceres could you share your Moz specific tests just for inspiration?

**Comment by kenchris** [comment]
@RobDolinMS do you have any tests at MSFT?

**Comment by marcoscaceres** [comment]
(I'll note that those are all automated tests... which don't help us... but we can maybe take some of the test conditions, do some copy/paste magic, and get some manual tests out of them)

**Comment by marcoscaceres** [comment]
...also, the tests don't conform to our new "V2" of the spec - because the IDL now makes things case sensitive. That's ok tho, just thought I would mention it.

**Comment by marcoscaceres** [comment]
We should move this bug to https://github.com/w3c/web-platform-tests

**Comment by kenchris** [comment]
@Honry can you take care of this?

**Comment by Honry** [comment]
@kenchris, @marcoscaceres, I've move this issue to https://github.com/w3c/web-platform-tests/issues/7912

**Comment by marcoscaceres** [comment]
Thanks @Honry. Closing so we can continue discussion there.
