### ISSUE TITLE
multilingual description

### ISSUE THREAD

**Issue by grrd01** [w3c/manifest#628]
I cannot find a way to create multilingual descriptions in my manifest file for a multilingual web app.

With the old manifest files for chrome web store, it was possible to add this to the manifest:
"description": "__MSG_appDesc__",

and then add a json-file for each language in a _locales folder:
_locales/en/messages.json:

{
  "appDesc": {
    "message": "my english description..."
  }
}

However, in the current w3c manifest specifications, it seems there's no way of doing this.

**Comment by marcoscaceres** [comment]
Right, you need to host your own manifest and set `<link rel=manifest>` to point to your localized version.

**Comment by marcoscaceres** [comment]
@grrd01, see also the description here:
https://www.w3.org/TR/appmanifest/#internationalization

**Comment by grrd01** [comment]
@marcoscaceres : thanks for your fast response!
Did i get you right:
Whenever I dynamically translate my index.html with webL10n (https://github.com/fabi1cazenave/webL10n), I am supposed to also replace the <link rel=manifest> to point to the proper localized version of my manifest-file?
Will the google bots and web app catalogs understand this behavior?

**Comment by marcoscaceres** [comment]
> Whenever I dynamically translate my index.html with webL10n , I am supposed to also replace the <link rel=manifest> to point to the proper localized version of my manifest-file?

I can't comment on webL10n, as I've never used it. But yes, that's an option. 

> Will the google bots and web app catalogs understand this behavior?

I don't see why not? Bots execute JS.

**Comment by grrd01** [comment]
@marcoscaceres : Since I doubt, a bot will be clever enough to find the right button to change the language to all available options, I'm afraid the only way for a bot to detect all languages will be to visit my site with a lot of different regional & language settings, where the initial language is selected from.
I don't think that's what google is doing, but I'm not an expert on this.

Anyway, thanks for your help! I'll close the issue since this is probably as far as I'll get..

**Comment by marcoscaceres** [comment]
> where the initial language is selected from.

Treat it as the same as an unregistered user who has just landed on your site. It’s basically the same problem. 

A user who had registered and given a language preference needs a different approach.
