### ISSUE TITLE
"Default" Orientation

### ISSUE THREAD

**Issue by nunoperalta** [w3c/manifest#632]
I understand that the values allowed for the manifest's orientation are the same as OrientationLockType in the Screen Orientation API.

However, none of the following orientations seems to simply respect user's Rotation Lock settings:

any
natural
landscape
landscape-primary
landscape-secondary
portrait
portrait-primary
portrait-secondary

"natural" seems to just be the same as "portrait", even if my phone is locked in Landscape.

"any" seems to just ignore any setting, and simply allow rotation freely.

I realized eventually that if I don't provide an "orientation" setting in the manifest, the app will simply respect the user's rotation lock setting, while still allow for rotation, similarly to "any", if the user doesn't have rotation locked. This is true on Google Chrome.

Is this an official/standard behavior, that if we don't provide the setting, it will default to the device's orientation setting?

Would there be any chance to have an extra orientation option, like "auto" or "default", to ensure this is the behavior I want for my application? I'm afraid that browsers could have different behaviors for orientation, because I didn't specify it in my manifest.

**Comment by mounirlamouri** [comment]
Which "Rotation Lock settings" are you talking about?

`natural` is meant to be the natural orientation, for most phone, that would be `portrait`. Tablets may have `landscape` as their `natural` orientation.

The description of `any` also follows the spec.

If you want to use the default orientation not setting the orientation as you are doing seems to be the right solution.

**Comment by nunoperalta** [comment]
Hello,

I'm talking about the Lock Screen Rotation feature on Androids (and possibly most systems).

See screenshots here - https://www.howtogeek.com/201130/how-to-lock-screen-orientation-in-android/

Thank you.

**Comment by mounirlamouri** [comment]
Only the default orientation is meant to follow this behaviour.

**Comment by nunoperalta** [comment]
Thank you.
So, the official way to ensure this behavior is by not providing an orientation?

Is it part of the spec that all browsers will respect the phone's orientation lock setting if no orientation is provided in the manifest?

I'm just afraid that some browsers could default to "natural" or something like that.

I would prefer to be able to explicitly say in the manifest that I want this behavior, rather than assuming browsers will do what I want.

**Comment by mounirlamouri** [comment]
It should be fine. `natural` is defined here: https://w3c.github.io/screen-orientation/#dom-orientationlocktype-natural and the other values around it.

Closing now.
