### ISSUE TITLE
PromptResponseObject definition is missing in "IDL Index"

### ISSUE THREAD

**Issue by Honry** [w3c/manifest#637]
In [IDL Index](https://w3c.github.io/manifest/#idl-index) section, [PromptResponseObject](https://w3c.github.io/manifest/#beforeinstallpromptevent-interface) definition is missing.

**Comment by marcoscaceres** [comment]
This is a bug in ReSpec. Filed https://github.com/w3c/respec/issues/1479

**Comment by marcoscaceres** [comment]
Fixed
