### ISSUE TITLE
Share from Gallery or Browser

### ISSUE THREAD

**Issue by nunoperalta** [w3c/manifest#639]
Hello,

Is it possible, or is it planned, to allow users to select a Photo in their Gallery app and use "Share" to a PWA, to facilitate photo uploading?

Similarly, a "Share" button on browsers, like Google Chrome, to share a link with a PWA.

Both of the above are possible with normal Android apps, but I couldn't find a way to do it with PWAs.

Thank you.

**Comment by kenchris** [comment]
There is the Web Share Target specification https://wicg.github.io/web-share-target/ which builds upon Web App Manifest and allows something similar to what you want :-)

**Comment by marcoscaceres** [comment]
@nunoperalta, as @kenchris mentioned, might be best to ask over at the Share Target repo, as it's outside the scope of this spec.
