### ISSUE TITLE
Clarify service worker member, and when it installs

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#640]
@GrosSacASac wrote: 

If I understand correctly, the service worker declaration inside the manifest has no consequence unless the web app is installed without directly visting the web app url.(with an web app store ?)

I ask because I have an app where the service worker is only installed after the users checks the checkbox USE OFFLINE. I don't want the manifest to install the service worker on normal page load without user consent first.

I came here because https://www.w3.org/TR/appmanifest/#serviceworker-member words are confusing.

**Comment by christianliebel** [comment]
@marcoscaceres There’s a discussion in https://github.com/w3c/manifest/issues/800 on exactly this topic, so I’d suggest closing the issue here.

**Comment by mgiuca** [comment]
Closing in favour of #800.
