### ISSUE TITLE
ServiceWorkerRegistration dictionary conflicts with ServiceWorker WebIDL

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/manifest#641]
[`ServiceWorkerRegistration`](https://www.w3.org/TR/appmanifest/#the-serviceworkerregistration-dictionary-and-its-members) redefines the name `ServiceWorkerRegistration`, but that name is already used by an [interface in the Service Worker spec](https://w3c.github.io/ServiceWorker/v1/#serviceworkerregistration-interface).

This is forbidden by WebIDL:
> Within the set of IDL fragments that a given implementation supports, the identifier of every interface, namespace, dictionary, enumeration, callback function and typedef must not be the same as the identifier of any other interface, namespace, dictionary, enumeration, callback function or typedef.

**Comment by kenchris** [comment]
Name suggestion?

**Comment by anssiko** [comment]
`ServiceWorkerRegistrationOptions` or `ServiceWorkerRegistrationSettings`?

There's precedence for both the suffixes for dictionary names on the platform.

Should pick something that's not confusing in the context of the [service worker registration](https://w3c.github.io/ServiceWorker/v1/#dfn-service-worker-registration) definition.

**Comment by kenchris** [comment]
We might need to rename other parts of the IDL to be consistent then

**Comment by marcoscaceres** [comment]
We should do this sooner, rather than later. @kenchris, could you take this?

**Comment by kenchris** [comment]
I could take this but we need to come up with a name.

Service Worker spec also has this

```
dictionary RegistrationOptions {
  USVString scope;
  WorkerType type = "classic";
  ServiceWorkerUpdateViaCache updateViaCache = "imports";
};
```

and we have

```
dictionary ServiceWorkerRegistration {
    required USVString src;
             USVString scope;
             USVString type = "classic";
             boolean   use_cache = "false";
};
```

It seems they changed their API, so maybe we should follow. @RobDolinMS could MS update to follow this new API ?

**Comment by kenchris** [comment]
ie move to use WorkerType as defined here: https://html.spec.whatwg.org/multipage/workers.html#workertype

And ServiceWorkerUpdateViaCache defined here:
https://w3c.github.io/ServiceWorker/v1/#enumdef-serviceworkerupdateviacache

**Comment by kenchris** [comment]
```
dictionary ServiceWorkerRegistrationObject {
    required USVString src;
             USVString scope;
             WorkerType type = "classic";
             ServiceWorkerUpdateViaCache updateViaCache = "imports";
};
```
