### ISSUE TITLE
how to change app name text color on the splash screen?

### ISSUE THREAD

**Issue by Focus3D** [w3c/manifest#642]
Hi,
There is no mention on how to change the app name text color on the splash screen, unexplained color change when using google chrome on android for the [airhorn ](https://github.com/GoogleChromeLabs/airhorn)app:
default : with “background_color”: “#2196F3” in manifest.json
![screenshot_2018-01-25-17-28-14](https://user-images.githubusercontent.com/1816969/35440114-ac354c08-02a6-11e8-9580-0d7e6c30be5e.png)

edited : “background_color”: “#FFFFFF” in manifest.json and "name": "Air Horner" (to see which one was used)
![screenshot_2018-01-25-18-13-53](https://user-images.githubusercontent.com/1816969/35440138-cdbcb06e-02a6-11e8-9d48-923f2e9dc5af.png)

So is it contrast related?
Is there any color table or do we have to test all colors to create one.
This is really an issue for branding.
Thank you.

**Comment by mounirlamouri** [comment]
You might want to file a Chrome bug for this as it's a Chrome specific behaviour. You can do this at https://crbug.com/new

This said, you are right, this is contrast related. You can find the logic [here](https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/util/ColorUtils.java?q=shouldUseLightForegroundOnBackground&sq=package:chromium&l=142).

/CC @dominickng @mgiuca

**Comment by Focus3D** [comment]
thank you and really sorry for disturbing you.

**Comment by dominickng** [comment]
@Focus3D FYI, we've been trying to work out a better way of handling splashscreens to give developers more control (mostly on https://github.com/w3c/manifest/issues/589), but these efforts have stalled for the meantime for lack of engineer time.
