### ISSUE TITLE
Add Matt Giuca as Co-Editor

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#650]
@chaals, @LJWatson (Chairs of the Web Platform WG): As is required by the W3C process,  the Editors would like to request @mgiuca become a co-editor of the Web Manifest specification. 

Over the last year, @mgiuca has made significant contributions to the specification ([commit history](https://github.com/w3c/manifest/commits?author=mgiuca), and plans to continue to help us move this specification to W3C Recommendation status. 
 
On behalf of the editors, we would like to acknowledge his substantial contributions and continued participation in the specification by listing him as co-editor.

**Comment by chaals** [comment]
Done: https://lists.w3.org/Archives/Public/public-webapps/2018JanMar/0011.html

**Comment by marcoscaceres** [comment]
@chaals, thanks!
