### ISSUE TITLE
New Boolean members to control interaction with related applications

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#658]
For a number of years, there have been requests to support the following two use cases:

1. Suppressing notifications if the related app is installed. If the native app is installed, it could be assumed that it is sending notifications to the user, and thus the web app should not also send notifications.
2. Suppressing the web app install prompt if the related app is installed (in the `beforeinstallprompt` event handler). If the native app is installed, it would put the user into a confusing state if they were also offered to install the web app.

I propose two new Boolean manifest members that declaratively disable certain features of the web application if one or more of the `related_applications` are installed in the user's system.

* `disable_notifications_if_related_app_installed`: If true, then if one or more of the applications listed in `related_applications` are installed in the user's system, notification permission would be auto-blocked for the app. (This would be indistinguishable from the user blocking notifications.)
* `disable_install_prompt_if_related_app_installed`: If true, then if one or more of the applications listed in `related_applications` are installed in the user's system, the `beforeinstallprompt` event would not fire for this application.

A key requirement would be that the web app is not able to actually query whether or not related applications are installed.

Some concerns / issues:

* May need to require that the related application in some way links back to the web domain (e.g., through [Android Digital Asset Links](https://developers.google.com/digital-asset-links/)). Otherwise, you can potentially find out whether the user has any particular native app installed on their device. (However, this may not be necessary since you can't actually query whether an app is installed, you just experience run-on effects from this. But I think a clever malicious site could use knowledge about the behaviour of certain user agents to distinguish whether the app is installed or not.)
* This may not be flexible enough; you wouldn’t know whether or not to show UI relating to notifications in your app (because you can't tell in advance whether it's going to be auto-blocked by the native app being installed, or whether it will prompt the user).
* We may want to recommend that the UA only blocks notifications if the native app has already been granted notification permission in the OS.
* The notification one feels weirdly positioned in the Manifest (since notifications aren't part of the web app manifest, and can be fired by a normal web site). In particular, notification permission is per-origin, while manifests can have a path scope. Would a non-/-scoped manifest block notification permission for the whole origin? Would we ignore it unless the manifest is /-scoped?
* The "at least one" rule might not be flexible enough. Could make it "all", or could allow the user to define some subset of the `related_applications` (replacing the Boolean with a list of app IDs).

An alternative syntax might allow for shorter names and scale in the future if we find more similar use cases:

```json
"if_related_app_installed": ["disable_notifications", "disable_install_prompt"]
```

So there are a lot of details we have to sort out before we do this.

**Background**

Last year, Chrome ran an origin trial for a proposed API called `getInstalledRelatedApps`, which was a JavaScript method allowing the site to query for the subset of the `related_applications` Manifest member that were actually installed on the user's system. This API is detailed in this blog post:

https://developers.google.com/web/updates/2017/04/getinstalledrelatedapps

As the above post suggests, this API had only two known use cases (those at the top of this post).

The origin trial had very low participation and there was not much enthusiasm for continuing with the API ([write-up](https://groups.google.com/a/chromium.org/d/msg/blink-dev/vrB0sJ0tQaI/8teG0oyrAwAJ)). It represents a bit too much of an information leak for a web app to learn about the user's system. A [timing attack](https://bugs.chromium.org/p/chromium/issues/detail?id=707071) was also identified (which would be common to all implementations, not Chrome) that would allow a malicious site to reliably query for the installed state of a non-related application, unless carefully mitigated.

However, we still wish to solve the above two use cases, so we are proposing the above manifest flag, as a simple declarative option that solves precisely those use cases, without actually letting the website know whether the native application is installed, or presenting a timing attack surface.

**Comment by mgiuca** [comment]
@marcoscaceres @owencm @ewilligers

**Comment by mgiuca** [comment]
Had a discussion this morning. One possible approach is to *not* specify this, and just let user agents apply the above logic (as if those two flags were true) in all cases.

We asked ourselves the questions:

- If your native app is installed on Android, and has notification permissions turned on (presumably giving duplicate notifications from the web), would you ever want to also send notifications from the web? (Probably not.)
- If your native app is installed on Android, would you ever want to ask the user to parallel-install the web app? (Probably not.)

So perhaps no spec work here, just some Chrome-side implementation. What do people think about this?

**Comment by kenchris** [comment]
I think the above is fine.

There are a few people like me who might install the native app (like to send videos on Twitter, not supported by Twitter lite) but still prefer the PWA. I would like that if I turned off notifications in the native app, that then I would still be able to get them in the PWA.

Basically, native apps will take precedence, but there will be a fallback to the PWA.

We could also make the precedence depend on the value of https://www.w3.org/TR/appmanifest/#prefer_related_applications-member

**Comment by mounirlamouri** [comment]
It might be interesting to have this implemented as implementation details before being spec'd. However, there are some issues that are still worth thinking of and may not be solved by dropping the spec changes. The two proposals are suggesting that native applications should take precedence over web applications. For example, it would mean that installing Twitter Lite will never send a notification if Twitter is installed. In general, I'm worried about the Web Platform putting other platforms first but it may also be a very surprising behaviour for a user. Trying a web application (if they can install it) will sound completely broken because they already had the native application installed and might not realise it. There are also various privacy issues as these behaviour changes could be detected by the website and they would be able to more easily track users and know more about them.

Though, I think having Chrome look into those problems independently from the specification process would be interesting.

**Comment by mgiuca** [comment]
@kenchris :

> We could also make the precedence depend on the value of https://www.w3.org/TR/appmanifest/#prefer_related_applications-member

This would only apply to the notifications case. (prefer_related_applications already hints that the web app install prompt not be shown, so there would be no change there.) I agree, this could be a useful signal; if prefer_related_applications is false, you continue to get notifications because the developer has instructed us not to prioritize the native app over the web app. If it is true, we turn off web applications if the native app is installed, because the developer has asked to prioritize.

My concern with this is that it could incentivize the use of prefer_related_applications (to deduplicate notifications), which in turn results in fewer web app installs. Which is why we proposed it as a separate Boolean, so the developer can ask for notifications to be de-duplicated *if* the native app is installed, while still promoting the web app over the native app if neither is installed.

@mounirlamouri :

> In general, I'm worried about the Web Platform putting other platforms first but it may also be a very surprising behaviour for a user.

I'm worried about this too, but if we want to de-duplicate notifications, then this is the only direction we can do it. If the user doesn't have a native app installed, nothing will be different. If they do have the native app installed, then subsequently installing the web app will create a terrible notifications experience, so this approach allows installation of the web app without creating a broken experience.

> Trying a web application (if they can install it) will sound completely broken because they already had the native application installed and might not realise it.

"Completely broken" is an overstatement. This proposal will stop just one thing from working, notifications (which you will already be getting to your native app). The other thing we would disable is the install prompt, which doesn't affect the installed-app experience.

> There are also various privacy issues as these behaviour changes could be detected by the website and they would be able to more easily track users and know more about them.

I think this is minor. Firstly, the site will not easily be able to detect these changes, as there could be other reasons why notification permission is blocked, or install event is not firing. Secondly, if they do, they will only be able to detect that their own app is installed. They already have the knowledge that the user uses their native app.

**Comment by mounirlamouri** [comment]
> If they do have the native app installed, then subsequently installing the web app will create a terrible notifications experience, so this approach allows installation of the web app without creating a broken experience.

That's true, double notifications for sure must be annoying but why should we disable the notifications on the web application in this case? Isn't it a clear sign from the user that they want to try the web application if they installed it when they already had the native application installed?

> "Completely broken" is an overstatement. This proposal will stop just one thing from working, notifications (which you will already be getting to your native app). The other thing we would disable is the install prompt, which doesn't affect the installed-app experience.

I agree that it depends on the application. This said, it's probably very likely that if I installed one web application and the notifications are still fired on the native application, as a user, I will never use the web application as the engagement will go to the other one.

I'm also a bit worried about edge cases such as the native application being installed but technically not usable/used (not logged in, notifications disabled) which would lead to a weird experience.

More I think about it, more I think it will be hard to do the right thing auto-magically. Sounds like developers or users should deal with this as they are in control of the experience. Based on your initial comment, sounds like developers don't care as much as we hoped. Are users complaining about this? or are they finding solutions such as manually disabling notifications?

**Comment by kenchris** [comment]
Can't android be smart and detect that the same notification comes to different targets and actually ask the user? We have the exact same issue when installing the same PWA using two browsers, say Samsung Internet and Chrome (or even Chrome stable and Chrome beta).

**Comment by mgiuca** [comment]
Closing, because we're proceeding with [getInstalledRelatedApps](https://github.com/WICG/get-installed-related-apps).
