### ISSUE TITLE
Question about 'lang' and 'dir' members

### ISSUE THREAD

**Issue by Malvoz** [w3c/manifest#660]
What are the implications of using the `lang` and `dir` attribute members? Is there a downside to omitting these while still defining them in `<html lang="X" dir="Y">`?

**Comment by marcoscaceres** [comment]
The html ones apply to the HTML document, not to the manifest.

**Comment by marcoscaceres** [comment]
What we could say is that if the `lang` is missing, assume the manifest is in the document language.

**Comment by Malvoz** [comment]
@marcoscaceres 

> The html ones apply to the HTML document, not to the manifest.

Yes, but somehow I thought the manifest's `lang` and `dir `members also applied **to the HTML** document. Just as the other members (such as `short_name`) describes the HTML.

### The `dir` member
> Specifies the primary text direction **for the name, short_name, and description members**. Together with the lang member, it can help provide the correct display of right-to-left languages.
_https://developer.mozilla.org/en-US/docs/Web/Manifest_

> The dir member specifies the base direction for the directionality-capable members **of the manifest**.
https://w3c.github.io/manifest/#dir-member

Thanks, my bad.
