### ISSUE TITLE
Add optional `author` member

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [w3c/manifest#675]
Each app in Google Play, App Store, Microsoft Store, etc. has an owner/developer.

Using it, it's easy to find all the apps of this developer.

<img src="https://user-images.githubusercontent.com/870154/40287932-17ad94a2-5cf4-11e8-887b-3143ae50aadd.png" width=400>

What about adding optional `author`/`developer`/`publisher`/`owner` string member?

**Comment by marcoscaceres** [comment]
As a guiding principle, we only add manifest members that have some effect on the user agent itself (e.g., "short_name" is the label under the icon of an app, "icons" is one of the icon that the user taps on, "orientation" is how the app should be oriented when launched). 

Although author/developer/etc seems useful, it doesn't really serve any useful purpose once the app is installed. 

It's also really easy to forge. Thus, stores should verify the owner of apps by some other means - and not trust the manifest.

**Comment by marcoscaceres** [comment]
duplicate of https://github.com/w3c/manifest/issues/630

**Comment by FluorescentHallucinogen** [comment]
@marcoscaceres What about re-opening this issue?

> As a guiding principle, we only add manifest members that have some effect on the user agent itself

Are app stores that support publishing PWA (like Samsung Galaxy Store and Microsoft Store) user agents too or not? PWAs discovered automatically by search engine or submitted by URL and they use the info from manifest.

Also I believe the situation with browsers may change in the near future: browsers could expose more info from the manifest to the user in PWA install prompt like screenshots, categories, iarc_rating_id, etc. Including publisher.

@diekus @aarongustafson PTAL.

**Comment by marcoscaceres** [comment]
> Are app stores that support publishing PWA (like Samsung Galaxy Store and Microsoft Store) user agents too or not?

Not in the current specification. No. 

> Also I believe the situation with browsers may change in the near future: browsers could expose more info from the manifest to the user in PWA install prompt like description, screenshots, categories, iarc_rating_id, etc. Including publisher. Not only app icon and URL.

You are not wrong. But we add things to the standard "reactively": that is, a case would be made (as in the above case for `author`) and we would need commitment from 2 implementers to add it to the spec (i.e., we don't add things to the spec in the hope that user agents will make use of things). We want to avoid situations where new manifest members don't get used, and we are forced to remove things from the spec due to lack of implementer commitment. 

That is the current situation with `author`.

**Comment by FluorescentHallucinogen** [comment]
@marcoscaceres Ok, but what about `"iarc_rating_id"` field? Is it currently used by any user agent? I mean, what's the fundamental difference between `"iarc_rating_id"` and `"author"` from this point of view? As far I know, the `"description"`, `"screenshots"` and `"categories"` fields are also not used by the browser (not displayed to the user). :thinking:

**Comment by marcoscaceres** [comment]
We've initially didn't apply the rule consistently :( We you now find us in the terrible situation of taking things out of the spec (e.g., `beforeinstallprompt` is on the chopping block... iarc_rating_id might also end up there, but we kept it because the Microsoft store was using it... but I don't know if they still are).

**Comment by FluorescentHallucinogen** [comment]
@marcoscaceres I've opened https://crbug.com/1050311. :wink:

**Comment by marcoscaceres** [comment]
Thanks @FluorescentHallucinogen. Also shared your improved screens with our PWA folks within Mozilla.

**Comment by marcoscaceres** [comment]
I'll just note that it's potentially possible to pull site ownership information from the SSL cert too.  It might be more reliable than from the manifest.

**Comment by aarongustafson** [comment]
Just to note: We are still using IARC rating & screenshots (and will be even more soon).

**Comment by marcoscaceres** [comment]
Ok, author is super scary tho... authorship needs to be verified by the store (with heavy legal/punitive consequences). I'm imagining a case of a PWA faking the author to be "Google LLC", as above.
