### ISSUE TITLE
minimal-ui "similar to fullscreen" should read "similar to standalone"

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#677]
In https://www.w3.org/TR/appmanifest/#display-modes, it reads:

"minimal-ui: This mode is similar to fullscreen"

I assume this is a mistake, because minimal-ui extends upon "standalone" mode, not fullscreen. Can I quick-fix this?

**Comment by marcoscaceres** [comment]
The original minimal ui apps from iOS (going back 3-4 years ago) launched in full screen, and then some user action made the "minimal UI" appear. If that's changed, then it would be prudent to update the spec.

**Comment by mgiuca** [comment]
But was it full screen, or standalone? (Also, what browser was this? I didn't think Safari supported manifest until recently.)

I view the four modes as strict progressive enhancements (increasing the amount of non-client UI):

fullscreen > standalone > minimal-ui > browser

So minimal-ui being based on fullscreen seems a bit wrong.

**Comment by marcoscaceres** [comment]
> (Also, what browser was this? 

Safari that shipped with iOS 7.1... back in 2014. 

> I didn't think Safari supported manifest until recently.)

True - but the concepts were developed in coordination with folks from Apple (even though they didn't implement the spec, they were still providing input into the design). 

> I view the four modes as strict progressive enhancements (increasing the amount of non-client UI):
> fullscreen > standalone > minimal-ui > browser

Right, I think we originally viewed them as:

fullscreen > minimal-ui > standalone >  browser 

The reason being that an app in "minimal-ui", was that the app launched fullscreen, then some user gesture caused the UI to appear. Now, that might have changed since we spec'ed this, and it may make sense to change the order. 

Just describing why we made the decision in the first place back in ~2014.

**Comment by mgiuca** [comment]
> The reason being that an app in "minimal-ui", was that the app launched fullscreen, then some user gesture caused the UI to appear.

But what does "standalone" mean in that world? Does it mean more permanent UI is on screen than minimal-ui? The text implies that minimal-ui has more stuff in it than standalone.

Also the order is kind of fixed by the fallback chain (explicit in the spec):

fullscreen → standalone → minimal-ui → browser

Since that's the fallback chain, it would imply that each of those modes has a superset of the features of the previous:

fullscreen ⊂ standalone ⊂ minimal-ui ⊂ browser

On this topic, I found another sentence which might be a relic from this era:

"When the fullscreen display mode is applied, it is RECOMMENDED that the user agent provides the end-user a means to consult common information about the web application, such as the origin, start and/or current URL, granted permissions, and associated icon."

I feel like this recommendation shouldn't be specific to fullscreen. Since standalone shows a superset of the UI of fullscreen, it's weird that the above info is recommended in fullscreen but not standalone. Also our security team specifically requested this for standalone mode. Should I delete the qualifier?
