### ISSUE TITLE
beforeinstallprompt not firing automatically

### ISSUE THREAD

**Issue by Braj65** [w3c/manifest#680]
I want to add to my app "Add To home screen banner", I went through the manual
https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/#testing-the-app-install-banner

Have fulfilled the conditions
1) Manifest file
 {
	"name": "Project clean as pwa",
	"short_name": "Pro Clean",
	"icons":[
		{
			"src": "/icons/icons8-washing-machine-48.png",
			"type": "image/png",
			"sizes": "48x48"
		},
		{
			"src": "/icons/icons8-washing-machine-96.png",
			"type": "image/png",
			"sizes": "96x96"
		},
		{
			"src": "/icons/app-icon-192x192.png",
			"type": "image/png",
			"sizes": "192x192"
		},
		{
			"src": "/icons/icons8-washing-machine-480.png",
			"type": "image/png",
			"sizes": "480x480"
		},
		{
			"src": "/icons/icons8-washing-machine-512.png",
			"type": "image/png",
			"sizes": "512x512"
		}
	],
	"start_url":"/initial",
	"scope": "../",
	"display":"standalone",
	"orientation":"any",
	"background_color":"#fff",
	"theme_color":"#3f51b5",
	"description":"Simple dry clean description",
	"dir":"ltr",
	"lang":"en-US"
}

2) Registered service worker
if("serviceWorker" in navigator){
	navigator.serviceWorker.register('/sw.js')
	.then(function(){
		console.log("Service worker registered");
	});
};

3) Added fetch event handler in serviceworker file
self.addEventListener("fetch",function(event){
	event.respondWith(fetch(event.request));
});

4) Saving beforeinstallprompt event for later use
window.addEventListener("beforeinstallprompt",function(event){
	console.log("beforeinstallprompt fired");//this never appears after waiting for long
        event.preventDefault();
	event.prompt();
	deferredPrompt = event;
	return false;
});

5) Using the event later
function collectOrder(){
	console.log("Using the event ", deferredPrompt);//on call of the funtion the event comes undefined
	if(deferredPrompt){
		deferredPrompt.prompt();

		deferredPrompt.userChoice.then(function(choiceResult){
			console.log(choiceResult.outcome);
			if(choiceResult.outcome==="dismissed")
				console.log("User cancelled installation");
			else
				console.log("User added to homescreen");
		});
		deferredPrompt = null;
	};
}

6) The lighthouse test says the app is pass for "install banner"

Help me with if anything is missing.

**Comment by dominickng** [comment]
What browser are you using, which version, and on what OS? It's probably best to file a bug on the relevant bug tracker for the browser in question.

**Comment by aarongustafson** [comment]
@Braj65 You may just not be hitting the the user engagement threshold for some reason. You can test to see if that’s the case by visiting [enabling Bypass user engagement checks](chrome://flags/#bypass-app-banner-engagement-checks) in Chrome. That should trigger the prompt automatically.

**Comment by marcoscaceres** [comment]
Closing, as this appears to be a browser bug.

**Comment by Braj65** [comment]
@aarongustafson I tried with enabling 'Bypass user engagement checks in Chrome' flag. But the prompt didn't trigger after waiting for some time. Any other way you can think of ? Am i missing any other required condition apart from the ones i have mentioned in the description of this topic at the start of this page?

**Comment by dominickng** [comment]
@Braj65 please file a bug on crbug.com/new and cc dominickn@chromium.org. Ideally if you can provide a link to the site in question that will help us work out what is going on.
