### ISSUE TITLE
Manifast and Service Worker updateViaCache

### ISSUE THREAD

**Issue by ayumihamsaki** [w3c/manifest#690]
Hello,

I would just like to double check something.

In the Manifest Spec found here: https://www.w3.org/TR/appmanifest/#update_via_cache-member

You write the following:

`"update_via_cache": "imports"`

In the Service Worker Spec found here: https://w3c.github.io/ServiceWorker/#enumdef-serviceworkerupdateviacache

They write the following:

`"updateViaCache": "imports"`

Surely both should match exactly the same to avoid confusion and possible syntax errors? Or is it to avoid using Upper Case letters in JSON?

Going to add some extra links for info:

Google's use of it: https://developers.google.com/web/updates/2018/06/fresher-sw

Not sure if this issue is related: https://github.com/w3c/manifest/issues/641

I just wondered if writing a manifest like this would be correct:

```
"serviceworker": {
      "src": "/sw.js",
      "scope": "./",
      "updateViaCache": "imports"
},
```

Also I spoke to someone at Google about updateViaCache and they said that imports was set to default by every browser. Not sure if this is totally true, but maybe could add to the spec - if it is true?

**Comment by marcoscaceres** [comment]
> Surely both should match exactly the same to avoid confusion and possible syntax errors? Or is it to avoid using Upper Case letters in JSON?

At the W3C, we have established a convention for JSON to use underscores as separators. That's detailed in this API design guide for the w3c: 
https://w3ctag.github.io/design-principles/#casing-rules

> Also I spoke to someone at Google about updateViaCache and they said that imports was set to default by every browser. Not sure if this is totally true, but maybe could add to the spec - if it is true?

@kenchris, do you know?

**Comment by tomayac** [comment]
> Also I spoke to someone at Google about updateViaCache and they said that imports was set to default by every browser. Not sure if this is totally true, but maybe could add to the spec - if it is true?

Quoting from @jeffposnick's [recent post] (emphasis mine):

(https://developers.google.com/web/updates/2018/06/fresher-sw): 
*"Starting in 68, the HTTP cache will be ignored when requesting updates to the service worker script, so existing web applications may see an increase in the frequency of requests for their service worker script. **Requests for importScripts will still go via the HTTP cache.** But this is just the default—a new registration option, updateViaCache is available that offers control over this behavior."*

**Comment by ayumihamsaki** [comment]
@tomayac no quoting from this issue found here: https://github.com/GoogleChrome/workbox/issues/1519

> The ideal scenario (honor the browser cache for importScripts(), ignore the browser cache for /service-worker.js) is the new default fore Chrome 68 and later, and is also the default for Safari, Edge, and recent versions of Firefox.
