### ISSUE TITLE
Should appinstalled and beforeinstallprompt events be optional?

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#699]
Spinning out from Fyrd/caniuse#4357. @marcoscaceres 

Currently the spec mandates that:

* `appinstalled` event is fired when the application install completes successfully, and
* `beforeinstallprompt` event is fired before the user agent shows an automated install prompt.

The former is a strong requirement. The latter is technically optional (because the user agent can of course never show an automated install prompt, or theoretically show some UI for installing the site but not call it an "automated install prompt"). Should we make these truly optional in the spec, by changing the MUSTs to MAYs?

Note that even if a user agent never fires a `beforeinstallprompt` event, it is still required to have the `BeforeInstallPromptEvent` object in the `Window` namespace, as well as the `onappinstalled` and `onbeforeinstallprompt` attribute handlers.

My opinion is that the current spec wording is fine:

* User agents should fire `appinstalled` if the app is installed from within the browser tab (obviously not if it's installed externally, such as through the Microsoft store).
* User agents are not required to fire `beforeinstallprompt`.
* User agents should still make `BeforeInstallPromptEvent`, `onappinstalled` and `onbeforeinstallprompt` visible, even if they never intend to fire these events.

So a user agent that makes those three names available, and fires `appinstalled`, would be conforming.

**Comment by kenchris** [comment]
> User agents should fire appinstalled if the app is installed from within the browser tab (obviously not if it's installed externally, such as through the Microsoft store).

The event could be postponed to first launch

**Comment by marcoscaceres** [comment]
If the events should be optional or not is somewhat a different concern to whether there will ever be two ore more implementations of a particular feature. As such, the prudent thing to do might be to mark the events at risk. Like you said:

> User agents should still make BeforeInstallPromptEvent, onappinstalled and onbeforeinstallprompt visible, even if they never intend to fire these events.

That would be the true indicator of conformance. Right now, we are not in a great place because we've failed to get more than one browser engine to support the events (even on an optional basis).

**Comment by marcoscaceres** [comment]
My proposal would again be to explicitly mark the events at risk and do one more round of lobbying to see if we can get them implemented in Safari or Firefox. I'l talk to the Firefox team - but we might need to face the reality that after ~2 years we don't have these events in, we might need to remove them from the spec.

**Comment by christianliebel** [comment]
TPAC 2019:
- `beforeinstallprompt`: make it optional (see https://github.com/w3c/manifest/pull/797)
- `appinstalled`: @beverloo checks metrics

**Comment by aarongustafson** [comment]
Closing per TPAC discussion ([notes](https://github.com/w3c/manifest/issues/782#issuecomment-533363985)).
