### ISSUE TITLE
Main index not updating?!

### ISSUE THREAD

**Issue by Zibri** [w3c/manifest#704]
In my manifest I have put:

"start_url": ".",

result: the app main html (which is index.html on the server) is never updated.

anyway, is there a way to force a refresh of all files loaded by the app when I update the main site?
only the serviceworker seem to update correctly.

**Comment by patrickkettner** [comment]
Hey @Zibri!
This is the repo for the spec, rather than issues with implementing PWAs. I'd suggest trying stackoverflow to get help with this kind of an issue.

Thank being said, it sounds like you should look at how you are caching the index page in your service worker.

**Comment by Zibri** [comment]
I am not caching anything. (I'm still in testing)
Anyway I found a solution: just issuing location.reload(true) in a webapp refreshes everything from the server! Finally.

**Comment by mgiuca** [comment]
This is likely an issue with the service worker, not the manifest.

Using `location.reload(true)` is a hack that's likely not addressing the core problem. You should make sure your service worker isn't serving old content.
