### ISSUE TITLE
Control over webapp installation & launch

### ISSUE THREAD

**Issue by frlinw** [w3c/manifest#705]
I want to discuss about the opportunity to give more control (to the developer) on what to do after webapp installation.

Current UA behavior after webapp installation:
- None of android browsers open the installed WebApp
    - Firefox, Edge: you have the possibility to drag WebApp icon to homescreen manually
    - Chrome automatically add the icon to homescreen (ie. the end user feels like nothing happened, he is kept on the browser, there is just a background notification)
- Chrome desktop close the tab and open the installed webapp immediately

With [chrome management API](https://developer.chrome.com/extensions/management) (which extends [management API](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/management)) as a source of inspiration:
- [launchType](https://developer.chrome.com/extensions/management#type-LaunchType): know if the app is launched as a tab or as a window
- [launchApp()](https://developer.chrome.com/extensions/management#method-launchApp): open the app (edit: on user gesture only)

Use case description:
![image](https://user-images.githubusercontent.com/11896237/48718520-de246780-ec1b-11e8-862d-7affed689ef2.png)

**Comment by dominickng** [comment]
I think the "trigger `appinstalled` on every page load after installation" usecase is encompassed by the [service worker launch event proposal](https://wicg.github.io/sw-launch/explainer.html), which will give installed sites control over their windows (@mgiuca)

Giving the developer control over what happens immediately after an installation (without a user navigation within the site) seems user-hostile to me.

**Comment by frlinw** [comment]
> Giving the developer control over what happens immediately after an installation (without a user navigation within the site) seems user-hostile to me.

Sure!
It follows the model of BeforeInstallPromptEvent.prompt() ie. allow the developer to call AppInstalledEvent.open() on user gesture only (tap/click) (that's why I talked about "open app button" in the use case description)

**Comment by frlinw** [comment]
Chrome management API https://developer.chrome.com/extensions/management which can be a source of inspiration.

**Comment by marcoscaceres** [comment]
Closing as out of scope for now.

**Comment by frlinw** [comment]
You can trigger the install button in userland
![image](https://user-images.githubusercontent.com/11896237/61868593-00246700-aeda-11e9-8e7a-4a5cd456cde7.png)
You can't trigger the (new in Chrome) "open with" button in userland
![image](https://user-images.githubusercontent.com/11896237/61868668-2ba75180-aeda-11e9-96a8-1ae520790faf.png)
these 2 actions are related and could be supported by the spec.

It's different from the service worker launch proposal linked by @dominickng. In the proposal, the launch event is designed `to prevent certain incoming navigations` so it's not controllable by the webauthor.
Note: Here I'm targeting future navigation and not 'after installation' action

I know there is already a UA adoption issue with beforeinstallprompt, what are the reasons to not implement it (for firefox at least)? Is it in a status quo state?

**Comment by mgiuca** [comment]
I think there's much less value in being able to programmatically trigger "open with" than "install".

The reason we allow programmatically triggering install is to give sites an opportunity to ask the user to commit to having the app around on their home screen, something that the user might not naturally discover or think about on their own.

Once an app is installed, the easiest way to open it is from the home screen. If the user is in the website, it's because they got there from a normal web navigation. It's helpful to have UI to switch into "app mode" but I don't think we want sites to be able to constantly ask the user to switch into app mode. (And the rejection model is weirder than BeforeInstallPrompt; if the user rejects switching into app mode once, does that mean they don't want to be asked again?)

**Comment by frlinw** [comment]
@mgiuca For the user experience, both have value, why was it implemented in Chromium/Firefox UI if not ?

You are probably right for the mobile plateform but it's not obvious for desktop.
During normal in-browser navigation, if you are used to go to a webapp (already installed) the only thing telling you it's installed is this icon in the address bar. 
But it's a new feature and most of the time, people don't look at the address bar zone except if they are searching for a specific known feature. So what is the discovering strategy? What if the desktop shortcut is removed?
If the user visit the webapp (in browser) and can see in a corner `hey, you already installed the app, use it! [open in app button]`, a click will open the "open with" tooltip (so he'll notice the new icon and discover the feature) and chose to open in app or cancel.

> I don't think we want sites to be able to constantly ask the user to switch into app mode

Visually, it could just replace the install button, same requirement (user gesture), same [design patterns](https://developers.google.com/web/updates/2019/06/pwa-install-patterns).

> if the user rejects switching into app mode once, does that mean they don't want to be asked again

It's not a permission but just a shortcut to open the "open with" tooltip. Webauthor don't even need to know if the user closed it.
It's the result of a user gesture, if they don't want to be asked again, they don't click.
