### ISSUE TITLE
service worker sections: mixed up inputs and outputs, some suggestions

### ISSUE THREAD

**Issue by lodott** [w3c/manifest#706]
Based on the latest editor's draft:

* In 7.2.13 a serviceworker variable is named as input for 8.11 but is neither defined nor needed in 8.11.
* Likewise in 8.11 only the manifest entry is mentioned as input, but not the manifest url needed in 8.11.2
* in 8.11.4 the manifest url is not mentioned as input for 11.2, but expected there

I would have made a pull request for this, but I was not sure which branch (gh-pages?) to fork for that.

Suggestion for 8.11: the processed scope's origin could be checked against the origin of the processed src member (otherwise the service worker will not be registered, see https://w3c.github.io/ServiceWorker/#register-algorithm)

Also the sw scope should normally be within the directory of the sw src path, though this restriction can be changed via HTTP Header on the service worker script (https://w3c.github.io/ServiceWorker/#service-worker-script-response). Nonetheless a note to that effect may be of interest here.

**Comment by kenchris** [comment]
We use gh-pages yes

**Comment by marcoscaceres** [comment]
The service_worker member was removed by #825.
