### ISSUE TITLE
Codify that the related_applications member should be consulted when installing a web application

### ISSUE THREAD

**Issue by dominickng** [w3c/manifest#707]
Currently, the [related_applications](https://www.w3.org/TR/appmanifest/#related_applications-member) member is very generally specified. Perhaps we should tighten the requirements on UAs here and enforce that UAs SHOULD only offer a web application for installation if the related_applications member is empty OR if none of the listed and compatible `related_applications` are installed.

This is independent of [prefer_related_applications](https://www.w3.org/TR/appmanifest/#prefer_related_applications-member), which tells the UA that a web application should never be offered for installation over the top of a related application (even if the related application ISN'T installed).

A question here is whether sites have listed `related_applications` but NOT specified `prefer_related_applications` to be true. Is there any reason why sites might do this, but NOT consider their web app and related app interchangeable? One example I've found is [Google Maps](https://www.google.com/maps/preview/pwa/manifest), but there it's probably fine to say that the native app and web app are interchangeable. I'm not sure if this holds in general so I'm interested in hearing thoughts.

I'm happy to draft some spec language if people think this requirement is sound.

**Comment by mgiuca** [comment]
I think this is a dupe of #658 (more generally addressing this as well as suppressing notifications; essentially the continuation of `getInstalledRelatedApplications`).

The three approaches outlined there are:

1. [spec] Introduce new Boolean members to let the site request suppression if the related application is installed, or
2. [spec] Require (or SHOULD) that the site suppress if the related application is installed, or
3. [implementations] Individual user agents can suppress if the related application is installed (possibly with a MAY clause in the spec).

**Comment by dominickng** [comment]
Indeed, thanks for pointing that issue. I'll close this one in favour of that.
