### ISSUE TITLE
The name and icon from the web app manifest is not getting displayed when payment handler installed from an iframe which is in another domain.

### ISSUE THREAD

**Issue by rakhi16** [w3c/manifest#708]
The name and icon from the web app manifest is not getting displayed when payment handler installed from an iframe which is in another domain. It is displayed only when the payment handler is installed from the top-level context.

For instance, let's assume:
Top level page is in domain – http://www.xyz.com
Manifest json and service worker are in different domain: https://www.abc.com
Manifest json URL - https://www.abc.com/manifest.json
Service worker URL - https://www.abc.com/sw.js

Top level page includes the iframe to install service worker and the link tag for manifest json.
Eg: http://www.xyz.com/index.html
<!doctype html>
<meta charset="utf-8">
<title>Toplevel</title>
<link rel="manifest" href=" https://www.abc.com/manifest.json">
<head></head>
<body>
<iframe src=" https://www.abc .com/installer.html" allowpaymentrequest></iframe>
</body>

Manifest json file looks like:
{
  "name": "Payment ABC",
  "icons": [   {
      "src": "icon.png",
      "sizes": "600x600",
      "type": "image/png"   }  ],
  "serviceworker": {
    "src": " sw.js",
    "use_cache": false
  }
}

**Comment by marcoscaceres** [comment]
@rsolomakhin, Chrome issue maybe? 

(Closing, as this doesn’t seem to be a spec issue- manifest spec doesn’t know anything about Payment Handlers)

**Comment by rsolomakhin** [comment]
Hey, this is a Chrome issue https://crbug.com/812297. We're working on fixing it.
