### ISSUE TITLE
Providing more than one iarc_rating_id

### ISSUE THREAD

**Issue by christianliebel** [w3c/manifest#712]
The property `iarc_rating_id` currently allows specifying a single IARC rating ID. However, IARC issues age rating certificates for one particular _storefront_ (e.g., Google Play) only. So as a result, you’d have to duplicate the entire manifest to provide a different certificate ID for a different app store or catalog. Is this the intended workflow?

Alternatively, `iarc_rating_id` could take an array of objects, which map a storefront key (e.g., a platform identifier) to a specific IARC certificate ID. This could be an additional method to maintain backward-compatibility with developers that are already using `iarc_rating_id`.

**Proposal**
```
{
  "iarc_rating_id": {
    "play": "baea39ae-b239-415a-a993-a633cd66e659",
    "https://myawesomecatalog.com": "e2b13b04-6516-4e37-b9bd-af6ae16f6838"
  }
}
```

**Comment by marcoscaceres** [comment]
I agree, this might be good to turn this into an object map with known keys and URLs.   

Does the play store actually support `iarc_rating_id`?

**Comment by kenchris** [comment]
Yes, Google Play is part of it

![image](https://user-images.githubusercontent.com/1101339/44712010-177f8800-aab0-11e8-9512-4d6c11a0b042.png)

but this is supposed to be a global rating, so you have one that applies to all stores, not one per store. So unless you are not rating the same thing (you should because this ties to one PWA) then there is only the need for one:

https://www.globalratings.com/for-developers.aspx

![image](https://user-images.githubusercontent.com/1101339/44712194-86f57780-aab0-11e8-8999-5caa611de513.png)

I would like to understand the "in some cases" though...

**Comment by christianliebel** [comment]
> I would like to understand the "in some cases" though...

@kenchris I’ve sent an email to the info@… address of IARC. Let’s see!

> So unless you are not rating the same thing (you should because this ties to one PWA) then there is only the need for one

The feature set of Progressive Web Apps may vary on different platforms. On Windows for instance, installed PWAs can use native UWP APIs (which might not have a web platform pendant). Thus the age rating might also vary. So it could be helpful to have at least an option for specifying different certification codes per storefront. What do you think?

**Comment by marcoscaceres** [comment]
Ok, but what I was asking was if Google Play Store supports web manifest?

**Comment by kenchris** [comment]
> Ok, but what I was asking was if Google Play Store supports web manifest?

Not at this point no :-) but it should be possible to generate the APK from it (there are indications that that is happening in some cases, like Google Maps Go which has some custom properties in the manifest)

**Comment by kenchris** [comment]
> @kenchris I’ve sent an email to the info@… address of IARC. Let’s see!

I also pinged @patrickkettner on Twitter if he known anyone internally in MS with relations in or knowledge about IARC as MS were the one who added this feature

**Comment by marcoscaceres** [comment]
@kenchris ok, great. Yeah, if only Microsoft supports it, we can see if it's possible to change it... however, it no other store supports this, then we might not need to change anything.

**Comment by christianliebel** [comment]
@marcoscaceres @kenchris Here’s the reply:

> Hi Christian,
>  
> We would defer to MS on the technical aspects of this, but our understanding is that “in some cases” means two things -
>  
> The feature is supported by the storefront.
> The product is the same across storefronts.
>  
> Please feel free to post this response in the thread.
>  
> IARC

**Comment by kenchris** [comment]
So as it is the same product (unless the PWA totally changes due to UA snipping) then there should be just one value.

I still think this might deserve a note in the spec. Feel like creating something like that Christian?

**Comment by christianliebel** [comment]
@kenchris Yep! I’ll close this issue and send in a PR within the next couple of days.
