### ISSUE TITLE
MIME type in HTML <link type="application/manifest+json" rel="manifest">

### ISSUE THREAD

**Issue by kael** [w3c/manifest#721]
Currently a WebApp manifest is discoverable using the HTML `<link>` header:
```html
<link rel="manifest"/>
```
I've come across the [Readium Web Publication Manifest](https://github.com/readium/webpub-manifest) which _« is an attempt to standardize a JSON based manifest format »_ for collections discovery, in the context of [WebPublications](https://www.w3.org/TR/wpub/) - noting that currently _« [The precise format of how such a manifest is stored is not considered in this document. ](https://w3c.github.io/dpub-pwp-ucr/#terminology) »_

To make such collections discoverable, Readium [proposes](https://github.com/readium/webpub-manifest#discovering-a-manifest) the following HTML `<link>` header:
```html
<link href="manifest.json" rel="manifest" type="application/webpub+json">
```
While writing a parser for HTML `<meta>` and `<link>` tags, I'm now wondering how I should handle those cases.

Which brings me to asking, shouldn't the MIME type `application/manifest+json` be explicitly added in the HTML `<link>` element to make it clearly distinguishable, unequivocal ?
```html
<link type="application/manifest+json" rel="manifest">
```

**Comment by dominickng** [comment]
It looks to me like Web Publications currently proposes using `<link rel="publication">`, not `<link rel="manifest">` (https://w3c.github.io/wpub/#wp-linking).

In fact, https://github.com/w3c/wpub/issues/132 suggests that they are considered just extending the web app manifest and retiring their separate manifest file. Either way, an explicit MIME type doesn't seem necessary for us, and I'm not even sure it's semantically valid to distinguish two `<link rel>` tags by the type alone. - the relationship is still indicated to be the same via the `rel` member

Readium appears to not be following the Web Publications spec at this point - I would suggest opening an issue with them to see why they don't align.

**Comment by kael** [comment]
Indeed, I've missed the `<link rel="publication">` proposal, but it's still unclear.

Regarding the use of a specific MIME type for webapps manifests, it'd make sense as:
- it'd be aligned with the way web servers can [optionally add a `Link`header](https://w3c.github.io/manifest/#media-type-registration) with a  type `application/manifest+json` ;
- it'd let free the `<link rel='manifest'>` as generic manifests class, similarly to `<link rel="alternate" type="application/[atom|rdf|rss]+xml">`, and would hence make it unequivocal for webapps ;
- but it'd partially break compatibility.

Seems to me there could be some clarification between the groups about the definition and use of `<link rel="manifest">`.

Anyway, that was my 2 cents.

Regarding parsing, for now I'll filter `<link rel='manifest'>` based on the lack of the `type` attribute to distinguish webapps manifests from potential others.

**Comment by marcoscaceres** [comment]
Given this specification "owns" the `rel='manifest'` relationship, and `application/manifest+json` is implied (or explicit in either the HTTP response or in the `link` element itself), I don't think there is a case ambiguity.
