### ISSUE TITLE
API to get details about browser heuristics.

### ISSUE THREAD

**Issue by photopea** [w3c/manifest#727]
I tried to listen to "beforeinstallprompt" event on my website www.Photopea.com, and show the Install button at More - Install Photopea.

Many of my users complain, that the button never becomes active (my app never detects "beforeinstallprompt") and I have absolutely no idea what is the reason. I would like to tell my users some instructions, how to install my app, but I have no idea which criterias of the browsers heuristic have not been met.  See [here](https://www.facebook.com/photopea/photos/a.1703140446613703/2120885974839146/?type=1&theater)

When the browser does not qualify the site appropriate for installing, could there be an API for a browser to tell the website a reason of this? So then, I could tell my users "Reload the webpage three times", "Make 666 clicks in a website", "Wait 3 minutes and make another click", "Make 5 more visits in the next 24 hours with at least 1 hour delay between them", etc.

It feels really strange and sad, that my website does not work the same way for every visitor, and I can not do anything about it.

**Comment by frlinw** [comment]
beforeinstallprompt is not standard and only supported by chrome
https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent
Instead of changing the state of your install button, you should show it only if the event is triggered.

Indeed, the install process needs [features](https://github.com/w3c/manifest/issues/705) & standardization

**Comment by photopea** [comment]
@frlinw But why don't you simplify it all? The website just calls window.install() and the browser shows the install dialog?

**Comment by frlinw** [comment]
To be honest, for now I don't care about "the way to do it", if I can do it, it's fine. There is just a lack of browser support.
about the "why", you'll probably find some answers on your other thread https://github.com/w3c/manifest/issues/627

**Comment by marcoscaceres** [comment]
closing as no actionable item here.
