### ISSUE TITLE
Broken fragments in spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#735]
We have a bunch we need to fix: 
https://validator.w3.org/checklink?uri=https://www.w3.org/TR/appmanifest/&recursive=on

error Lines: 3330, 5235 https://heycam.github.io/webidl/
Status: 200 OK
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://heycam.github.io/webidl/#sequence (line 3330)
error Lines: 4949, 5235 https://www.w3.org/TR/css-syntax-3/
Status: 200 OK
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://www.w3.org/TR/css-syntax-3/#parse-component-value (line 4949)
error Lines: 2609, 2620, 5235 https://tc39.github.io/ecma262/
Status: 200 OK
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://tc39.github.io/ecma262/#sec-15.12.2 (lines 2609, 2620)
error Lines: 2480, 4986, 5235 https://fetch.spec.whatwg.org/
Status: 200 OK
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://fetch.spec.whatwg.org/#concept-request-context (lines 2480, 4986)
error Lines: 1654, 1897, 1901, 1902, 1903, 2010, 2466, 4855, 4856, 4857, 4999, 5003, 5007, 5010, 5014, 5017, 5020, 5024, 5027, 5031, 5034, 5037, 5040, 5044, 5047, 5051, 5055, 5059, 5062, 5065, 5068, 5071, 5074, 5078, 5081, 5085, 5088, 5092, 5096, 5100, 5103, 5107, 5111, 5114, 5118, 5122, 5125, 5128, 5235 https://html.spec.whatwg.org/multipage/
Status: 200 OK
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://html.spec.whatwg.org/multipage/#the-meta-element (line 5068)
https://html.spec.whatwg.org/multipage/#event-handler-idl-attributes (line 5122)
https://html.spec.whatwg.org/multipage/#allowed-to-navigate (line 5003)
https://html.spec.whatwg.org/multipage/#networking-task-source (line 5055)
https://html.spec.whatwg.org/multipage/#origin (line 5062)
https://html.spec.whatwg.org/multipage/#the-area-element (line 5071)
https://html.spec.whatwg.org/multipage/#top-level-browsing-context (line 5010)
https://html.spec.whatwg.org/multipage/#the-element's-base-url (line 5114)
https://html.spec.whatwg.org/multipage/#attr-link-sizes (line 5100)
https://html.spec.whatwg.org/multipage/#navigate (line 5024)
https://html.spec.whatwg.org/multipage/#unordered-set-of-unique-space-separated-tokens (line 5020)
https://html.spec.whatwg.org/multipage/#workertype (line 5128)
https://html.spec.whatwg.org/multipage/#the-a-element (line 5065)
https://html.spec.whatwg.org/multipage/#concept-origin-opaque (lines 2466, 5014)
https://html.spec.whatwg.org/multipage/#rel-icon (line 5085)
https://html.spec.whatwg.org/multipage/#attr-meta-name (line 5074)
https://html.spec.whatwg.org/multipage/#queue-a-task (line 5059)
https://html.spec.whatwg.org/multipage/#delay-the-load-event (line 5040)
https://html.spec.whatwg.org/multipage/#attr-link-rel (line 5047)
https://html.spec.whatwg.org/multipage/#eventhandler (lines 1902, 1903, 4856, 4857)
https://html.spec.whatwg.org/multipage/#same-origin (lines 5017, 5111)
https://html.spec.whatwg.org/multipage/#concept-link-obtain (line 5051)
https://html.spec.whatwg.org/multipage/#tree-order (line 5044)
https://html.spec.whatwg.org/multipage/#active-document (line 2010)
https://html.spec.whatwg.org/multipage/#valid-non-negative-integer (line 5096)
https://html.spec.whatwg.org/multipage/#the-link-element (line 5031)
https://html.spec.whatwg.org/multipage/#ascii-case-insensitive (line 5088)
https://html.spec.whatwg.org/multipage/#window (lines 1654, 1897, 1901, 4855)
https://html.spec.whatwg.org/multipage/#meta-application-name (line 5078)
https://html.spec.whatwg.org/multipage/#the-title-element (line 5081)
https://html.spec.whatwg.org/multipage/#queue-a-post-load-task (line 5118)
https://html.spec.whatwg.org/multipage/#linkTypes (line 5034)
https://html.spec.whatwg.org/multipage/#in-parallel (line 5125)
https://html.spec.whatwg.org/multipage/#valid-mime-type (line 5107)
https://html.spec.whatwg.org/multipage/#completely-loaded (line 4999)
https://html.spec.whatwg.org/multipage/#replacement-enabled (line 5027)
https://html.spec.whatwg.org/multipage/#concept-link-type-sniffing (line 5103)
https://html.spec.whatwg.org/multipage/#attr-link-sizes-any (line 5092)
https://html.spec.whatwg.org/multipage/#external-resource-link (line 5007)
https://html.spec.whatwg.org/multipage/#attr-link-media (line 5037)
error Line: 1030 https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webapplicationmanifest/
Status: 401 Unauthorized
The link is not public and the actual resource is only available behind authentication. If not already done, you could specify it.

info Line: 1108 mailto:public-webapps@w3.org
Status: (N/A) Access to 'mailto' URIs has been disabled
Accessing links with this URI scheme has been disabled in link checker.

info Line: 4785 https://github.com/SchemaStore/schemastore
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 1020 https://github.com/w3c/manifest/
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 2932 https://github.com/pwa-builder/ManifoldJS/issues/42
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

Broken fragments:
https://github.com/pwa-builder/ManifoldJS/issues/42#issuecomment-100335570 (line 2932)
info Line: 2047 https://github.com/PaulKinlan
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 4702 https://github.com/w3c/manifest/issues/97
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 1101 https://github.com/w3c/manifest//issues
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 4118 https://github.com/w3c/manifest/wiki/Platforms
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 4784 https://github.com/SchemaStore/schemastore/issues/
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 2931 https://github.com/w3c/manifest/issues/?q=is%3Aissue+is%3Aopen+label%3A%22enhancement%22
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 1022 https://github.com/w3c/manifest/issues/
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Lines: 1094, 4657 https://github.com/w3c/manifest/issues
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 4783 https://github.com/madskristensen
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Lines: 4644, 4672 https://github.com/w3c/manifest/wiki/Extensions-Registry
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 1034 https://webkit.org/b/158205 redirected to https://bugs.webkit.org/show_bug.cgi?id=158205
Status: 301 -> (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 1024 https://github.com/w3c/manifest/commits/gh-pages
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 2722 https://github.com/w3c/manifest/issues/?q=is%3Aissue+is%3Aopen+label%3A%22Feature+Request%22
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 1032 https://bugzil.la/997779 redirected to https://bugzilla.mozilla.org/show_bug.cgi?id=997779
Status: 301 -> (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 1026 https://github.com/w3c/manifest/pulls/
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 2722 https://github.com/w3c/manifest/issues/446
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 2047 https://github.com/w3c/manifest/issues/332
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

Broken fragments:
https://github.com/w3c/manifest/issues/332#issuecomment-83960468 (line 2047)
info Line: 2931 https://github.com/w3c/manifest/issues/380
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 3466 https://github.com/w3c/manifest/wiki/Categories
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 2047 https://github.com/w3c/manifest/issues/363
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

info Line: 2029 https://github.com/w3c/manifest/issues/646
Status: (N/A) Forbidden by robots.txt
The link was not checked due to robots exclusion rules. Check the link manually.

error Line: 1028 https://www.chromestatus.com/feature/6488656873259008
Status: 405 Method Not Allowed
The server does not allow HTTP HEAD requests, which prevents the Link Checker to check the link automatically. Check the link manually.

error Line: 1039 https://caniuse.com/
Status: 406 Not Acceptable
The server isn't capable of responding according to the Accept* headers sent. This is likely to be a server-side issue with negotiation.

Broken fragments:
https://caniuse.com/#feat=web-app-manifest (line 1039)
List of redirects

The links below are not broken, but the document does not use the exact URL, and the links were redirected. It may be a good idea to link to the final location, for the sake of speed.

warning Line: 1016 https://google.com/ redirected to https://www.google.com/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4781 http://schemastore.org/ redirected to http://schemastore.org/json/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 1016 https://intel.com/ redirected to https://www.intel.com/content/www/us/en/homepage.html
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 1016 https://microsoft.com/ redirected to https://www.microsoft.com/en-us/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4381 https://www.ietf.org/iesg/ redirected to https://www.ietf.org/about/groups/iesg/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

**Comment by marcoscaceres** [comment]
Will fix with xref...

**Comment by marcoscaceres** [comment]
Actually, will leave this open and close with a PR.

**Comment by aarongustafson** [comment]
Working on a new test of these. Will submit a PR.

**Comment by aarongustafson** [comment]
The missing Opera logo in the CSS appears to be a ReSpec issue.

**Comment by aarongustafson** [comment]
> Broken fragments:
https://fetch.spec.whatwg.org/#concept-request-context (line 5263)

It’s hard to tell if this should be a reference to DOM context instead. Fetch does not have its own context definition anymore.

**Comment by aarongustafson** [comment]
> Lines: 2880, 2891, 5505 https://tc39.github.io/ecma262/ redirected to https://tc39.es/ecma262/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated to point to the more recent URI.

This is another ReSpec issue I think.

**Comment by aarongustafson** [comment]
> Broken fragments:
https://html.spec.whatwg.org/multipage/#attr-link-media (line 5311)
https://html.spec.whatwg.org/multipage/#allowed-to-navigate (line 5280)
https://html.spec.whatwg.org/multipage/#active-document (line 2246)
https://html.spec.whatwg.org/multipage/#ascii-case-insensitive (line 5363)
https://html.spec.whatwg.org/multipage/#networking-task-source (line 5329)
https://html.spec.whatwg.org/multipage/#external-resource-link (line 5284)
https://html.spec.whatwg.org/multipage/#meta-application-name (line 5353)
https://html.spec.whatwg.org/multipage/#tree-order (line 5318)
https://html.spec.whatwg.org/multipage/#queue-a-post-load-task (line 5390)
https://html.spec.whatwg.org/multipage/#top-level-browsing-context (line 5287)
https://html.spec.whatwg.org/multipage/#linkTypes (line 5308)
https://html.spec.whatwg.org/multipage/#delay-the-load-event (line 5314)
https://html.spec.whatwg.org/multipage/#event-handler-idl-attributes (line 5394)
https://html.spec.whatwg.org/multipage/#the-area-element (line 5346)
https://html.spec.whatwg.org/multipage/#valid-mime-type (line 5379)
https://html.spec.whatwg.org/multipage/#replacement-enabled (line 5301)
https://html.spec.whatwg.org/multipage/#concept-link-obtain (line 5325)
https://html.spec.whatwg.org/multipage/#attr-link-rel (line 5321)
https://html.spec.whatwg.org/multipage/#queue-a-task (line 5333)
https://html.spec.whatwg.org/multipage/#in-parallel (line 5397)
https://html.spec.whatwg.org/multipage/#attr-link-sizes-any (line 5367)
https://html.spec.whatwg.org/multipage/#the-meta-element (line 5343)
https://html.spec.whatwg.org/multipage/#valid-non-negative-integer (line 5371)
https://html.spec.whatwg.org/multipage/#the-element's-base-url (line 5386)
https://html.spec.whatwg.org/multipage/#the-a-element (line 5339)
https://html.spec.whatwg.org/multipage/#attr-meta-name (line 5349)
https://html.spec.whatwg.org/multipage/#the-title-element (line 5356)
https://html.spec.whatwg.org/multipage/#the-link-element (line 5305)
https://html.spec.whatwg.org/multipage/#origin (line 5336)
https://html.spec.whatwg.org/multipage/#concept-link-type-sniffing (line 5375)
https://html.spec.whatwg.org/multipage/#same-origin (lines 5291, 5383)
https://html.spec.whatwg.org/multipage/#unordered-set-of-unique-space-separated-tokens (line 5294)
https://html.spec.whatwg.org/multipage/#navigate (line 5298)
https://html.spec.whatwg.org/multipage/#workertype (line 5400)
https://html.spec.whatwg.org/multipage/#rel-icon (line 5360)

I *think* these are all broken because WHATWG attempts to resolve anchors in the multipage rendering of the spec via JavaScript.

**Comment by marcoscaceres** [comment]
ReSpec's "xref" support should be able to deal with that. I'll try to send some incremental fixes.

**Comment by marcoscaceres** [comment]
These are now fixed. There is a few issues where we are referencing concepts and algorithms not exported from various specs, but I'll deal with those separately.
