### ISSUE TITLE
is there a new pwa titlebar feature? if so how can it be removed?

### ISSUE THREAD

**Issue by inspectaTech** [w3c/manifest#745]
New a2hs requests display a pwa with a titlebar. My previous experience was of a display with a more 'native feel' because standalone display didn't include any browser or app window ui.  Now this title bar is displayed at startup and my design no longer fits on the screen. Am i missing something in the manifest to turn this off?

![screenshot_20181202-085137](https://user-images.githubusercontent.com/19675189/49340572-aea82e80-f60f-11e8-8d04-5d02ce3b3f15.jpg)

**Comment by g-ortuno** [comment]
Not really a spec issues so I would open a bug with the appropriate browser.

(That said, in Chrome we show that UI when the site navigates off-scope; are you navigating off-scope? There is also a [bug](https://crbug.com/861618) where navigating off scope and then navigating back leaves that UI up even though it should be hidden.)

**Comment by dominickng** [comment]
As @g-ortuno said, you should file a bug with the appropriate browser (it looks like Chrome to me, but I'm not 100% sure). If it's Chrome, please cc me and I can make sure it's routed appropriately.

**Comment by inspectaTech** [comment]
thanks, will do.
