### ISSUE TITLE
Color processing steps are incorrect

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#760]
We currently rely on [[CSS-SYNTAX-3]] "parse a component value", but that's an internal algorithm that's participating in a larger parser... it also skips of preconditions that the parser requires. 

We've [asked the CSS working group for guidance](https://lists.w3.org/Archives/Public/www-style/2019Apr/0014.html).

**Comment by SimonSapin** [comment]
Assuming the input is Unicode (with bytes you’d first [decode](https://drafts.csswg.org/css-syntax/#input-byte-stream) to Unicode), parsing should go something like:

* [Preprocessing the input stream](https://drafts.csswg.org/css-syntax/#input-preprocessing),
* Then [Tokenization](https://drafts.csswg.org/css-syntax/#consume-token),
* Then [Parse according to the grammar](https://drafts.csswg.org/css-syntax/#parse-grammar) of [`<color>`](https://drafts.csswg.org/css-color/#typedef-color), or some subset of it:
  - I think `currentColor` only makes sense in CSS properties?
  - If you need RGBA eventually, you might want to not parse `device-cmyk(…)`
* Then convert the matched components according to the corresponding section (for example [Converting HSL colors to sRGB colors](https://drafts.csswg.org/css-color/#hsl-to-rgb)) to the form needed, such as four numbers in the 0 to 1 range for R, G, B, and A channels.

Perhaps css-syntax should have better “glue” algorithms for putting these three steps together. https://drafts.csswg.org/css-syntax/#parse-grammar says it can take a string as input, but when following steps we then get to “[from the list of tokens produced by the tokenizer](https://drafts.csswg.org/css-syntax/#current-input-token)” without further links or info about how to make a tokenizer.

CC @tabatkins

**Comment by tabatkins** [comment]
The first three steps are all covered by just calling CSS/parse with a string. The end result is a `<color>` value, which you can then manipulate in prose, excluding things aren't convertible to RGBA (like `currentcolor` or `device-cmyk()`) and possibly excluding more difficult things (like `color()` with a non-builtin profile).  Step 4 is all past CSS Syntax tho, and into CSS Color.

(Like, if this kind of thing might be done elsewhere, it might be useful for CSS Color to go ahead and define a grammar nonterminal just for "canonicalizable to RGBA without outside information" colors, so you can just parse to that.)

---------

> but when following steps we then get to “from the list of tokens produced by the tokenizer” without further links or info about how to make a tokenizer.

You might be missing this introductory text from 5.3, which applies to all of the algorithms:

> They assume that they are invoked on a token stream, but they may also be invoked on a string; if so, first perform input preprocessing to produce a code point stream, then perform tokenization to produce a token stream.

Does that answer your question? If not, what exactly do you think is missing?

**Comment by SimonSapin** [comment]
Ah indeed, 5.3 intro is what I missed.

**Comment by christianliebel** [comment]
@marcoscaceres @tabatkins In #878, I now use the CSS/parse algorithm to retrieve a `<color>` value. Would it be okay to then…
- Exclude the value if it's either `currentcolor`, a `<system-color>`, `<color()>`, `<device-cmyk()>`, or `<deprecated-colors>` [CSS Color 4]
- Convert <color> to an sRGB color
- Set its alpha value to 1
- Return it in its hex color notation?
