### ISSUE TITLE
Add internal slot for "install is showing".

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#761]
The "steps to install the web application" currently state:

> If there is already an installation process being presented, terminate this algorithm.

We should define a boolean on top-level browsing context to track this.

**Comment by fallaciousreasoning** [comment]
Would this be exposed to the web?

**Comment by mgiuca** [comment]
No, an "internal slot" is spec terminology for a global or class variable inside the spec "language".

**Comment by marcoscaceres** [comment]
Closed because of #836.
