### ISSUE TITLE
Navigation during installation 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#762]
Continuing from #761, we need to specify what happens if the application is being installed and the underlying page navigates while the install prompt is being shown.

**Comment by marcoscaceres** [comment]
Noting that this affects .prompt(), as it has a pending promise that should reject if the underlying document navigates.

**Comment by dominickng** [comment]
This is a good point. In Chrome, I think we currently just drop the promise without resolving it prior to navigation.

**Comment by marcoscaceres** [comment]
As the eventing model is now gone (#836), we can probably ignore this.
