### ISSUE TITLE
Introduce window.Application global object aside manifest.webmanifest

### ISSUE THREAD

**Issue by OmidHekayati** [w3c/manifest#769]
As talks in #97, ... that manifest.webmanifest replicate HTML features, I think spec editors must consider about abandon manifest.webmanifest for these reasons:
- The manifest file has not any idea how to start an app! and we must cache HTML file for each URL that is so bad because all that HTML files is same if have CSR(client-side rendering)! If devs want to have SSR web app (server-side rendering) as an installable app, they must accept that nobody wants to add an app to the home screen that in no internet situation on non-caches URLs shows browser errors or just custom error HTML file!! Manifest is part of PWA and one key purpose is not just app work offline by old caches but works offline natively (CSR client-side rendering). To achieve this, devs must handle lots of logic like routing, ... and best way to implement these needs always start apps with specific `main.html` file in any URL and browser can cache it once for start app in any URL by that file.
- All PWA-starter-kit has just one index.html (I think index name is not a good choice) as the start point of an app that shows PWAs should not have more than one entry point! so we don't need another file than main.html to tell browser for entry point like a manifest file!
- As mention in #97 for security reason (app introduce itself to look like another app) and browser force serve PWA apps over TLS protocol and a certificate for TLS protocol belong to a domain, not URL, a domain can't set more than one app shortcut, so we just need one main HTML file.  So for the future, we must just read the app name and icon from certificate, not from the `manifest` or `main.html` file.

And also I think register another app logic process as `service-worker` also is a huge mistake in web standard due to just register one `main.js` to start an app is enough and devs can write the logic in desired order to handle everything. e.g. [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is [promise](https://developer.mozilla.org/en-US/docs/Web/API/Promise) based so [FetchEvent](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent) can register globally in window object like other event listener.

I propose this way to tell the browser that our app can be PWA (or just has CSR ability) And you can see below example or our version [main.html](https://github.com/SabzCity/www.sabz.city/blob/master/gui/main.html) that have many other tags that introduce the app, splash screen, ...  
I am not sure now about how to indicate [main.js](https://github.com/SabzCity/www.sabz.city/blob/master/gui/main.js) file in main.html and prevent devs to not include other script tags even inline script in main.html due it must illegal like other languages from having more than one main intro(function)!
```html
    <meta name="display" content="standalone">
    <meta name="theme-color" content="#66ff55">
    <link rel="home" href="/?utm_source=PWA&utm_medium=shortcut">
    <link rel="main" href="/gui/main.html">
    <script type="module" src="/gui/main.js" async></script>
```
By above CSR standard proposal that indicate a `main.html` file to render all URL, we also able to write a compiler to compile web apps to native OS apps easily.
(p.s. We consider to continue this approach, not use any manifest file and make a compiler like Flutter but in HTML standards, not complete new languages.)

Last but not least as lots of good face HTML specification never get standard like [@apply](http://tabatkins.github.io/specs/css-apply-rule/) in CSS, Editors must be brave to abandoned `manifest.webmanifest` file from specification and introduce `main.html` before it's too late and uses some meta and link tags.

**Comment by OmidHekayati** [comment]
After some discussion with my friends, we decide to improve our web app idea and work on some two experimental global objects as "window.Application" & "window.Locale" and add Polyfill to test the idea on browsers.
Add ability to devs to initialize "window.Application" data with HTML tags or JS, but still consider to not use any external JSON file!

See these two files for more info about these objects and their methods:
- https://github.com/SabzCity/www.sabz.city/blob/master/gui/widget-localize/window.application.js
- https://github.com/SabzCity/www.sabz.city/blob/master/gui/widget-localize/window.locale.js

**Comment by samad-aghaei** [comment]
Are you sure the method you've used, appending webmanifest to the head in "window.Application" is working?
https://github.com/SabzCity/www.sabz.city/blob/5ae5e99ea50326bd294ded9b0c5ee950a3c292b5/gui/widget-localize/window.application.js#L184
As long as I know, that won't work, at least in latest version of chrome.

**Comment by OmidHekayati** [comment]
Dear @samad-aghaei as you must know "Web App Manifest" proposal is not stable or become standard yet! so we want to discuss here why editors propose external files for app metadata instead of other ways!

Due to web apps must have some basic logic so we can use HTML or JS to tell the browser about app metadata that always use in browser engines.

The external manifest file is like that we serve a file (as separate data) for each page to tell search engines about the content of our pages!!

**Comment by samad-aghaei** [comment]
Omid jan, There is no “must” in knowledge.
If you’d read my comment carefully, that was a simple question.

Also, I don’t think if the webmanifest feature has been implemented “to tell search engines about the content of our pages!!”

The web app manifest is a simple JSON file that tells the browser about your web application and how it should behave when 'installed' on the user's mobile device or desktop. Having a manifest is required by Chrome to show the Add to Home Screen prompt.
A typical manifest file includes information about the app name, icons it should use, the start_url it should start at when launched, and more.

**Comment by OmidHekayati** [comment]
We discuss in here in manifest repository issues so we must know about every aspect of discussion and must know about everything to propose the best ideas!

I must say again that I don't argue about the whole proposal I just argue about how we must tell the browser about our apps! Still, I can't find any reason why we must have an external file to tell the browser about app metadata!

p.s. Our idea about "window.Application" is not complete and we will improve in next weeks to fix all logic problems to ready use in production.

**Comment by samad-aghaei** [comment]
I spent two days to find an elegant way to read the manifest content without fetch it by js code over the browser.

I’m agree with you, loading webmanifest as an external resource is not elegant but still better than writing our app settings in js libraries or in a small js file, or even write it as inline code directly in the page.
I know the webmanifest spec still is unstable, but not in general. almost all the modern browsers has implemented this feature.

I tried the method you’ve used in your app, a couple of months ago and it didn’t work.
At least we have to have a link tag with rel=“manifest” in head, then we can set href attribute dynamically. but still not elegant.

**Comment by OmidHekayati** [comment]
Do you agree that just add a manifest external file can't convert a web site to a web app?

If yes, so you must declare some JS logic code for the browser to app work offline or other logic like route URL change! So if you must declare some code as ServiceWorker or my proposal as the "main" function to start the app, why we don't tell the browser about our app details in that JS declaration file?

If no, I think we have two different purposes about web app.

**Comment by marcoscaceres** [comment]
So, we have a JSON file for legacy reasons: this spec predates service workers by one or two years. Regardless m, we don’t have any plans on adding an API to the spec at this point. If you’d like to serve it using a service worker, you should be able to intercept the fetch request associated with the manifest.

**Comment by OmidHekayati** [comment]
Dear @marcoscaceres I think your excuse about manifest predates SW is not good here! (A bad excuse is worse than none) If manifest editors propose all application needed in this spec we don't need other specs like SW! Developing an application is not a discrete logic in any layer.
In this way, we must say `just think and use the manifest proposal as another way to add web site shortcut only` but your way about adding `serviceworker` member to manifest tell us another thing!

**I don't change this spec a lot**, I just say we can give developers option about how they want to set or update app metadata and some minor improvements in manifest(application) members.

p.s. I don't want to become a ruler or change this spec shortly. I just want to tell the community that we must have a better standard to achieve web app goals. and want to listen to feedback about this idea as an alternative to manifest file.

**Comment by marcoscaceres** [comment]
Closing this issue, as no further action can be taken here. Thanks everyone for your input!

**Comment by marcoscaceres** [comment]
Related https://github.com/w3c/manifest/issues/472
