### ISSUE TITLE
purpose member type check missing

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#771]
When processing purpose, the spec assumes that the value will be a String. However, it could be any other JSON type. 

@dominickng or @mgiuca, could you kindly please check what Chrome does when given:

```JSON
{
    "icons": [{"src": "test", "sizes": "400x400", "purpose": [] }]
}
``` 

Does it convert purpose to "any"? or does the icon get ignored (failure)? 

Also, probably too late... but `purpose` should have been a List :( When we do canonicalization, we return it as a list. Anyway, no big deal.

**Comment by marcoscaceres** [comment]
Also, we should probably deal with {"purpose": ""} more gracefully.... right now, it's "failure", which might be unexpected.

**Comment by dominickng** [comment]
The purpose will get converted to ANY, but an error message is printed out. That is, the purpose member is ignored since it isn't a string, but the icon is not ignored and treated as though the purpose is ANY.

**Comment by dominickng** [comment]
The {"purpose": ""} case in Chrome will also result in the ANY purpose being used and the icon isn't ignored.
