### ISSUE TITLE
When fetching manifest, credentials should be omitted 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#776]
When fetching a web manifest, cookies should not be sent unnecessarily... as such, we should omit credentials by default.

**Comment by dominickng** [comment]
Isn't this the case already as per step 7 in https://www.w3.org/TR/appmanifest/#obtaining ? In Chrome as least, we've had a number of WontFix bugs come up where developers were trying to retrieve manifests from credentialed servers and needed to add the crossOrigin tag for Chrome to send cookies.

**Comment by marcoscaceres** [comment]
yeah, so I think it's missing in:

> Let request be a new [FETCH] request, whose URL is manifest URL, and whose context is "manifest".

Should be:

`... and <a>credentials mode</a> is "omit"`

**Comment by marcoscaceres** [comment]
(so, chrome is doing the right thing by default :) )
