### ISSUE TITLE
Add link type "manifest" to HTML

### ISSUE THREAD

**Issue by Malvoz** [w3c/manifest#778]
I'm aware that the link relation was registered almost [5 years ago](https://github.com/w3c/manifest/pull/314). However it does not yet show in https://www.iana.org/assignments/link-relations/link-relations.xhtml

I'm asking because https://github.com/whatwg/html/issues/4823#issuecomment-518784840. I don't know if there's anything to be done TBH, asking nonetheless.

Thanks :)

**Comment by marcoscaceres** [comment]
I think we need to actually email IANA with the details from the spec. We haven't done that yet 😊

**Comment by marcoscaceres** [comment]
We need to do two things here... send a PR to the HTML spec to add "Link type "manifest"" and send a PR to: https://github.com/link-relations/registry

**Comment by aarongustafson** [comment]
Would you like me to do that @marcoscaceres?

**Comment by marcoscaceres** [comment]
That would be amazing. Take a look at Link type “preload” as one to base off. We should end up with something similar in HTML (pointing back to our spec).

**Comment by aarongustafson** [comment]
*ToDo*: Add to the HTML spec
*ToDo*: Web Platform Test:

```js
x = document.createElement("link");
x.relList.supports("manifest") ;
```

**Comment by aarongustafson** [comment]
Related: https://github.com/whatwg/html/pull/5581

**Comment by aarongustafson** [comment]
We need to fire an event named load on the `link`

**Comment by marcoscaceres** [comment]
Actually, I remembered that we decided not to fire the event on load because it reveals if/when the user is installing. It was something that came up a few years ago, so decided not to add it... I'll have to dig up the original conversation.

**Comment by aarongustafson** [comment]
PR is validating. Hopefully it’s ready to merge.

**Comment by aarongustafson** [comment]
Looks like we are _almost_ ready to merge into HTML, but @annevk would like some additional tests. See https://github.com/whatwg/html/pull/5581#pullrequestreview-439224722

**Comment by aarongustafson** [comment]
Looks like the PR is passing. 🤞🏻 we’ll get it merged soon.

**Comment by aarongustafson** [comment]
Awaiting completion of WPTs (#666).
