### ISSUE TITLE
Dynamic Theme Color

### ISSUE THREAD

**Issue by MehrdadKhnzd** [w3c/manifest#779]
Hello. I have an app with both dark and light mode support, with the ability of theme color customization. How can I change the manifest theme based on page or header color?

**Comment by tomayac** [comment]
Some discussion around this is happening in https://github.com/w3c/manifest/issues/758. For now, you can dynamically change the manifest URL, see the source code of the demo at https://dark-mode-baseline.glitch.me/ for an example.

**Comment by alancutter** [comment]
Use `<meta name="theme-color" content="???">` for dynamic theme colour. Example PWA: https://thundering-frigate.glitch.me

**Comment by aarongustafson** [comment]
Seems like there are valid alternatives and we have no run-time API for manifests, so I am closing this as wontfix.
