### ISSUE TITLE
beforeinstallprompt not fire with "prefer_related_applications": true

### ISSUE THREAD

**Issue by outprogs** [w3c/manifest#780]
Hello,

I want to add install banner for native app to our portal. According this [doc](https://developers.google.com/web/fundamentals/app-install-banners/native)  we should be able to do this by adding to manifest.json with following parameters and meets the [criteria](https://developers.google.com/web/fundamentals/app-install-banners/native#criteria)  

`"prefer_related_applications": true,
"related_applications": [
  {
    "platform": "play",
    "id": "com.google.samples.apps.iosched"
  }
]`

Here is manifest.json that i currently have: 
```
{
  "start_url": "/",
  "gcm_sender_id": "xxxxxx",
  "gcm_user_visible_only": true,
  "short_name": "App",
  "name": "App name",
  "prefer_related_applications": true,
  "related_applications": [
	{
		"platform": "play",
		"url": "https://play.google.com/store/apps/details?id=xxxxxxxxx",
		"id": "xxxxxxxxxxxx"
	}, {
		"platform": "itunes",
		"url": "https://itunes.apple.com/us/app/xxxx/idxxxx?mt=8"
	}
],
  "icons": [
	{
		"src": "launcher-icon-4x.png",
		"sizes": "192x192",
		"type": "image/png"
	},
	{
		"src": "launcher-icon-5x.png",
		"sizes": "512x512",
		"type": "image/png"
	}
  ],
  "display":"standalone",
  "background_color": "#e8eaf6",
   "theme_color": "#3f51b5"
}
```

If i change "prefer_related_applications" to false, PWA works fine for me on Chrome Desktop (Version 76.0.3809.100 (Official Build) (64-bit)) and on Chrome Android (Version 74.0.3729.136). 

Once i change  "prefer_related_applications" to true,  i see that "beforeinstallprompt" event fired for  Chrome Desktop but nothing fired on  Chrome Android. 

Does this expected behavior? Do you have some examples  of code for native app prompt? 
Thanks for you time

**Comment by alancutter** [comment]
None of those apps are available on desktop so they are ignored on Chrome. See: https://cs.chromium.org/chromium/src/chrome/browser/banners/app_banner_manager.cc?type=cs&q=AppBannerManager::ShouldDeferToRelatedApplication&sq=package:chromium&g=0&l=279

**Comment by outprogs** [comment]
@alancutter thanks for info, i checked the code and issue https://bugs.chromium.org/p/chromium/issues/detail?id=949430, and i assumed that we will not have native app prompt for Android chrome because of this https://cs.chromium.org/chromium/src/chrome/browser/banners/app_banner_manager_android.cc?type=cs&sq=package:chromium&g=0&l=388

IsSupportedAppPlatform will always return  false on Android platform

**Comment by alancutter** [comment]
Unfortunately the code is a bit convoluted here. The Android version does a native app installability check separate to a web app installability check, see [`AppBannerManagerAndroid::PerformInstallableChecks()`](https://cs.chromium.org/chromium/src/chrome/browser/banners/app_banner_manager_android.cc?type=cs&sq=package:chromium&g=0&l=170).

**Comment by marcoscaceres** [comment]
Unfortunately, we are not really able to help with Chrome specific bugs as they are outside the scope of the this spec.... cc'ing @dominickng in case this needs to be redirected by inside Google.

**Comment by dominickng** [comment]
@outprogs this should work properly on Chrome for Android. Note that if the native app is already installed or not available on that device, the prompt will not be shown.
