### ISSUE TITLE
Adaptive icons on Android 9

### ISSUE THREAD

**Issue by TorstenDittmann** [w3c/manifest#783]
Running:
- Android 9
- Chrome 76.0.3809.111

Problem:
Icons get squeezed into a round icon.

Screen:
![Image of Icons](https://img.techpowerup.org/190826/scrnsht.png)

I tried normal icon, without background and one considering the [safe-zone](https://w3c.github.io/manifest/#icon-masks)

Used Codesnippet:
```
{
            "src": "/assets/android-chrome-36x36.png",
            "sizes": "36x36",
            "type": "image/png"
},
```

**Comment by marcoscaceres** [comment]
This appears to be Chrome specific issue, and outside the scope of the spec. CC'ing @kenchris and @dominickng  as they might be able to help.

**Comment by kenchris** [comment]
This is not supported on Android yet for WebAPKs but it is being implemented as we speak. Firefox Preview supports it though and you can test with maskable.app

**Comment by mgiuca** [comment]
Are you using [`"purpose": "maskable"`](https://w3c.github.io/manifest/#dfn-badge-maskable)? All of the stuff in the manifest about the safe zone and the construction of adaptive icons in Android is triggered by the use of that member. It won't work without it.

**Comment by TorstenDittmann** [comment]
> Are you using [`"purpose": "maskable"`](https://w3c.github.io/manifest/#dfn-badge-maskable)? All of the stuff in the manifest about the safe zone and the construction of adaptive icons in Android is triggered by the use of that member. It won't work without it.

Same appearance with [`"purpose": "maskable"`].

Even with maskable.app it creates the icon like above.

With [Mozillas Reference Browser](https://github.com/mozilla-mobile/reference-browser) it shows the icon like expected. So it is a Chrome specific issue. 

Thanks for all of your time.

**Comment by dominickng** [comment]
Adaptive icon support isn't yet deployed in Chrome on Android. It should hopefully be out soon.
