### ISSUE TITLE
Scope should remove the query and fragment at parse time

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#793]
Since our [within scope](https://www.w3.org/TR/appmanifest/#dfn-within-scope) algorithm ignores the query and fragment part of the scope, I feel like we should strip those out in the [steps for processing the scope](https://www.w3.org/TR/appmanifest/#dfn-processing-the-scope-member).

Thus if your `scope` is `"/foo/?bar"`, we would canonically say that the scope is `"/foo/"`, reflecting the fact that the query string is irrelevant.

This change would not actually have any direct (specified) user-visible changes, since the only place in the manifest spec that scope is used is the "within scope" algorithm (which ignores query and fragment). However, it might be exposed to the user, for example, through developer tools that displays the canonical parse of the manifest, in which case it would be best to strip the query and fragment for clarity.

**Comment by aarongustafson** [comment]
Makes sense to me.

Just to head off potential questions: this applies to `scope` only, not `start_url` (which we have [another discussion about with regard to query strings and privacy](https://github.com/w3c/manifest/issues/399)).

**Comment by mgiuca** [comment]
Yes, only scope.

Also note that there is a [proposal](https://github.com/wanderview/service-worker-scope-pattern-matching/blob/master/explainer.md) to extend scope syntax with query matching --- this change would only apply to legacy scope syntax which doesn't support query matching in manifest.

**Comment by fallaciousreasoning** [comment]
**Note:** I'm pretty sure ServiceWorkers don't do this, so we'll be diverging a bit.
