### ISSUE TITLE
make BeforeInstallPrompt optional

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#796]
We should make it clear that the BIP API is optional.

**Comment by fallaciousreasoning** [comment]
There's a pull request for this here #797.

**Note:** Did we also want to add a warning?

**Comment by mgiuca** [comment]
> **Note:** Did we also want to add a warning?

What warning?

Optional is not the same thing as deprecated. I am OK with optional but I'll be fighting if there are calls to deprecate this.

**Comment by marcoscaceres** [comment]
Closed via #836
