### ISSUE TITLE
Space-separated sizes in ImageResource?

### ISSUE THREAD

**Issue by aarongustafson** [w3c/manifest#807]
@rayankans and I are working on breaking out `ImageResource` currently and, while reading through the `sizes` member in more detail as part of that, I noticed it supports a set of space-separated values (much like its HTML equivalent). As each `ImageResource` has only a single file (`src`) associated with it and that file has one set of natural dimensions, I’m confused as to why we would support multiple values here. But perhaps I’m missing something.

@marcoscaceres @mgiuca @kenchris Any insight here?

Also: *If* it should only be a single value, should we also consider amending it to "size" and deprecate `sizes`, perhaps grandfathering it in by extracting the first set item from any existing `sizes` member as `size`)?

Duplicates https://github.com/rayankans/image-resource/issues/1

**Comment by dominickng** [comment]
> As each `ImageResource` has only a single file (src) associated with it and that file has one set of natural dimensions, I’m confused as to why we would support multiple values here. But perhaps I’m missing something.

Is it correct to assume each `ImageResource` only has one set of natural dimensions? I would assume this is here (and in HTML) to support non-scalable icon formats that can contain multiple discrete icons of different sizes (e.g. `.ico` and `.icns`).

**Comment by marcoscaceres** [comment]
Yep, what @dominickng said: The underlying reason was to support .ico and .icns, which can contain multiple icons in a single file.

**Comment by aarongustafson** [comment]
As I mentioned on the other thread, I’d totally forgotten about the `.icns` container format. Thanks for the reminder. Do you think it would make sense to include a note to that effect on the `ImageResource` spec?

**Comment by dominickng** [comment]
The manifest spec has a concrete example referencing a `ico` file. That may be sufficient.

**Comment by marcoscaceres** [comment]
@aarongustafson, if you haven't already, please also take a look at HTML spec's definition of the "sizes" attribute. I seem to recall that it also provides some rationale there - so maybe something also good to reference.

**Comment by aarongustafson** [comment]
This has been address  in https://github.com/w3c/image-resource/pull/11
