### ISSUE TITLE
Inconsistent use of "terminate" vs "abort"

### ISSUE THREAD

**Issue by jyasskin** [w3c/manifest#809]
https://www.w3.org/TR/appmanifest/#obtaining sometimes uses "terminate this algorithm" and sometimes "abort these steps". I think they have the same meaning, but the spec should pick one. This is not super-important.

**Comment by marcoscaceres** [comment]
I think we should go with "abort these steps" throughout.

**Comment by marcoscaceres** [comment]
@contrepoint has kindly volunteered to fix this for us. Looking forward to the PR.
