### ISSUE TITLE
Broken reference: Valid MIME type

### ISSUE THREAD

**Issue by benfrancis** [w3c/manifest#813]
The reference to "valid MIME type" in section [9.7 type member](https://www.w3.org/TR/appmanifest/#type-member) appears to be a broken link.

It's currently:

`<a data-cite="HTML#valid-mime-type"><dfn>valid MIME type</dfn></a>`

Which resolves to

`https://html.spec.whatwg.org/multipage/#valid-mime-type`

and that anchor doesn't appear to exist.

I'm not sure what specification _should_ be referenced to determine whether a given MIME type is valid, but https://mimesniff.spec.whatwg.org may be useful?

**Comment by aarongustafson** [comment]
Thanks for the heads up! I’ve submitted a PR.
