### ISSUE TITLE
Obtaining the manifest from any context

### ISSUE THREAD

**Issue by rayankans** [w3c/manifest#818]
[Obtaining](https://www.w3.org/TR/appmanifest/#obtaining) the manifest only works for top-level browsing contexts at the moment. Would it be possible to update the algorithm to take any browsing context? It would enable some interesting use cases, as outlined in [wicg/get-installed-related-apps/#11](https://github.com/WICG/get-installed-related-apps/issues/11)

**Comment by aarongustafson** [comment]
It feels like this relates to https://github.com/w3c/manifest/issues/851 in some way too, no?

**Comment by marcoscaceres** [comment]
Closing this one... I don't think we want anything apart from the top level navigable to say what the manifest is.
