### ISSUE TITLE
Spec what it means to support "manifest" via <link>'s relList 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#826]
We need to spec out:

```
document.createElement("link").relList.supports("manifest");
```

This might actually go into HTML... just putting it here as reminder.

**Comment by marcoscaceres** [comment]
Noting, browsers:

 * Safari: true 
 * Chrome: true
 * Firefox: false - bug https://bugzilla.mozilla.org/show_bug.cgi?id=1596040

**Comment by marcoscaceres** [comment]
Fixed in Firefox (Fenix will return true - and  I think Firefox nightly too, as DevTools now has an "Applications" tab that processes the manifest).  

@aarongustafson, this is related https://github.com/w3c/manifest/issues/778 ... we should get this "for free" when it goes into HTML, but please double check with the HTML crew when you send the PR to HTML (please cc me too).

**Comment by aarongustafson** [comment]
Related to #778

**Comment by aarongustafson** [comment]
I was interested in trying to build a platform test, so I took a stab at it.

**Comment by aarongustafson** [comment]
@marcoscaceres Is this one clear to close or is there more work to do on this?

**Comment by marcoscaceres** [comment]
Let's close it... this will now be handled over on the HTML side for free.
