### ISSUE TITLE
Microsoft's company url redirects to another Microsoft url

### ISSUE THREAD

**Issue by janiceshiu** [w3c/manifest#837]
Ran the spec through the [w3 validator](https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.w3.org%2FTR%2Fappmanifest%2F&hide_type=all&recursive=on&depth=&check=Check) and noticed the issue below

> warning Line: 1052 https://microsoft.com/ redirected to https://www.microsoft.com/en-us/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

Sending a PR to fix this.

cc @marcoscaceres

**Comment by aarongustafson** [comment]
Just to confirm: Does the same redirect happen regardless of system/browser language? I didn’t realize it was a 301, but I would hope the logic would redirect based on user preference. (MDN redirects based on language codes too, which is why I ask.)

**Comment by alancutter** [comment]
That redirect looks fine to me, can we suppress the warning instead?

**Comment by janiceshiu** [comment]
closing and have closed the PR.
