### ISSUE TITLE
[Proposal] Home screen widgets

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [w3c/manifest#840]
Since we have shortcuts in the spec, what about another interesting feature that at this moment native apps have, but PWAs haven't — home screen widgets?

E.g. it would be really nice to have a https://weather-pwa-sample.firebaseapp.com/final/ PWA as Android or Windows home screen widget.

**Comment by FluorescentHallucinogen** [comment]
I've also opened https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/152.

**Comment by aarongustafson** [comment]
> Since we have shortcuts in the spec, what about another interesting feature that at this moment native apps have, but PWAs haven't — home screen widgets?
> 
> E.g. it would be really nice to have a https://weather-pwa-sample.firebaseapp.com/final/ PWA as Android or Windows home screen widget.

We are talking about it: 

* https://discourse.wicg.io/t/noodling-on-an-idea-projections-for-web-apps/3900
* https://github.com/w3c/manifest/issues/782#issuecomment-533363985
