### ISSUE TITLE
Use the newly defined ImageResource

### ISSUE THREAD

**Issue by rayankans** [w3c/manifest#854]
The `ImageResource` definition moved to its own [spec](https://w3c.github.io/image-resource/). The Manifest's definition includes some extra manifest-specific fields. So instead of defining its own `ImageResource` it could re-use parts of the new `ImageResource` by defining the following dictionary:

```webidl
dictionary ManifestImageResource : ImageResource {
  USVString platform;
  USVString purpose;
}
```

**Comment by marcoscaceres** [comment]
Blocked on TAG feedback and getting FPWD out.

**Comment by aarongustafson** [comment]
This is in the system now, so we are unblocked.

**Comment by marcoscaceres** [comment]
We can use "process an image resource from JSON" from [[image-resource]].
