### ISSUE TITLE
how to handle cancel button for pwa prompt

### ISSUE THREAD

**Issue by novaknole** [w3c/manifest#855]
I am curious how you handle this.

**Question 1)** So basically let's say a prompt appeared which means I make my `install` button's css as `display` block.  So `install` button appears. User clicks on it and there's a browser's prompt appearing. Now, let's say user clicked on cancel. Now if he refreshes the page,  `beforeinstallprompt` event still gets called which means my `install` button will still appear. The sum up is `install` button is gonna be here all along until user installs the app. 

Is this the behaviour you follow or what do you do? Do you use `localStorage` to detect if user clicked cancel and and not show `install` button again?

I'd highly appreciate your ideas.

**Question 2)** I already opened a bug issue on chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1064743 but maybe you know this hopefully.

**Comment by marcoscaceres** [comment]
Moved issue to BIP repo: https://github.com/WICG/beforeinstallprompt/issues/1
