### ISSUE TITLE
consider alternative manifest formats

### ISSUE THREAD

**Issue by ret394** [w3c/manifest#861]
from https://w3c.github.io/manifest/
> This specification defines a JSON-based manifest file 

first JSON manifest is used. https://github.com/w3c/manifest/issues/12

please do not use JSON. it has well known issues, but not due to spec. consider alternatives. 

please reach out at my github repo https://github.com/ret394/jubilant-broccoli/issues if anything is unclear. thanks.

**Comment by marcoscaceres** [comment]
Little late given that the spec shipped years ago, but appreciate the suggestion.
