### ISSUE TITLE
Bad cross references - remove `data-cite` where possible

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#884]
Couple of bad cross references... we are probably trying to cite things that don't exist anymore or that are not explicitly exported by HTML.
 
```
https://html.spec.whatwg.org/multipage/#unordered-set-of-unique-space-separated-tokens
https://html.spec.whatwg.org/multipage/#linkTypes
https://html.spec.whatwg.org/multipage/#delay-the-load-event
https://html.spec.whatwg.org/multipage/#valid-non-negative-integer
https://html.spec.whatwg.org/multipage/#concept-link-type-sniffing
https://html.spec.whatwg.org/multipage/#the-element's-base-url
```

**Comment by marcoscaceres** [comment]
Unordered set coming soon hopefully: https://github.com/whatwg/html/pull/5622

**Comment by marcoscaceres** [comment]
Please see any `data-cite=` things in the spec - hopefully we can get accessible name and description exported.

**Comment by aarongustafson** [comment]
I didn’t see these two in there anymore:

* https://html.spec.whatwg.org/multipage/#concept-link-type-sniffing
* https://html.spec.whatwg.org/multipage/#the-element's-base-url
