### ISSUE TITLE
"Delay the load event" should happen in HTML

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#891]
As discussed in https://github.com/whatwg/html/pull/5595 ...  our spec talks about "MUST NOT delay the load event". However, that should be defined in the HTML spec, not in our spec so we need to move it over. 

This is part of moving the "manifest" link relationship over to HTML. https://github.com/whatwg/html/pull/5581

**Comment by aarongustafson** [comment]
I could really use your help with the algorithms on the HTML spec @marcoscaceres. I don’t feel like I’ve got the domain knowledge to understand all of the implications of the changes I’m making as I try to merge the two. Do you think it makes sense to copy over the whole section from the Manifest spec and then work with you (and @domenic) to winnow it down to only the bits that need to diverge from the default behavior in the HTML spec?
