### ISSUE TITLE
badge purpose "monochrome" is only supported by Firefox

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#905]
As the badge purpose "monochrome" is only supported by Firefox, it is at risk of being removed from the specification. Implementers should express interest in supporting this feature if they would like it to remain in the specification.

**Comment by mgiuca** [comment]
Chrome: Filed https://crbug.com/1096388

As I said on #833, I can't commit to us actually using this but I think it's useful to have it defined and I'll advocate for it to be used when an appropriate context arises.

**Comment by marcoscaceres** [comment]
Thanks @mgiuca, the feature is explicitly marked at risk in the spec, so we will await your feedback in #905. 

<img width="884" alt="Screenshot 2020-06-18 17 13 01" src="https://user-images.githubusercontent.com/870154/84989421-fb6a4080-b186-11ea-8ff6-9c0d43f899c1.png">

**Comment by kenchris** [comment]
@aarongustafson I assume this would also be useful for Edge and the Microsoft design system - maybe something Microsoft would be interested in adding support for?

**Comment by KnechtRo0trecht** [comment]
I find a blank version of the icon very useful. A one-color icon is already needed for the safari mask-icon to display the logo in the touch bar. User agents could do a lot with a blank, standard version of the normal icon e.g. when having a design schema to automatically fit the icon in the design schema: The icon color is red, background is black with a padding of x. It could also be useful for share-icon-generation, so the icon can easily fit to the share-icon-design.

**Comment by christianliebel** [comment]
> Chrome: Filed https://crbug.com/1096388
> 
> As I said on #833, I can't commit to us actually using this but I think it's useful to have it defined and I'll advocate for it to be used when an appropriate context arises.

@mgiuca The crbug was marked as Fixed/Closed. Can that be interpreted as your support for this badge purpose?

**Comment by phoglenix** [comment]
I'm the last eng person on Chrome to touch icon purposes (not a PM!).
https://crbug.com/1096388 was tracking the rename of purpose "badge" to "monochrome". That part is done.
https://crbug.com/1114638 is tracking adding support for icons with purpose "monochrome" (not a commitment to do so).

I believe @mgiuca's comment is still accurate. Chrome is not actually using "monochrome" currently but would support it remaining in the spec because it's likely to be useful in the future.

**Comment by mgiuca** [comment]
Yeah so this is just in Firefox as far as we can tell.

I think @NotWoods renamed it in Firefox, correct? And it's landed in the spec. So that means it's renamed everywhere that it exists.

It isn't implemented outside of Firefox, so that puts it at risk in the spec, however, Google supports keeping it just because we think we'll want it some day. If it gets taken out of the spec due to only one implementation, c'est la vie. It can come back later.

**Comment by aarongustafson** [comment]
Just making a note here: Once this has broader adoption, we will need to add it to the Web Platform Tests. I am removing it from #666 so it doesn’t hold up CR.

**Comment by loyso** [comment]
Chrome M93 recognizes "monochrome" icon purpose for both primary icons and shortcut menus (jump lists).
https://bugs.chromium.org/p/chromium/issues/detail?id=1114638

It's not yet exposed in Chrome UI yet, will be used in Notifications in M94-M95.

**Comment by FluorescentHallucinogen** [comment]
> Chrome M93 recognizes "monochrome" icon purpose for both primary icons and shortcut menus (jump lists).
https://bugs.chromium.org/p/chromium/issues/detail?id=1114638

> It's not yet exposed in Chrome UI yet, will be used in Notifications in M94-M95.

Two questions:

1. Is it only for Chrome on desktop? What about Chrome on Android?

2. Are icons declared in web app manifest really used for notifications? 🤔
As far as I know `showNotification(title, options)` method uses `icon` property from `options` argument. See https://web-push-book.gauntface.com/display-a-notification/. If the `options` object has no `icon` property, then default browser icon used. Isn't it?

**Comment by marcoscaceres** [comment]
@dmurph 👆

**Comment by dmurph** [comment]
1. I believe this is only ChromeOS - but @loyso is the right person to ask here
2. I think the goal is to never use the browser icon, and instead use icons from the manifest.

**Comment by loyso** [comment]
Hi all! Thanks for asking!

1. Yes - it is ChromeOS only. For Android: ask peter@chromium.org to add a UI support? :)

Aside: you can enable/try it on Linux: https://bugs.chromium.org/p/chromium/issues/detail?id=1236313
(not launched yet). MacOS and Win would require a system notifications explorations, But you can try
and enable the flag on other Desktop OSes.

2. With this change we have the following order of precedence (from low to high):
  a. Chrome logo (default browser icon).
  b. Web app icon from the manifest, when available.
  c. Notification-specific icon, when available (`options.badge` parameter in SW registration.showNotification() API)
  
I hope that helps, happy to chat! (For example: #pwas on Chromium Slack https://app.slack.com/client/T039UTRBS/CGK77JY3W)

**Comment by mkruisselbrink** [comment]
Reopening since this issue is still [referenced](https://www.w3.org/TR/appmanifest/#monochrome-icons-and-solid-fills) from the spec. If this is actually no longer an issue, presumably the spec should no longer say it is?

**Comment by mathix420** [comment]
I created this issue a while ago https://crbug.com/1468845
It seems to be ongoing.

**Comment by mgiuca** [comment]
Yes, this should just be removed from the spec. (I'm rushing through my old email right now so I won't do it immediately, leaving this bug open, but just a note for future people that we should just delete the reference to this issue from the spec, and close it.)

**Comment by NotWoods** [comment]
Yes, this is intended to be used for the themed icons in Android. Since it's currently used for shortcuts on Android, this issue is about removing the firefox-only warning rather than removing monochrome icons.

**Comment by poyribn** [comment]
I would love my Firefox Tab&nbsp;Bar to look more modern and less distracting by enabling monochrome&nbsp;Favicons.
Currently only colored&nbsp;Favicons are supported, which fits perfectly with the Design&nbsp;Language of the first Web&nbsp;Browsers and not&nbsp;so&nbsp;much with the Design&nbsp;Language of modern Web&nbsp;Browsers — in&nbsp;particular, Favicons colored by Website&nbsp;Vendors clash with Tab&nbsp;Groups colored by Users.
