### ISSUE TITLE
Task switcher icon

### ISSUE THREAD

**Issue by ronanyeah** [w3c/manifest#907]
I am having the same problem as this person:
https://stackoverflow.com/questions/60156733/how-do-i-trigger-adaptive-maskable-icon-for-pwa-in-android-task-switcher

Is there a way to alter this behaviour? I can't see anything conclusive in the spec. For me it places a square maskable icon in front of whatever the set `background_color` is.

**Comment by mgiuca** [comment]
This isn't a Manifest issue, but an implementation problem with Chrome and/or Android.

Glad to hear of this issue. I've filed a Chrome bug [crbug.com/1098580](https://crbug.com/1098580) which you can follow for updates.

**Comment by ronanyeah** [comment]
Thanks!
