### ISSUE TITLE
At risk: ManifestImageResource.platform?

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#909]
I believe [`ManifestImageResource.platform`](https://www.w3.org/TR/appmanifest/#platform-member) should be considered at risk. I don't think Chrome implements it ([`ParseIcons`](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/manifest/manifest_parser.cc;l=387;drc=730040c92ecd7b32a67faa689133d3074e149157;bpv=1;bpt=1) in Chrome's manifest parser doesn't look at the `"platform"` member). And I don't think it's necessary. Does Gecko or WebKit implement this?

Since we added `maskable` and `monochrome`, we're trending towards specifying purposes with specialized semantics, but not specific to any OS. I think that's much better than letting developers supply specific icons for each OS.

I think it can be removed.

**Comment by aarongustafson** [comment]
It *may* make sense to move this, alongside screenshots, to the App Information spec. I'll check with the folks consuming those details for storefronts. It's probably an edge case, but there might be instances where folks want to offer alternate screenshots for desktop and mobile, for example.

**Comment by marcoscaceres** [comment]
[checked](https://github.com/mozilla/gecko-dev/blob/master/dom/manifest/ImageObjectProcessor.jsm), we don't implement it in Gecko either. I'd be ok to remove it. Safari doesn't implement any icon support, so probably ok there too.

**Comment by aarongustafson** [comment]
Has the icon support story at Apple changed at all with their “homescreen web apps"? I saw the announcement, but have not read up.

**Comment by tomayac** [comment]
> Has the icon support story at Apple changed at all with their “homescreen web apps"? I saw the announcement, but have not read up.

No changes in the current iOS 14 beta 1. Still doesn’t use the icons from the manifest. I test with “all” possible icon sizes: https://ios-a2hs-demo.glitch.me/.

**Comment by marcoscaceres** [comment]
thanks for confirming @tomayac!

**Comment by christianliebel** [comment]
> I think it can be removed.

I agree. Web developers should not have to deal with OS/platform differences, and `maskable` and `monochrome` are great ways for developers to adapt their icons to the platform. So it makes sense to remove the `platform` member from ManifestImageResource. 👍 

Also, I support @aarongustafson’s idea to move the platform member to App Information/screenshots, as developers might want to show different screenshots not only for mobile and desktop but also for various storefronts/platforms (which may have special requirements for those screenshots).

**Comment by christianliebel** [comment]
+ Update JSON schema
