### ISSUE TITLE
Replace "determine the installability of the document" with some manifest/document reconciliation steps

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#912]
Following up a [review thread](https://github.com/w3c/manifest/pull/834/#pullrequestreview-434708529): the concept of "installability of the document" doesn't make a lot of sense, given that most browsers allow any document to be installed. So we should just remove the concept of "installability of the document".

However, we have valuable normative requirements in these steps around a) making up a virtual manifest for sites that have none, and b) reconciling the processed manifest with the document URL to make sure its `scope` and `start_url` are same-origin as the document URL. We should move those into a dedicated algorithm; either a "steps to sanitize a manifest for installation from a document URL" or perhaps "steps to install a document". The goal is to let an external system (such as an app store) install a manifest without any document, but if a browser installs a manifest from a document, disallow installation of an app that's hosted on a different origin to the originating document.

**Comment by marcoscaceres** [comment]
> the concept of "installability of the document" doesn't make a lot of sense, given that most browsers allow any document to be installed. So we should just remove the concept of "installability of the document".

Removed. 

> a) making up a virtual manifest for sites that have none

I think it might be overly presumptuous to assume they use the same mechanism or defaults. I think we should just stay silent on this.   

>  b) reconciling the processed manifest with the document URL to make sure its scope and start_url are same-origin as the document URL. 

I think this is handled as far as there is a document and link relationship. 

> The goal is to let an external system (such as an app store) install a manifest without any document,

I'm thinking this should be a non-goal *for now*. We should just solve for manifests installed from documents.  

> but if a browser installs a manifest from a document, disallow installation of an app that's hosted on a different origin to the originating document.

Agree.

**Comment by marcoscaceres** [comment]
Closing, as processing a manifest is strongly tied to there being a document:
https://www.w3.org/TR/appmanifest/#dfn-processing-a-manifest
