### ISSUE TITLE
Combine all security & privacy sections into one?

### ISSUE THREAD

**Issue by mgiuca** [w3c/manifest#915]
I just noticed how many security and/or privacy considerations sections we have — eight!:

- [Installable web applications - Privacy and security considerations](https://www.w3.org/TR/appmanifest/#installation-sec)
- [Navigation scope - Security considerations](https://www.w3.org/TR/appmanifest/#navigation-scope-security-considerations)
- [Display modes - Privacy and security considerations](https://www.w3.org/TR/appmanifest/#privacy-and-security-considerations-0)
- [Display modes - The `display-mode` media feature - Security and privacy considerations](https://www.w3.org/TR/appmanifest/#security-and-privacy-considerations)
- [`ShortcutItem` and its members - `url` member - Privacy and security considerations](https://www.w3.org/TR/appmanifest/#privacy-and-security-considerations-1)
- [`WebAppManifest` dictionary - `start_url` member - Privacy consideration: `start_url` tracking](https://www.w3.org/TR/appmanifest/#privacy-consideration-start_url-tracking)
- [Media type registration](https://www.w3.org/TR/appmanifest/#media-type-registration) - Security and privacy considerations (this one is part of the standard form so we probably can't move it)
- [Internationalization](https://www.w3.org/TR/appmanifest/#internationalization) - Mentions privacy concerns

Would it be appropriate to combine all of these (probably excepting the IANA one) into a single "Security and privacy considerations" appendix at the bottom of the document, @marcoscaceres ? If not, we should at least name them consistently.

**Comment by marcoscaceres** [comment]
Yeah, might be fine to combine them. I need to check if it's obvious enough in the normative parts/algorithms that the privacy/security mitigations are happening.
