### ISSUE TITLE
can multiple PWA scopes exist for virtual paths

### ISSUE THREAD

**Issue by rrrepos** [w3c/manifest#919]
I have a NodeJS app and they are accessed via `https://somewebapp.com/abc` and `https://somewebapp.com/def`. But internally they point to the same code and use the path (as locals in NodeJS) to customise the experience. Is there a way to have two sets of installs for each of the path. 

I have tried two manifests (dynamically loaded based on path) and in each have the following scope and start_url:

```
scope: /abc
start_url: /abc
```
However for the first path it creates the install using the correct icon as specified by that paths manifest. Is there a way around this? Thanks

**Comment by christianliebel** [comment]
@rrrepos Which browser are you testing it on? Could you try to use trailing slashes for both `scope` and `start_url`, like so:

```json
{
  "scope": "/abc/",
  "start_url": "/abc/"
}
```

?

**Comment by rrrepos** [comment]
It worked when I changed the path of the respective manifest files to a subdirectory viz. `/abc/manifest.json` and `/def/manifest.json`. It seems unlikely that that should have been the error. 

@christianliebel : I tried on Chrome 83 on MacOSX as well as Chrome on Android. Thansk
