### ISSUE TITLE
auto value of the dir member

### ISSUE THREAD

**Issue by xfq** [w3c/manifest#923]
https://www.w3.org/TR/appmanifest/#dom-textdirectiontype-auto

AFAIK the `auto` value for direction is often used when the direction is to be determined programmatically using heuristics. See [HTML](https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute) for an example.

For specs that don't use heuristics to determine the base direction (like [CSS](https://drafts.csswg.org/css-writing-modes-3/#direction) and [TTML](https://www.w3.org/TR/ttml2/#style-attribute-direction)), they usually don't include an `auto` value. I wonder what intention of the `auto` value is in the Web App Manifest. Is an `auto` value needed?

**Comment by marcoscaceres** [comment]
IIRC, "auto" is needed because it leaves it to the Unicode bidi algorithm to work it out. ltr and `rtl` and `ltr` strongly overrides the bidi algorithm (or signals to the bidi algorithm what to expect), so it's needed and it's different to "auto".

**Comment by xfq** [comment]
I see. Thank you.

I think the behavior should be specified in the WAM spec. For example, the HTML spec looks for the first strongly-directional character, similar to the [Paragraph Level](https://unicode.org/reports/tr9/#The_Paragraph_Level) determination in the bidirectional algorithm.

**Comment by marcoscaceres** [comment]
Problem is that we just pass the strings to the OS, it's not something we really control. We can only provide the hints to the OS.

**Comment by marcoscaceres** [comment]
having said that, the above is only theoretical... I don't think any OS actually accepts these hints... there are other places where they can be useful tho (e.g., in an install dialog that is presented by the browser).
