### ISSUE TITLE
Chore: Update contribution guidelines to include commit prefixes

### ISSUE THREAD

**Issue by aarongustafson** [w3c/manifest#929]
The current approach is to use things like "chore" to prefix commits. We should add that—and the list of values—to the docs.

**Comment by marcoscaceres** [comment]
So, the list is (first case doesn't matter too much, though I prefer upper) - they are all fairly self explanatory, but the [PULL_REQUEST_TEMPLATE](https://github.com/w3c/manifest/blob/gh-pages/PULL_REQUEST_TEMPLATE.md) has good definitions for each:

 * Chore: 
 * Editorial: 
 * BREAKING CHANGE: 
 * none if it's normative change

The reason we have them is so we can filter them non-normative changes out quickly. This allows us to generate changelogs.  

We should probably just add a reminder to "PULL_REQUEST_TEMPLATE.md" for this.
