### ISSUE TITLE
Add field: public key (certificate)

### ISSUE THREAD

**Issue by darkdragon-001** [w3c/manifest#930]
The app manifest should provide an option for the app developer/owner to specify the certificate (public key) which will be used for HTTPS connections (similar to [HTTP Public Key Pinning (HPKP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning)).

This would allow many of the apps currently bundling Electron to move (back) to PWAs while maintaining their high security standards (e.g. [E2E encrypted messenger Signal](https://community.signalusers.org/t/web-app-for-signal/1272/2)).

**Comment by dominickng** [comment]
I don't quite see how this addresses the Signal use case. The manifest itself still has to be requested, and by the time that happens the site has usually fully loaded. At what point would any key specified in the manifest be used? In what way should it be used?

**Comment by alancutter** [comment]
I wonder if this kind of check could be implemented in a service worker fetch instead.

**Comment by alancutter** [comment]
I don't think the manifest is the right place for this data anyway as it's so time dependent. The manifest should be for static app metadata.

**Comment by mgiuca** [comment]
This feels like more of a [Web Bundles](https://web.dev/web-bundles/) issue than a manifest thing.

**Comment by darkdragon-001** [comment]
> I don't quite see how this addresses the Signal use case. The manifest itself still has to be requested, and by the time that happens the site has usually fully loaded. At what point would any key specified in the manifest be used? In what way should it be used?

There is no perfect solution of this chicken and egg problem. There needs to be some _trust_ at some point. Usually this is done in the installation step (downloading the installer from the website, setting up apt repository keys, ...). As common with traditional distribution models (public key displayed on website along the download, apt keys published via twitter, ...), browsers should show this public key in the PWA installation dialog for verification over another channel.

After installation, all future traffic is protected with implementation of this proposal:
- safe updates
- safe download of web sites/assets
- safe communication (e.g. XHR)

> This feels like more of a [Web Bundles](https://web.dev/web-bundles/) issue than a manifest thing.

In addition to the browser based installation approach, _safe distribution_ via other channels (app stores, bundles etc.) would be as easy as submitting a link to the manifest since the manifest contains _all_ necessary data.

**Comment by marcoscaceres** [comment]
I'm going to go ahead and close this one, as I don't think this problem can be solved via the manifest. End to end encryption of messages should be handled for all web applications, not just installed ones.

**Comment by darkdragon-001** [comment]
This is not about encryption but about authenticity. At installation time, which is manually triggered by the user, one should have the possibility to verify the key. Whenever the key changes, the user should actively be asked for acceptance to unblock the update.
