### ISSUE TITLE
Related applications parsing is incorrect

### ISSUE THREAD

**Issue by aarongustafson** [w3c/manifest#936]
The [steps for processing the `related_applications` member](https://www.w3.org/TR/appmanifest/#dfn-processing-the-related_applications-member) has the following issues:

1. It references a `src` value which is not specified.
2. Even though `platform` is required, it does not throw out `ExternalApplicationResource`s that do not include a `platform`

**Comment by aarongustafson** [comment]
@marcoscaceres would you consider fixes for this to be a breaking change? They seem necessary for making it testable.

**Comment by aarongustafson** [comment]
@marcoscaceres would you consider this a breaking change?

**Comment by marcoscaceres** [comment]
Seems the `src` was a typo... should have been `id`. Fixed via #933. 

> @marcoscaceres would you consider fixes for this to be a breaking change? They seem necessary for making it testable.

**Comment by aarongustafson** [comment]
Closing in anticipation of the change getting published.
