### ISSUE TITLE
Feature: Open shortcuts on the already open app

### ISSUE THREAD

**Issue by CheloXL** [w3c/manifest#937]
Right now, if I have my PWA open and I use a shortcut defined on the manifest, the OS opens a new window/app/instance of the same app, but in the correct state based on the shortcut.
I would like to setup shortcuts in order to only open one instance of the app, and if I select another shortcut, that command is sent to the existing browser frame instead of opening a new top-level app,

**Comment by reillyeon** [comment]
This would be resolved by either the [Service Worker "launch" Event](https://github.com/WICG/sw-launch/blob/master/explainer.md) or [Declarative Link Capturing](https://github.com/WICG/sw-launch/blob/master/declarative_link_capturing.md).
