### ISSUE TITLE
Spec Metadata Lists Incorrect Values for Chrome

### ISSUE THREAD

**Issue by jpmedley** [w3c/manifest#939]
The Browser Support heading in the spec manifest shows support in Chrome as 89. If I hover over the label it expands to show Chrome support in 86 through 89. (I'm not sure why I thought to hover. There's no affordance suggesting that I should do that.)

Chrome has actually supported [web app manifest since 39](https://www.chromestatus.com/feature/6488656873259008). There is a similar problem with the Chrome Android label.

Also Chrome 89 does not even exist yet. The current dev channel is Chrome 88. 

![image](https://user-images.githubusercontent.com/8204171/99417318-a4d86e00-28ae-11eb-9b0e-dbf976d78256.png)

**Comment by christianliebel** [comment]
Hi Joe! From my understanding, the browser support section shows data from caniuse.com, where the Chrome support data appears to be correct: https://caniuse.com/web-app-manifest

The caniuse integration in ReSpec retrieves the four latest versions of a browser (https://github.com/w3c/respec/blob/develop/src/core/caniuse.js#L108), showing the latest one on the label, and hiding the previous three in the submenu. This includes prerelease versions. My installation of Chrome Canary is on version 89 already, so it seems as if M89 is already in preview.

It may make sense to show the latest released version of the browser on the label and all supported versions in the hover menu. That however would be a feature request for ReSpec.

.cc @sidvishnoi @marcoscaceres

**Comment by jpmedley** [comment]
I'll open a ticket on respec. In the meantime, I'd suggest removing it completely because it's showing incorrect data.

**Comment by sidvishnoi** [comment]
> It may make sense to show the latest released version of the browser on the label and all supported versions in the hover menu.

The default number of browsers can be adjusted in `respecConfig` (https://respec.org/docs/#caniuse):
```js
var respecConfig = {
  caniuse: {
    feature: "web-app-manifest",
    versions: 10,
  },
};
```

Though, showing too many versions might become too clumsy. I'll try to see if we can group versions like caniuse.com does.

**Comment by sidvishnoi** [comment]
Also, I'm not sure if it'll add much value as we do not intend to copy the caniuse table into ReSpec/spec. This is what the "More info" link is for.

**Comment by jpmedley** [comment]
I'm less concerned with how you get there than I am about the fact that it
looks like its presenting incorrect information.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by marcoscaceres** [comment]
I agree that what it shows is not great. sidvishnoi/respec-caniuse-route#8 would solve the problem via the grouping. 

I guess the best thing to do here right now would be to just set "versions" to 1. That disables the hover behavior and just shows the latest supported version. 

@jpmedley, would that be suitable?

**Comment by christianliebel** [comment]
I am closing this as the browser support section now links to caniuse.com.
