### ISSUE TITLE
Confusing use of MAY and SHOULD

### ISSUE THREAD

**Issue by triple-underscore** [w3c/manifest#948]
[In section 2.1 Application's name](https://w3c.github.io/manifest/#application-s-name)

> If the name and short_name members are missing or undefined, a user agent MAY fallback to the Document to find suitable replacements for missing manifest members (e.g., using application-name in place of name or short_name). Alternatively, the user agent SHOULD assign a default name (e.g., "Untitled") that follows platform conventions. Alternatively, a user agent MAY allow the end-user to input some text that can serve as the application's name. 

There are three alternatives with a SHOULD and two MAYs mixed.
Does it mean SHOULD phrase takes precedence over the others? (If so, the SHOULD phrase should come first.)

The paragraph also mentioned `undefined` explicitly, which seems inconsistent with other paragraphs in the same section:

> When either the name member or the short_name member is missing, ...

Does this “missing” do exclude `undefined` ?

> When both the name and short_name members are present,...

Does this “present” do include `undefined` ?

**Comment by mseddon** [comment]
fwiw my read is that the SHOULD clauses would be priortised, and 'missing' would include `undefined`, (primarily because it's faster to assign undefined in JS, so it's an idiom that performs faster than `delete()`), but this is a good clarification, since it doesn't feel as clear as presented.

**Comment by marcoscaceres** [comment]
It's basically, "if you, browser maker, choose to do X (MAY), then you SHOULD do it this way:...".  I know, it's less than ideal, but as a rule spec's can't enforce browser UI related things. 

My current reading of the recommendations there seems to be ok, so I'm going to go ahead and close this.
