### ISSUE TITLE
The current PWA id (app_id) is used for system integration (tile, taskbar)

### ISSUE THREAD

**Issue by sunggook** [w3c/manifest#953]
Migration to the new scheme of global id should work internally in the browser, but I wonder how it will address system integration.  In Windows, the identity is used for shortcut, tile on start, pinned taskbar, file handler, etc. I assume that some of them could be updatable without user notice, but some of them aren't; pinned icon on Start or Taskbar location will be changed or removed by different app_id, then user think their existing apps are disappeared (uninstalled) or move randomly.

**Comment by dmurph** [comment]
pwa id / app_id is currently not actually defined in the spec - that's what we're trying to work out with https://github.com/philloooo/pwa-unique-id and https://github.com/w3c/manifest/issues/586.

Regarding your question - I agree that some of might not be updatable. If the id scheme changes somehow, the user agent might have to support those old ids indefinitely.

**Comment by marcoscaceres** [comment]
I'm going to close as a duplicate of #586.
