### ISSUE TITLE
prefer_related_applications is single engine feature

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/manifest#957]
The `prefer_related_applications` member of this specification currently only has a single implementation. As such, it has been marked "[at risk](https://www.w3.org/2020/Process-20200915/#at-risk)" as per the W3C Process, meaning that:

> [The feature] may be removed before advancement to Proposed Recommendation without a requirement to publish a new Candidate Recommendation.

The Web Apps Working Group is seeking a second implementation in order to keep this feature in the specification.

**Comment by christianliebel** [comment]
Considering this feature has remained single-engine, I would suggest moving it to Manifest App Info.

@marcoscaceres @dmurph @diekus @kenchris Any objections?

**Comment by dmurph** [comment]
Same objection - AFAIK this should go then in the WICG/manifest_incubations

**Comment by christianliebel** [comment]
Makes sense!
