### ISSUE TITLE
Register media type with IANA

### ISSUE THREAD

**Issue by christianliebel** [w3c/manifest#970]
The `application/manifest+json` media type should be registered with IANA "[o]ne to two months prior to Candidate Recommendation" (https://www.w3.org/2020/01/registering-mediatypes).

**Comment by marcoscaceres** [comment]
Emailed IANA. Blocked on waiting to hear back. I don't expect any issues with the registration.

**Comment by plehegar** [comment]
https://mailarchive.ietf.org/arch/msg/media-types/qm2LPP66PTi6VN5LgBGs7vLYwzo/

**Comment by plehegar** [comment]
Next step will be to fill the IANA form.

**Comment by marcoscaceres** [comment]
Reminder to fill out the actual IANA form.

**Comment by marcoscaceres** [comment]
Form filled out and sent. Progress can be tracked at:
https://tools.iana.org/public-view/viewticket/1198833

**Comment by plehegar** [comment]
I validated the request on the W3C side.

**Comment by marcoscaceres** [comment]
https://www.iana.org/assignments/media-types/application/manifest+json
