### ISSUE TITLE
Extension of the Application Manifest -> MiniApps Manifest  

### ISSUE THREAD

**Issue by espinr** [w3c/manifest#974]
Hi team,

As co-editor of the [MiniApp Manifest spec](https://w3c.github.io/miniapp-manifest/), before moving ahead to the FPWG, I would like to align with you in the process to create homogeneous specifications. 

The current MiniApps Manifest specification includes references to the [Application Manifest members](https://w3c.github.io/miniapp-manifest/#webappmanifest-members) and defines some [supplementary ones](https://w3c.github.io/miniapp-manifest/#supplementary-manifest-members). Following the extensibility recommendations, we have defined the algorithms to process these MiniApp members, using the manifest [extension point](https://www.w3.org/TR/appmanifest/#dfn-extension-point).

We have indicated this in the [Processing the manifest](https://w3c.github.io/miniapp-manifest/#processing) section. **I wonder if [this way](https://w3c.github.io/miniapp-manifest/#processing) is correct, or we should also indicate it formally using Infra.** 

Thanks in advance.

**Comment by marcoscaceres** [comment]
Hi @espinr, yes, the way you've specified things looks ok. No need to indicate that you are using Infra, as that's done automatically in there References section. 

However, in some of your processing you "return failure", but then don't deal with the failures.

**Comment by espinr** [comment]
Thanks, @marcoscaceres.  

> However, in some of your processing you "return failure", but then don't deal with the failures.

Good point, thanks! Yes, we should review the whole algorithm. It's the first version and it might have some inconsistencies.
