### ISSUE TITLE
Registering as file extension / content-type handler

### ISSUE THREAD

**Issue by brettz9** [w3c/manifest#976]
IIRC, someone had suggested previously that webapp manifests were going to handle this, so if so, I'd be grateful for a reference.

If not, I'd like to request that OS' begin to support the likes of my https://github.com/brettz9/webappfind project (recent browser versions have apparently broken at least some of its functionality).

Basically, it allows one to use "Open with" on one's desktop and have the file contents be shuttled off directly into a web app--no need for drag-and-drop, or a file dialog.

If anyone wants more rationales behind the "why", you can see the video on my project page, but I think it should be pretty self-explanatory why someone would want to be able to open up local HTML or JavaScript files into a web-based IDE, or open up images into an image editor, etc.

Thanks!

**Comment by tomayac** [comment]
This is what [File Handling](https://web.dev/file-handling/) is about.
